CREATE PROCEDURE CSP_SYNC_EVT_CLASS

      @TableParam TVP_EVT_CLASS READONLY

AS
BEGIN

	BEGIN TRY

		BEGIN TRANSACTION

			MERGE EVT_CLASS WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON

				TARGET.ORG_CODE = SOURCE.ORG_CODE AND
				TARGET.EVT_CLASS = SOURCE.EVT_CLASS

			WHEN MATCHED AND (

				TARGET.EVT_CLS_DESC != SOURCE.EVT_CLS_DESC OR
				TARGET.SCOPE != SOURCE.SCOPE OR
				TARGET.DEL != SOURCE.DEL OR
				TARGET.CHG != SOURCE.CHG OR
				TARGET.DEL_FOCUS != SOURCE.DEL_FOCUS OR
				TARGET.RETIRE != SOURCE.RETIRE OR
				TARGET.UPD_STAMP != SOURCE.UPD_STAMP OR
				TARGET.UPD_USER_ID != SOURCE.UPD_USER_ID OR
				TARGET.ENT_STAMP != SOURCE.ENT_STAMP OR
				TARGET.ENT_USER_ID != SOURCE.ENT_USER_ID OR
				TARGET.SEQUENCE != SOURCE.SEQUENCE OR
				TARGET.EVT_CLS_DESC_ALT1 != SOURCE.EVT_CLS_DESC_ALT1 OR
				TARGET.EVT_CLS_DESC_ALT2 != SOURCE.EVT_CLS_DESC_ALT2 OR
				TARGET.EVT_CLS_DESC_ALT3 != SOURCE.EVT_CLS_DESC_ALT3 OR
				TARGET.EVT_CLS_DESC_ALT4 != SOURCE.EVT_CLS_DESC_ALT4 OR
				TARGET.EVT_CLS_DESC_ALT5 != SOURCE.EVT_CLS_DESC_ALT5 )

			THEN UPDATE SET

				TARGET.EVT_CLS_DESC = SOURCE.EVT_CLS_DESC,
				TARGET.SCOPE = SOURCE.SCOPE,
				TARGET.DEL = SOURCE.DEL,
				TARGET.CHG = SOURCE.CHG,
				TARGET.DEL_FOCUS = SOURCE.DEL_FOCUS,
				TARGET.RETIRE = SOURCE.RETIRE,
				TARGET.UPD_STAMP = SOURCE.UPD_STAMP,
				TARGET.UPD_USER_ID = SOURCE.UPD_USER_ID,
				TARGET.ENT_STAMP = SOURCE.ENT_STAMP,
				TARGET.ENT_USER_ID = SOURCE.ENT_USER_ID,
				TARGET.SEQUENCE = SOURCE.SEQUENCE,
				TARGET.EVT_CLS_DESC_ALT1 = SOURCE.EVT_CLS_DESC_ALT1,
				TARGET.EVT_CLS_DESC_ALT2 = SOURCE.EVT_CLS_DESC_ALT2,
				TARGET.EVT_CLS_DESC_ALT3 = SOURCE.EVT_CLS_DESC_ALT3,
				TARGET.EVT_CLS_DESC_ALT4 = SOURCE.EVT_CLS_DESC_ALT4,
				TARGET.EVT_CLS_DESC_ALT5 = SOURCE.EVT_CLS_DESC_ALT5

			WHEN NOT MATCHED BY TARGET THEN INSERT (
				ORG_CODE,
				EVT_CLASS,
				EVT_CLS_DESC,
				SCOPE,
				DEL,
				CHG,
				DEL_FOCUS,
				RETIRE,
				UPD_STAMP,
				UPD_USER_ID,
				ENT_STAMP,
				ENT_USER_ID,
				SEQUENCE,
				EVT_CLS_DESC_ALT1,
				EVT_CLS_DESC_ALT2,
				EVT_CLS_DESC_ALT3,
				EVT_CLS_DESC_ALT4,
				EVT_CLS_DESC_ALT5 )

			VALUES (

				SOURCE.ORG_CODE,
				SOURCE.EVT_CLASS,
				SOURCE.EVT_CLS_DESC,
				SOURCE.SCOPE,
				SOURCE.DEL,
				SOURCE.CHG,
				SOURCE.DEL_FOCUS,
				SOURCE.RETIRE,
				SOURCE.UPD_STAMP,
				SOURCE.UPD_USER_ID,
				SOURCE.ENT_STAMP,
				SOURCE.ENT_USER_ID,
				SOURCE.SEQUENCE,
				SOURCE.EVT_CLS_DESC_ALT1,
				SOURCE.EVT_CLS_DESC_ALT2,
				SOURCE.EVT_CLS_DESC_ALT3,
				SOURCE.EVT_CLS_DESC_ALT4,
				SOURCE.EVT_CLS_DESC_ALT5 )

			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);

		COMMIT TRANSACTION;

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION;

		THROW;

	END CATCH;

END;