CREATE TABLE SYNC_METRICS
(
	SYNC_Table VARCHAR(255),
	SYNC_StartTime DATETIME,
	SYNC_EndTime DATETIME,
	SYNC_ElapsedTime DECIMAL(38,3),
	SYNC_FetchTime DECIMAL(38,3),
	SYNC_LoadTime DECIMAL(38,3),
	SYNC_CleanTime DECIMAL(38,3),
	SYNC_MergeTime DECIMAL(38,3),
	SYNC_RowsUpdated BIGINT,
	SYNC_Success BIT
);