CREATE PROCEDURE CSP_SYNC_STATUS_MASTER

      @TableParam TVP_STATUS_MASTER READONLY

AS
BEGIN

	BEGIN TRY
		
		BEGIN TRANSACTION

			MERGE STATUS_MASTER WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON 
			
				TARGET.STATUS_CODE = SOURCE.STATUS_CODE
		
			WHEN MATCHED AND (
				TARGET.STATUS_DESC    != SOURCE.STATUS_DESC    OR
				TARGET.EVT_FUNC_EFB   != SOURCE.EVT_FUNC_EFB   OR
				TARGET.USR_DEFN_STS   != SOURCE.USR_DEFN_STS   OR
				TARGET.ABBR_STS_DESC  != SOURCE.ABBR_STS_DESC  OR
				TARGET.MKT_CTL        != SOURCE.MKT_CTL        OR
				TARGET.MKT_SPL        != SOURCE.MKT_SPL        OR
				TARGET.PHASE_CTL      != SOURCE.PHASE_CTL      OR
				TARGET.USR_STS_3      != SOURCE.USR_STS_3      OR
				TARGET.USR_STS_4      != SOURCE.USR_STS_4      OR
				TARGET.USR_STS_5      != SOURCE.USR_STS_5      OR
				TARGET.USR_STS_6      != SOURCE.USR_STS_6      OR
				TARGET.USR_STS_7      != SOURCE.USR_STS_7      OR
				TARGET.USR_DEFN_LDESC != SOURCE.USR_DEFN_LDESC OR
				TARGET.STS_COLOR      != SOURCE.STS_COLOR	   OR
				TARGET.JOB_FUNC_JFB   != SOURCE.JOB_FUNC_JFB   OR
				TARGET.DEL            != SOURCE.DEL            OR
				TARGET.CHG            != SOURCE.CHG            OR
				TARGET.DEL_FOCUS      != SOURCE.DEL_FOCUS      OR
				TARGET.TXT_COLOR      != SOURCE.TXT_COLOR      OR
				TARGET.ALLOW_BLOCKS   != SOURCE.ALLOW_BLOCKS   OR
				TARGET.LOST_FLAG      != SOURCE.LOST_FLAG      OR
				TARGET.PROP_CALC      != SOURCE.PROP_CALC )

			THEN UPDATE SET 

				TARGET.STATUS_DESC = SOURCE.STATUS_DESC,
				TARGET.EVT_FUNC_EFB = SOURCE.EVT_FUNC_EFB,
				TARGET.USR_DEFN_STS = SOURCE.USR_DEFN_STS,
				TARGET.ABBR_STS_DESC = SOURCE.ABBR_STS_DESC,
				TARGET.MKT_CTL = SOURCE.MKT_CTL,
				TARGET.MKT_SPL = SOURCE.MKT_SPL,
				TARGET.PHASE_CTL = SOURCE.PHASE_CTL,
				TARGET.USR_STS_3 = SOURCE.USR_STS_3,
				TARGET.USR_STS_4 = SOURCE.USR_STS_4,
				TARGET.USR_STS_5 = SOURCE.USR_STS_5,
				TARGET.USR_STS_6 = SOURCE.USR_STS_6,
				TARGET.USR_STS_7 = SOURCE.USR_STS_7,
				TARGET.USR_DEFN_LDESC = SOURCE.USR_DEFN_LDESC,
				TARGET.STS_COLOR = SOURCE.STS_COLOR,
				TARGET.JOB_FUNC_JFB = SOURCE.JOB_FUNC_JFB,
				TARGET.DEL = SOURCE.DEL,
				TARGET.CHG = SOURCE.CHG,
				TARGET.DEL_FOCUS = SOURCE.DEL_FOCUS,
				TARGET.TXT_COLOR = SOURCE.TXT_COLOR,
				TARGET.ALLOW_BLOCKS = SOURCE.ALLOW_BLOCKS,
				TARGET.LOST_FLAG = SOURCE.LOST_FLAG,
				TARGET.PROP_CALC = SOURCE.PROP_CALC


			WHEN NOT MATCHED BY TARGET THEN INSERT (

				STATUS_CODE,
				STATUS_DESC,
				EVT_FUNC_EFB,
				USR_DEFN_STS,
				ABBR_STS_DESC,
				MKT_CTL,
				MKT_SPL,
				PHASE_CTL,
				USR_STS_3,
				USR_STS_4,
				USR_STS_5,
				USR_STS_6,
				USR_STS_7,
				USR_DEFN_LDESC,
				STS_COLOR,
				JOB_FUNC_JFB,
				DEL,
				CHG,
				DEL_FOCUS,
				TXT_COLOR,
				ALLOW_BLOCKS,
				LOST_FLAG,
				PROP_CALC )

			VALUES (
				SOURCE.STATUS_CODE,
				SOURCE.STATUS_DESC,
				SOURCE.EVT_FUNC_EFB,
				SOURCE.USR_DEFN_STS,
				SOURCE.ABBR_STS_DESC,
				SOURCE.MKT_CTL,
				SOURCE.MKT_SPL,
				SOURCE.PHASE_CTL,
				SOURCE.USR_STS_3,
				SOURCE.USR_STS_4,
				SOURCE.USR_STS_5,
				SOURCE.USR_STS_6,
				SOURCE.USR_STS_7,
				SOURCE.USR_DEFN_LDESC,
				SOURCE.STS_COLOR,
				SOURCE.JOB_FUNC_JFB,
				SOURCE.DEL,
				SOURCE.CHG,
				SOURCE.DEL_FOCUS,
				SOURCE.TXT_COLOR,
				SOURCE.ALLOW_BLOCKS,
				SOURCE.LOST_FLAG,
				SOURCE.PROP_CALC
			)
			
			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);
		
		COMMIT TRANSACTION;

	END TRY
	
	BEGIN CATCH

		ROLLBACK TRANSACTION;
		
		THROW;

	END CATCH;

END;