CREATE TYPE dbo.TVP_TRANS_TYPES AS TABLE
(
	[TSM] [nvarchar](11) NOT NULL,
	[ORG_CODE] [nvarchar](2) NOT NULL,
	[TRANS_TYPE] [nvarchar](3) NOT NULL,
	[TRANS_SOURCE] [nvarchar](2) NOT NULL,
	[TRANS_METHOD] [nvarchar](6) NOT NULL,
	[TRANS_DESC] [nvarchar](100) NULL,
	[STATUS] [nvarchar](1) NULL,
	[MEMO_TYPE] [nvarchar](1) NULL,
	[REF_REQ] [nvarchar](1) NULL,
	[EXPIR_REQ] [nvarchar](1) NULL,
	[CONTROL_REQ] [nvarchar](1) NULL,
	[CC_NBR_REQ] [nvarchar](1) NULL,
	[CC_ID_REQ] [nvarchar](1) NULL,
	[TRANS_CLASS] [nvarchar](1) NULL,
	[TRANS_IND] [nvarchar](1) NULL,
	[REV_DEPOSIT] [nvarchar](1) NULL,
	[REV_TYPE] [nvarchar](3) NULL,
	[CURRENCY] [nvarchar](3) NULL,
	[TRANSFER] [nvarchar](1) NULL,
	[GROUP] [nvarchar](6) NULL,
	[ACCRUE] [nvarchar](3) NULL,
	[LATE_CHARGE] [nvarchar](3) NULL,
	[CC_FIRST_NUM] [nvarchar](2) NULL,
	[CC_MERCH_ID] [nvarchar](240) NULL,
	[CC_AUTH_USER] [nvarchar](400) NULL,
	[CC_AUTH_PWD] [nvarchar](240) NULL,
	[ENT_STAMP] [datetime] NULL,
	[ENT_USER_ID] [nvarchar](10) NULL,
	[UPD_STAMP] [datetime] NULL,
	[UPD_USER_ID] [nvarchar](10) NULL,
	[ALLOW_FINAL_INV] [nvarchar](1) NULL,
	[REFUND] [nvarchar](1) NULL,
	[ALT_TRANS_DESC_1] [nvarchar](100) NULL,
	[ALT_TRANS_DESC_2] [nvarchar](100) NULL,
	[ALT_TRANS_DESC_3] [nvarchar](100) NULL,
	[ALT_TRANS_DESC_4] [nvarchar](100) NULL,
	[ALT_TRANS_DESC_5] [nvarchar](100) NULL,
	[SOURCE_DEFAULT] [nvarchar](2) NULL,
	[AUTO_AUTHORIZE] [nvarchar](1) NULL,
	[CB_TRANS] [nvarchar](1) NULL,
	[USER_REF_REQ] [nvarchar](1) NULL,
	[CC_ID_HIDE] [nvarchar](1) NULL,
	[CC_NBR_HIDE] [nvarchar](1) NULL,
	[CONTROL_HIDE] [nvarchar](1) NULL,
	[EXPIR_HIDE] [nvarchar](1) NULL,
	[REF_HIDE] [nvarchar](1) NULL,
	[USER_REF_HIDE] [nvarchar](1) NULL,
	[GL_HIDE] [nvarchar](1) NULL,
	[PAYOR_INFO_HIDE] [nvarchar](1) NULL,
	[FEE_TSM] [nvarchar](11) NULL,
	[FEE_PCT] [numeric](6, 4) NULL,
	[FEE_RES_TYPE] [nvarchar](6) NULL,
	[FEE_RES_CODE] [nvarchar](12) NULL,
	[FEE_PCT_AMT] [numeric](8, 4) NULL,
	[FEE_BASIS] [int] NULL,
	[CC_AUTH_SPECS_SEQ_NBR] [int] NULL
	PRIMARY KEY CLUSTERED
	(
		[TSM] ASC,
		[ORG_CODE] ASC
	)
);

