CREATE PROCEDURE CSP_SYNC_ACCT_MASTER

      @TableParam TVP_ACCT_MASTER READONLY

AS
BEGIN

	BEGIN TRY

		BEGIN TRANSACTION

			MERGE ACCT_MASTER WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON

				TARGET.ORG_CODE = SOURCE.ORG_CODE AND
				TARGET.ACCT_CODE = SOURCE.ACCT_CODE

			WHEN MATCHED AND (
				TARGET.ORG_CODE != SOURCE.ORG_CODE OR
				TARGET.ACCT_CODE != SOURCE.ACCT_CODE OR
				TARGET.MAIN_ACCT != SOURCE.MAIN_ACCT OR
				TARGET.NAME != SOURCE.NAME OR
				TARGET.TYPE != SOURCE.TYPE OR
				TARGET.CLASS != SOURCE.CLASS OR
				TARGET.STATUS != SOURCE.STATUS OR
				TARGET.LEGAL_NAME != SOURCE.LEGAL_NAME OR
				TARGET.COMPANY_NAME != SOURCE.COMPANY_NAME OR
				TARGET.ALPHA_SEARCH_KEY != SOURCE.ALPHA_SEARCH_KEY OR
				TARGET.ACRONYM != SOURCE.ACRONYM OR
				TARGET.ADDRESS_L1 != SOURCE.ADDRESS_L1 OR
				TARGET.ADDRESS_L2 != SOURCE.ADDRESS_L2 OR
				TARGET.ADDRESS_L3 != SOURCE.ADDRESS_L3 OR
				TARGET.ADDRESS_L4 != SOURCE.ADDRESS_L4 OR
				TARGET.ADDRESS_L5 != SOURCE.ADDRESS_L5 OR
				TARGET.ADDRESS_L6 != SOURCE.ADDRESS_L6 OR
				TARGET.CITY != SOURCE.CITY OR
				TARGET.STATE != SOURCE.STATE OR
				TARGET.POSTAL_CODE != SOURCE.POSTAL_CODE OR
				TARGET.COUNTRY != SOURCE.COUNTRY OR
				TARGET.MAIN_PHONE != SOURCE.MAIN_PHONE OR
				TARGET.MAIN_FAX != SOURCE.MAIN_FAX OR
				TARGET.MOBILE != SOURCE.MOBILE OR
				TARGET.PERS_PHONE != SOURCE.PERS_PHONE OR
				TARGET.EMAIL_ADDRESS != SOURCE.EMAIL_ADDRESS OR
				TARGET.WEB_ADDRESS != SOURCE.WEB_ADDRESS OR
				TARGET.SALES_REGION != SOURCE.SALES_REGION OR
				TARGET.REP_CODE != SOURCE.REP_CODE OR
				TARGET.MKT_SEG_1 != SOURCE.MKT_SEG_1 OR
				TARGET.MKT_SEG_2 != SOURCE.MKT_SEG_2 OR
				TARGET.KEYWORD_1 != SOURCE.KEYWORD_1 OR
				TARGET.KEYWORD_2 != SOURCE.KEYWORD_2 OR
				TARGET.MKT_SIZE != SOURCE.MKT_SIZE OR
				TARGET.MKT_SIZE_UOM != SOURCE.MKT_SIZE_UOM OR
				TARGET.IACVB_CODE != SOURCE.IACVB_CODE OR
				TARGET.EVT_SALES_DESIG != SOURCE.EVT_SALES_DESIG OR
				TARGET.TOUR_DESIG != SOURCE.TOUR_DESIG OR
				TARGET.PUBREL_DESIG != SOURCE.PUBREL_DESIG OR
				TARGET.MEMBER_DESIG != SOURCE.MEMBER_DESIG OR
				TARGET.AR_DESIG != SOURCE.AR_DESIG OR
				TARGET.AP_DESIG != SOURCE.AP_DESIG OR
				TARGET.VISITOR_DESIG != SOURCE.VISITOR_DESIG OR
				TARGET.REGIS_DESIG != SOURCE.REGIS_DESIG OR
				TARGET.PERS_DESIG != SOURCE.PERS_DESIG OR
				TARGET.ASSOC_DESIG != SOURCE.ASSOC_DESIG OR
				TARGET.POSITION != SOURCE.POSITION OR
				TARGET.TITLE != SOURCE.TITLE OR
				TARGET.PREFIX != SOURCE.PREFIX OR
				TARGET.FIRST_NAME != SOURCE.FIRST_NAME OR
				TARGET.MIDDLE_INITIAL != SOURCE.MIDDLE_INITIAL OR
				TARGET.LAST_NAME != SOURCE.LAST_NAME OR
				TARGET.LAST_NAME2 != SOURCE.LAST_NAME2 OR
				TARGET.SUFFIX != SOURCE.SUFFIX OR
				TARGET.NICKNAME != SOURCE.NICKNAME OR
				TARGET.DEPT != SOURCE.DEPT OR
				TARGET.SALUTATION != SOURCE.SALUTATION OR
				TARGET.BIRTHDAY != SOURCE.BIRTHDAY OR
				TARGET.TAX_ID != SOURCE.TAX_ID OR
				TARGET.ACCURACY != SOURCE.ACCURACY OR
				TARGET.SELECT != SOURCE.SELECT OR
				TARGET.USERID != SOURCE.USERID OR
				TARGET.PRIVILEGED != SOURCE.PRIVILEGED OR
				TARGET.DIRECT_MAIL != SOURCE.DIRECT_MAIL OR
				TARGET.DUP_STS != SOURCE.DUP_STS OR
				TARGET.DUP_MULTI != SOURCE.DUP_MULTI OR
				TARGET.DUP_TYPEOF_DATA != SOURCE.DUP_TYPEOF_DATA OR
				TARGET.DUP_CONSOL_ACCT != SOURCE.DUP_CONSOL_ACCT OR
				TARGET.LANG_PREF != SOURCE.LANG_PREF OR
				TARGET.ENTER_STAMP != SOURCE.ENTER_STAMP OR
				TARGET.ENTER_USERID != SOURCE.ENTER_USERID OR
				TARGET.UPD_STAMP != SOURCE.UPD_STAMP OR
				TARGET.UPD_USERID != SOURCE.UPD_USERID OR
				TARGET.ACCT_SECURITY != SOURCE.ACCT_SECURITY OR
				TARGET.INET_LOGON != SOURCE.INET_LOGON OR
				TARGET.INET_PWD != SOURCE.INET_PWD OR
				TARGET.SHIP_METHOD != SOURCE.SHIP_METHOD OR
				TARGET.GENDER != SOURCE.GENDER OR
				TARGET.LANG_CODE != SOURCE.LANG_CODE OR
				TARGET.EFAX_ADDRESS != SOURCE.EFAX_ADDRESS OR
				TARGET.ALERT_FREQ != SOURCE.ALERT_FREQ OR
				TARGET.ALERT_LEAD != SOURCE.ALERT_LEAD OR
				TARGET.ALERT_EMAIL != SOURCE.ALERT_EMAIL OR
				TARGET.USE_ALERT != SOURCE.USE_ALERT OR
				TARGET.TITLE_2 != SOURCE.TITLE_2 OR
				TARGET.ADDR_LBL_01 != SOURCE.ADDR_LBL_01 OR
				TARGET.ADDR_LBL_02 != SOURCE.ADDR_LBL_02 OR
				TARGET.ADDR_LBL_03 != SOURCE.ADDR_LBL_03 OR
				TARGET.ADDR_LBL_04 != SOURCE.ADDR_LBL_04 OR
				TARGET.ADDR_LBL_05 != SOURCE.ADDR_LBL_05 OR
				TARGET.ADDR_LBL_06 != SOURCE.ADDR_LBL_06 OR
				TARGET.ADDR_LBL_07 != SOURCE.ADDR_LBL_07 OR
				TARGET.ADDR_LBL_08 != SOURCE.ADDR_LBL_08 OR
				TARGET.ADDR_LBL_09 != SOURCE.ADDR_LBL_09 OR
				TARGET.ADDR_LBL_10 != SOURCE.ADDR_LBL_10 OR
				TARGET.HOTEL_FLAG != SOURCE.HOTEL_FLAG OR
				TARGET.HOTEL_RATING != SOURCE.HOTEL_RATING OR
				TARGET.HOTEL_CAPACITY != SOURCE.HOTEL_CAPACITY OR
				TARGET.CHK_IN_TIME != SOURCE.CHK_IN_TIME OR
				TARGET.CHK_OUT_TIME != SOURCE.CHK_OUT_TIME OR
				TARGET.METH_OF_NOTIFY != SOURCE.METH_OF_NOTIFY OR
				TARGET.PAY_LOCATION != SOURCE.PAY_LOCATION OR
				TARGET.PROP_CNTCT != SOURCE.PROP_CNTCT OR
				TARGET.PROP_CNTCT_ORG != SOURCE.PROP_CNTCT_ORG OR
				TARGET.MULTI_ORG_ACCT != SOURCE.MULTI_ORG_ACCT OR
				TARGET.SYNC_ORG != SOURCE.SYNC_ORG OR
				TARGET.SYNC_ACCT != SOURCE.SYNC_ACCT OR
				TARGET.SYNC_STS != SOURCE.SYNC_STS OR
				TARGET.PP_NBR != SOURCE.PP_NBR OR
				TARGET.PP_ISSUE_LOC != SOURCE.PP_ISSUE_LOC OR
				TARGET.PP_ISSUE_DATE != SOURCE.PP_ISSUE_DATE OR
				TARGET.PP_EXP_DATE != SOURCE.PP_EXP_DATE OR
				TARGET.BIRTH_PLACE != SOURCE.BIRTH_PLACE OR
				TARGET.NATIONALITY != SOURCE.NATIONALITY OR
				TARGET.ID_NBR != SOURCE.ID_NBR OR
				TARGET.SPKR_DESIG != SOURCE.SPKR_DESIG OR
				TARGET.EXTERNAL_CODE != SOURCE.EXTERNAL_CODE OR
				TARGET.EVT_SALES_STS != SOURCE.EVT_SALES_STS OR
				TARGET.TOUR_STS != SOURCE.TOUR_STS OR
				TARGET.PUBREL_STS != SOURCE.PUBREL_STS OR
				TARGET.MEMBER_STS != SOURCE.MEMBER_STS OR
				TARGET.AR_STS != SOURCE.AR_STS OR
				TARGET.AP_STS != SOURCE.AP_STS OR
				TARGET.VISITOR_STS != SOURCE.VISITOR_STS OR
				TARGET.REGIS_STS != SOURCE.REGIS_STS OR
				TARGET.PERS_STS != SOURCE.PERS_STS OR
				TARGET.SPKR_STS != SOURCE.SPKR_STS OR
				TARGET.HOTEL_CODE != SOURCE.HOTEL_CODE OR
				TARGET.REP_CODE_2 != SOURCE.REP_CODE_2 OR
				TARGET.REP_CODE_3 != SOURCE.REP_CODE_3 OR
				TARGET.MAX_REG_HRS != SOURCE.MAX_REG_HRS OR
				TARGET.PRS_POSITION != SOURCE.PRS_POSITION OR
				TARGET.PRS_DEPT != SOURCE.PRS_DEPT OR
				TARGET.PURGE_IND != SOURCE.PURGE_IND OR
				TARGET.PURGE_VALIDATE != SOURCE.PURGE_VALIDATE OR
				TARGET.PROP_SORT_ORDER != SOURCE.PROP_SORT_ORDER OR
				TARGET.UNIQUE_ID != SOURCE.UNIQUE_ID OR
				TARGET.TAX_SCHEME != SOURCE.TAX_SCHEME OR
				TARGET.TAX_REG_STS != SOURCE.TAX_REG_STS OR
				TARGET.PREF_CNTCT_METHOD != SOURCE.PREF_CNTCT_METHOD OR
				TARGET.SOCIAL_NETWORK_1 != SOURCE.SOCIAL_NETWORK_1 OR
				TARGET.SOCIAL_NETWORK_2 != SOURCE.SOCIAL_NETWORK_2 OR
				TARGET.SOCIAL_NETWORK_3 != SOURCE.SOCIAL_NETWORK_3 OR
				TARGET.PRIMARY_ACCT != SOURCE.PRIMARY_ACCT OR
				TARGET.EXH_RANK_POINTS != SOURCE.EXH_RANK_POINTS OR
				TARGET.EMAIL_DOMAIN != SOURCE.EMAIL_DOMAIN OR
				TARGET.ANNUAL_REVENUE != SOURCE.ANNUAL_REVENUE OR
				TARGET.NUM_EMPLOYEES != SOURCE.NUM_EMPLOYEES OR
				TARGET.BIO != SOURCE.BIO OR
				TARGET.LEAD != SOURCE.LEAD )

			THEN UPDATE SET

				TARGET.MAIN_ACCT = SOURCE.MAIN_ACCT,
				TARGET.NAME = SOURCE.NAME,
				TARGET.TYPE = SOURCE.TYPE,
				TARGET.CLASS = SOURCE.CLASS,
				TARGET.STATUS = SOURCE.STATUS,
				TARGET.LEGAL_NAME = SOURCE.LEGAL_NAME,
				TARGET.COMPANY_NAME = SOURCE.COMPANY_NAME,
				TARGET.ALPHA_SEARCH_KEY = SOURCE.ALPHA_SEARCH_KEY,
				TARGET.ACRONYM = SOURCE.ACRONYM,
				TARGET.ADDRESS_L1 = SOURCE.ADDRESS_L1,
				TARGET.ADDRESS_L2 = SOURCE.ADDRESS_L2,
				TARGET.ADDRESS_L3 = SOURCE.ADDRESS_L3,
				TARGET.ADDRESS_L4 = SOURCE.ADDRESS_L4,
				TARGET.ADDRESS_L5 = SOURCE.ADDRESS_L5,
				TARGET.ADDRESS_L6 = SOURCE.ADDRESS_L6,
				TARGET.CITY = SOURCE.CITY,
				TARGET.STATE = SOURCE.STATE,
				TARGET.POSTAL_CODE = SOURCE.POSTAL_CODE,
				TARGET.COUNTRY = SOURCE.COUNTRY,
				TARGET.MAIN_PHONE = SOURCE.MAIN_PHONE,
				TARGET.MAIN_FAX = SOURCE.MAIN_FAX,
				TARGET.MOBILE = SOURCE.MOBILE,
				TARGET.PERS_PHONE = SOURCE.PERS_PHONE,
				TARGET.EMAIL_ADDRESS = SOURCE.EMAIL_ADDRESS,
				TARGET.WEB_ADDRESS = SOURCE.WEB_ADDRESS,
				TARGET.SALES_REGION = SOURCE.SALES_REGION,
				TARGET.REP_CODE = SOURCE.REP_CODE,
				TARGET.MKT_SEG_1 = SOURCE.MKT_SEG_1,
				TARGET.MKT_SEG_2 = SOURCE.MKT_SEG_2,
				TARGET.KEYWORD_1 = SOURCE.KEYWORD_1,
				TARGET.KEYWORD_2 = SOURCE.KEYWORD_2,
				TARGET.MKT_SIZE = SOURCE.MKT_SIZE,
				TARGET.MKT_SIZE_UOM = SOURCE.MKT_SIZE_UOM,
				TARGET.IACVB_CODE = SOURCE.IACVB_CODE,
				TARGET.EVT_SALES_DESIG = SOURCE.EVT_SALES_DESIG,
				TARGET.TOUR_DESIG = SOURCE.TOUR_DESIG,
				TARGET.PUBREL_DESIG = SOURCE.PUBREL_DESIG,
				TARGET.MEMBER_DESIG = SOURCE.MEMBER_DESIG,
				TARGET.AR_DESIG = SOURCE.AR_DESIG,
				TARGET.AP_DESIG = SOURCE.AP_DESIG,
				TARGET.VISITOR_DESIG = SOURCE.VISITOR_DESIG,
				TARGET.REGIS_DESIG = SOURCE.REGIS_DESIG,
				TARGET.PERS_DESIG = SOURCE.PERS_DESIG,
				TARGET.ASSOC_DESIG = SOURCE.ASSOC_DESIG,
				TARGET.POSITION = SOURCE.POSITION,
				TARGET.TITLE = SOURCE.TITLE,
				TARGET.PREFIX = SOURCE.PREFIX,
				TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
				TARGET.MIDDLE_INITIAL = SOURCE.MIDDLE_INITIAL,
				TARGET.LAST_NAME = SOURCE.LAST_NAME,
				TARGET.LAST_NAME2 = SOURCE.LAST_NAME2,
				TARGET.SUFFIX = SOURCE.SUFFIX,
				TARGET.NICKNAME = SOURCE.NICKNAME,
				TARGET.DEPT = SOURCE.DEPT,
				TARGET.SALUTATION = SOURCE.SALUTATION,
				TARGET.BIRTHDAY = SOURCE.BIRTHDAY,
				TARGET.TAX_ID = SOURCE.TAX_ID,
				TARGET.ACCURACY = SOURCE.ACCURACY,
				TARGET.SELECT = SOURCE.SELECT,
				TARGET.USERID = SOURCE.USERID,
				TARGET.PRIVILEGED = SOURCE.PRIVILEGED,
				TARGET.DIRECT_MAIL = SOURCE.DIRECT_MAIL,
				TARGET.DUP_STS = SOURCE.DUP_STS,
				TARGET.DUP_MULTI = SOURCE.DUP_MULTI,
				TARGET.DUP_TYPEOF_DATA = SOURCE.DUP_TYPEOF_DATA,
				TARGET.DUP_CONSOL_ACCT = SOURCE.DUP_CONSOL_ACCT,
				TARGET.LANG_PREF = SOURCE.LANG_PREF,
				TARGET.ENTER_STAMP = SOURCE.ENTER_STAMP,
				TARGET.ENTER_USERID = SOURCE.ENTER_USERID,
				TARGET.UPD_STAMP = SOURCE.UPD_STAMP,
				TARGET.UPD_USERID = SOURCE.UPD_USERID,
				TARGET.ACCT_SECURITY = SOURCE.ACCT_SECURITY,
				TARGET.INET_LOGON = SOURCE.INET_LOGON,
				TARGET.INET_PWD = SOURCE.INET_PWD,
				TARGET.SHIP_METHOD = SOURCE.SHIP_METHOD,
				TARGET.GENDER = SOURCE.GENDER,
				TARGET.LANG_CODE = SOURCE.LANG_CODE,
				TARGET.EFAX_ADDRESS = SOURCE.EFAX_ADDRESS,
				TARGET.ALERT_FREQ = SOURCE.ALERT_FREQ,
				TARGET.ALERT_LEAD = SOURCE.ALERT_LEAD,
				TARGET.ALERT_EMAIL = SOURCE.ALERT_EMAIL,
				TARGET.USE_ALERT = SOURCE.USE_ALERT,
				TARGET.TITLE_2 = SOURCE.TITLE_2,
				TARGET.ADDR_LBL_01 = SOURCE.ADDR_LBL_01,
				TARGET.ADDR_LBL_02 = SOURCE.ADDR_LBL_02,
				TARGET.ADDR_LBL_03 = SOURCE.ADDR_LBL_03,
				TARGET.ADDR_LBL_04 = SOURCE.ADDR_LBL_04,
				TARGET.ADDR_LBL_05 = SOURCE.ADDR_LBL_05,
				TARGET.ADDR_LBL_06 = SOURCE.ADDR_LBL_06,
				TARGET.ADDR_LBL_07 = SOURCE.ADDR_LBL_07,
				TARGET.ADDR_LBL_08 = SOURCE.ADDR_LBL_08,
				TARGET.ADDR_LBL_09 = SOURCE.ADDR_LBL_09,
				TARGET.ADDR_LBL_10 = SOURCE.ADDR_LBL_10,
				TARGET.HOTEL_FLAG = SOURCE.HOTEL_FLAG,
				TARGET.HOTEL_RATING = SOURCE.HOTEL_RATING,
				TARGET.HOTEL_CAPACITY = SOURCE.HOTEL_CAPACITY,
				TARGET.CHK_IN_TIME = SOURCE.CHK_IN_TIME,
				TARGET.CHK_OUT_TIME = SOURCE.CHK_OUT_TIME,
				TARGET.METH_OF_NOTIFY = SOURCE.METH_OF_NOTIFY,
				TARGET.PAY_LOCATION = SOURCE.PAY_LOCATION,
				TARGET.PROP_CNTCT = SOURCE.PROP_CNTCT,
				TARGET.PROP_CNTCT_ORG = SOURCE.PROP_CNTCT_ORG,
				TARGET.MULTI_ORG_ACCT = SOURCE.MULTI_ORG_ACCT,
				TARGET.SYNC_ORG = SOURCE.SYNC_ORG,
				TARGET.SYNC_ACCT = SOURCE.SYNC_ACCT,
				TARGET.SYNC_STS = SOURCE.SYNC_STS,
				TARGET.PP_NBR = SOURCE.PP_NBR,
				TARGET.PP_ISSUE_LOC = SOURCE.PP_ISSUE_LOC,
				TARGET.PP_ISSUE_DATE = SOURCE.PP_ISSUE_DATE,
				TARGET.PP_EXP_DATE = SOURCE.PP_EXP_DATE,
				TARGET.BIRTH_PLACE = SOURCE.BIRTH_PLACE,
				TARGET.NATIONALITY = SOURCE.NATIONALITY,
				TARGET.ID_NBR = SOURCE.ID_NBR,
				TARGET.SPKR_DESIG = SOURCE.SPKR_DESIG,
				TARGET.EXTERNAL_CODE = SOURCE.EXTERNAL_CODE,
				TARGET.EVT_SALES_STS = SOURCE.EVT_SALES_STS,
				TARGET.TOUR_STS = SOURCE.TOUR_STS,
				TARGET.PUBREL_STS = SOURCE.PUBREL_STS,
				TARGET.MEMBER_STS = SOURCE.MEMBER_STS,
				TARGET.AR_STS = SOURCE.AR_STS,
				TARGET.AP_STS = SOURCE.AP_STS,
				TARGET.VISITOR_STS = SOURCE.VISITOR_STS,
				TARGET.REGIS_STS = SOURCE.REGIS_STS,
				TARGET.PERS_STS = SOURCE.PERS_STS,
				TARGET.SPKR_STS = SOURCE.SPKR_STS,
				TARGET.HOTEL_CODE = SOURCE.HOTEL_CODE,
				TARGET.REP_CODE_2 = SOURCE.REP_CODE_2,
				TARGET.REP_CODE_3 = SOURCE.REP_CODE_3,
				TARGET.MAX_REG_HRS = SOURCE.MAX_REG_HRS,
				TARGET.PRS_POSITION = SOURCE.PRS_POSITION,
				TARGET.PRS_DEPT = SOURCE.PRS_DEPT,
				TARGET.PURGE_IND = SOURCE.PURGE_IND,
				TARGET.PURGE_VALIDATE = SOURCE.PURGE_VALIDATE,
				TARGET.PROP_SORT_ORDER = SOURCE.PROP_SORT_ORDER,
				TARGET.UNIQUE_ID = SOURCE.UNIQUE_ID,
				TARGET.TAX_SCHEME = SOURCE.TAX_SCHEME,
				TARGET.TAX_REG_STS = SOURCE.TAX_REG_STS,
				TARGET.PREF_CNTCT_METHOD = SOURCE.PREF_CNTCT_METHOD,
				TARGET.SOCIAL_NETWORK_1 = SOURCE.SOCIAL_NETWORK_1,
				TARGET.SOCIAL_NETWORK_2 = SOURCE.SOCIAL_NETWORK_2,
				TARGET.SOCIAL_NETWORK_3 = SOURCE.SOCIAL_NETWORK_3,
				TARGET.PRIMARY_ACCT = SOURCE.PRIMARY_ACCT,
				TARGET.EXH_RANK_POINTS = SOURCE.EXH_RANK_POINTS,
				TARGET.EMAIL_DOMAIN = SOURCE.EMAIL_DOMAIN,
				TARGET.ANNUAL_REVENUE = SOURCE.ANNUAL_REVENUE,
				TARGET.NUM_EMPLOYEES = SOURCE.NUM_EMPLOYEES,
				TARGET.BIO = SOURCE.BIO,
				TARGET.LEAD = SOURCE.LEAD

			WHEN NOT MATCHED BY TARGET THEN INSERT (

				ORG_CODE,
				ACCT_CODE,
				MAIN_ACCT,
				NAME,
				TYPE,
				CLASS,
				STATUS,
				LEGAL_NAME,
				COMPANY_NAME,
				ALPHA_SEARCH_KEY,
				ACRONYM,
				ADDRESS_L1,
				ADDRESS_L2,
				ADDRESS_L3,
				ADDRESS_L4,
				ADDRESS_L5,
				ADDRESS_L6,
				CITY,
				STATE,
				POSTAL_CODE,
				COUNTRY,
				MAIN_PHONE,
				MAIN_FAX,
				MOBILE,
				PERS_PHONE,
				EMAIL_ADDRESS,
				WEB_ADDRESS,
				SALES_REGION,
				REP_CODE,
				MKT_SEG_1,
				MKT_SEG_2,
				KEYWORD_1,
				KEYWORD_2,
				MKT_SIZE,
				MKT_SIZE_UOM,
				IACVB_CODE,
				EVT_SALES_DESIG,
				TOUR_DESIG,
				PUBREL_DESIG,
				MEMBER_DESIG,
				AR_DESIG,
				AP_DESIG,
				VISITOR_DESIG,
				REGIS_DESIG,
				PERS_DESIG,
				ASSOC_DESIG,
				POSITION,
				TITLE,
				PREFIX,
				FIRST_NAME,
				MIDDLE_INITIAL,
				LAST_NAME,
				LAST_NAME2,
				SUFFIX,
				NICKNAME,
				DEPT,
				SALUTATION,
				BIRTHDAY,
				TAX_ID,
				ACCURACY,
				SELECT,
				USERID,
				PRIVILEGED,
				DIRECT_MAIL,
				DUP_STS,
				DUP_MULTI,
				DUP_TYPEOF_DATA,
				DUP_CONSOL_ACCT,
				LANG_PREF,
				ENTER_STAMP,
				ENTER_USERID,
				UPD_STAMP,
				UPD_USERID,
				ACCT_SECURITY,
				INET_LOGON,
				INET_PWD,
				SHIP_METHOD,
				GENDER,
				LANG_CODE,
				EFAX_ADDRESS,
				ALERT_FREQ,
				ALERT_LEAD,
				ALERT_EMAIL,
				USE_ALERT,
				TITLE_2,
				ADDR_LBL_01,
				ADDR_LBL_02,
				ADDR_LBL_03,
				ADDR_LBL_04,
				ADDR_LBL_05,
				ADDR_LBL_06,
				ADDR_LBL_07,
				ADDR_LBL_08,
				ADDR_LBL_09,
				ADDR_LBL_10,
				HOTEL_FLAG,
				HOTEL_RATING,
				HOTEL_CAPACITY,
				CHK_IN_TIME,
				CHK_OUT_TIME,
				METH_OF_NOTIFY,
				PAY_LOCATION,
				PROP_CNTCT,
				PROP_CNTCT_ORG,
				MULTI_ORG_ACCT,
				SYNC_ORG,
				SYNC_ACCT,
				SYNC_STS,
				PP_NBR,
				PP_ISSUE_LOC,
				PP_ISSUE_DATE,
				PP_EXP_DATE,
				BIRTH_PLACE,
				NATIONALITY,
				ID_NBR,
				SPKR_DESIG,
				EXTERNAL_CODE,
				EVT_SALES_STS,
				TOUR_STS,
				PUBREL_STS,
				MEMBER_STS,
				AR_STS,
				AP_STS,
				VISITOR_STS,
				REGIS_STS,
				PERS_STS,
				SPKR_STS,
				HOTEL_CODE,
				REP_CODE_2,
				REP_CODE_3,
				MAX_REG_HRS,
				PRS_POSITION,
				PRS_DEPT,
				PURGE_IND,
				PURGE_VALIDATE,
				PROP_SORT_ORDER,
				UNIQUE_ID,
				TAX_SCHEME,
				TAX_REG_STS,
				PREF_CNTCT_METHOD,
				SOCIAL_NETWORK_1,
				SOCIAL_NETWORK_2,
				SOCIAL_NETWORK_3,
				PRIMARY_ACCT,
				EXH_RANK_POINTS,
				EMAIL_DOMAIN,
				ANNUAL_REVENUE,
				NUM_EMPLOYEES,
				BIO,
				LEAD )

			VALUES (
				SOURCE.ORG_CODE,
				SOURCE.ACCT_CODE,
				SOURCE.MAIN_ACCT,
				SOURCE.NAME,
				SOURCE.TYPE,
				SOURCE.CLASS,
				SOURCE.STATUS,
				SOURCE.LEGAL_NAME,
				SOURCE.COMPANY_NAME,
				SOURCE.ALPHA_SEARCH_KEY,
				SOURCE.ACRONYM,
				SOURCE.ADDRESS_L1,
				SOURCE.ADDRESS_L2,
				SOURCE.ADDRESS_L3,
				SOURCE.ADDRESS_L4,
				SOURCE.ADDRESS_L5,
				SOURCE.ADDRESS_L6,
				SOURCE.CITY,
				SOURCE.STATE,
				SOURCE.POSTAL_CODE,
				SOURCE.COUNTRY,
				SOURCE.MAIN_PHONE,
				SOURCE.MAIN_FAX,
				SOURCE.MOBILE,
				SOURCE.PERS_PHONE,
				SOURCE.EMAIL_ADDRESS,
				SOURCE.WEB_ADDRESS,
				SOURCE.SALES_REGION,
				SOURCE.REP_CODE,
				SOURCE.MKT_SEG_1,
				SOURCE.MKT_SEG_2,
				SOURCE.KEYWORD_1,
				SOURCE.KEYWORD_2,
				SOURCE.MKT_SIZE,
				SOURCE.MKT_SIZE_UOM,
				SOURCE.IACVB_CODE,
				SOURCE.EVT_SALES_DESIG,
				SOURCE.TOUR_DESIG,
				SOURCE.PUBREL_DESIG,
				SOURCE.MEMBER_DESIG,
				SOURCE.AR_DESIG,
				SOURCE.AP_DESIG,
				SOURCE.VISITOR_DESIG,
				SOURCE.REGIS_DESIG,
				SOURCE.PERS_DESIG,
				SOURCE.ASSOC_DESIG,
				SOURCE.POSITION,
				SOURCE.TITLE,
				SOURCE.PREFIX,
				SOURCE.FIRST_NAME,
				SOURCE.MIDDLE_INITIAL,
				SOURCE.LAST_NAME,
				SOURCE.LAST_NAME2,
				SOURCE.SUFFIX,
				SOURCE.NICKNAME,
				SOURCE.DEPT,
				SOURCE.SALUTATION,
				SOURCE.BIRTHDAY,
				SOURCE.TAX_ID,
				SOURCE.ACCURACY,
				SOURCE.SELECT,
				SOURCE.USERID,
				SOURCE.PRIVILEGED,
				SOURCE.DIRECT_MAIL,
				SOURCE.DUP_STS,
				SOURCE.DUP_MULTI,
				SOURCE.DUP_TYPEOF_DATA,
				SOURCE.DUP_CONSOL_ACCT,
				SOURCE.LANG_PREF,
				SOURCE.ENTER_STAMP,
				SOURCE.ENTER_USERID,
				SOURCE.UPD_STAMP,
				SOURCE.UPD_USERID,
				SOURCE.ACCT_SECURITY,
				SOURCE.INET_LOGON,
				SOURCE.INET_PWD,
				SOURCE.SHIP_METHOD,
				SOURCE.GENDER,
				SOURCE.LANG_CODE,
				SOURCE.EFAX_ADDRESS,
				SOURCE.ALERT_FREQ,
				SOURCE.ALERT_LEAD,
				SOURCE.ALERT_EMAIL,
				SOURCE.USE_ALERT,
				SOURCE.TITLE_2,
				SOURCE.ADDR_LBL_01,
				SOURCE.ADDR_LBL_02,
				SOURCE.ADDR_LBL_03,
				SOURCE.ADDR_LBL_04,
				SOURCE.ADDR_LBL_05,
				SOURCE.ADDR_LBL_06,
				SOURCE.ADDR_LBL_07,
				SOURCE.ADDR_LBL_08,
				SOURCE.ADDR_LBL_09,
				SOURCE.ADDR_LBL_10,
				SOURCE.HOTEL_FLAG,
				SOURCE.HOTEL_RATING,
				SOURCE.HOTEL_CAPACITY,
				SOURCE.CHK_IN_TIME,
				SOURCE.CHK_OUT_TIME,
				SOURCE.METH_OF_NOTIFY,
				SOURCE.PAY_LOCATION,
				SOURCE.PROP_CNTCT,
				SOURCE.PROP_CNTCT_ORG,
				SOURCE.MULTI_ORG_ACCT,
				SOURCE.SYNC_ORG,
				SOURCE.SYNC_ACCT,
				SOURCE.SYNC_STS,
				SOURCE.PP_NBR,
				SOURCE.PP_ISSUE_LOC,
				SOURCE.PP_ISSUE_DATE,
				SOURCE.PP_EXP_DATE,
				SOURCE.BIRTH_PLACE,
				SOURCE.NATIONALITY,
				SOURCE.ID_NBR,
				SOURCE.SPKR_DESIG,
				SOURCE.EXTERNAL_CODE,
				SOURCE.EVT_SALES_STS,
				SOURCE.TOUR_STS,
				SOURCE.PUBREL_STS,
				SOURCE.MEMBER_STS,
				SOURCE.AR_STS,
				SOURCE.AP_STS,
				SOURCE.VISITOR_STS,
				SOURCE.REGIS_STS,
				SOURCE.PERS_STS,
				SOURCE.SPKR_STS,
				SOURCE.HOTEL_CODE,
				SOURCE.REP_CODE_2,
				SOURCE.REP_CODE_3,
				SOURCE.MAX_REG_HRS,
				SOURCE.PRS_POSITION,
				SOURCE.PRS_DEPT,
				SOURCE.PURGE_IND,
				SOURCE.PURGE_VALIDATE,
				SOURCE.PROP_SORT_ORDER,
				SOURCE.UNIQUE_ID,
				SOURCE.TAX_SCHEME,
				SOURCE.TAX_REG_STS,
				SOURCE.PREF_CNTCT_METHOD,
				SOURCE.SOCIAL_NETWORK_1,
				SOURCE.SOCIAL_NETWORK_2,
				SOURCE.SOCIAL_NETWORK_3,
				SOURCE.PRIMARY_ACCT,
				SOURCE.EXH_RANK_POINTS,
				SOURCE.EMAIL_DOMAIN,
				SOURCE.ANNUAL_REVENUE,
				SOURCE.NUM_EMPLOYEES,
				SOURCE.BIO,
				SOURCE.LEAD )

			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);

		COMMIT TRANSACTION;

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION;

		THROW;

	END CATCH;

END;