CREATE TYPE [dbo].[TVP_ACCT_MASTER] AS TABLE
(
	[ORG_CODE] [nvarchar](2) NOT NULL,
	[ACCT_CODE] [nvarchar](8) NOT NULL,
	[MAIN_ACCT] [nvarchar](8) NOT NULL,
	[NAME] [nvarchar](150) NOT NULL,
	[TYPE] [nvarchar](3) NULL,
	[CLASS] [nvarchar](1) NOT NULL,
	[STATUS] [nvarchar](1) NOT NULL,
	[LEGAL_NAME] [nvarchar](150) NULL,
	[COMPANY_NAME] [nvarchar](150) NULL,
	[ALPHA_SEARCH_KEY] [nvarchar](20) NULL,
	[ACRONYM] [nvarchar](10) NULL,
	[ADDRESS_L1] [nvarchar](100) NULL,
	[ADDRESS_L2] [nvarchar](100) NULL,
	[ADDRESS_L3] [nvarchar](100) NULL,
	[ADDRESS_L4] [nvarchar](100) NULL,
	[ADDRESS_L5] [nvarchar](100) NULL,
	[ADDRESS_L6] [nvarchar](100) NULL,
	[CITY] [nvarchar](50) NULL,
	[STATE] [nvarchar](5) NULL,
	[POSTAL_CODE] [nvarchar](25) NULL,
	[COUNTRY] [nvarchar](3) NULL,
	[MAIN_PHONE] [nvarchar](150) NULL,
	[MAIN_FAX] [nvarchar](150) NULL,
	[MOBILE] [nvarchar](150) NULL,
	[PERS_PHONE] [nvarchar](150) NULL,
	[EMAIL_ADDRESS] [nvarchar](150) NULL,
	[WEB_ADDRESS] [nvarchar](150) NULL,
	[SALES_REGION] [nvarchar](4) NULL,
	[REP_CODE] [nvarchar](8) NULL,
	[MKT_SEG_1] [nvarchar](1) NULL,
	[MKT_SEG_2] [nvarchar](3) NULL,
	[KEYWORD_1] [nvarchar](20) NULL,
	[KEYWORD_2] [nvarchar](20) NULL,
	[MKT_SIZE] [numeric](15, 2) NULL,
	[MKT_SIZE_UOM] [nvarchar](3) NULL,
	[IACVB_CODE] [nvarchar](20) NULL,
	[EVT_SALES_DESIG] [nvarchar](1) NULL,
	[TOUR_DESIG] [nvarchar](1) NULL,
	[PUBREL_DESIG] [nvarchar](1) NULL,
	[MEMBER_DESIG] [nvarchar](1) NULL,
	[AR_DESIG] [nvarchar](1) NULL,
	[AP_DESIG] [nvarchar](1) NULL,
	[VISITOR_DESIG] [nvarchar](1) NULL,
	[REGIS_DESIG] [nvarchar](1) NULL,
	[PERS_DESIG] [nvarchar](1) NULL,
	[ASSOC_DESIG] [nvarchar](1) NULL,
	[POSITION] [nvarchar](6) NULL,
	[TITLE] [nvarchar](100) NULL,
	[PREFIX] [nvarchar](100) NULL,
	[FIRST_NAME] [nvarchar](70) NULL,
	[MIDDLE_INITIAL] [nvarchar](10) NULL,
	[LAST_NAME] [nvarchar](70) NULL,
	[LAST_NAME2] [nvarchar](70) NULL,
	[SUFFIX] [nvarchar](100) NULL,
	[NICKNAME] [nvarchar](50) NULL,
	[DEPT] [nvarchar](6) NULL,
	[SALUTATION] [nvarchar](100) NULL,
	[BIRTHDAY] [datetime] NULL,
	[TAX_ID] [nvarchar](20) NULL,
	[ACCURACY] [nvarchar](1) NULL,
	[SELECT] [nvarchar](1) NULL,
	[USERID] [nvarchar](10) NULL,
	[PRIVILEGED] [nvarchar](1) NULL,
	[DIRECT_MAIL] [nvarchar](1) NULL,
	[DUP_STS] [nvarchar](1) NULL,
	[DUP_MULTI] [int] NULL,
	[DUP_TYPEOF_DATA] [nvarchar](10) NULL,
	[DUP_CONSOL_ACCT] [nvarchar](8) NULL,
	[LANG_PREF] [nvarchar](2) NULL,
	[ENTER_STAMP] [datetime] NULL,
	[ENTER_USERID] [nvarchar](10) NULL,
	[UPD_STAMP] [datetime] NULL,
	[UPD_USERID] [nvarchar](10) NULL,
	[ACCT_SECURITY] [nvarchar](10) NULL,
	[INET_LOGON] [nvarchar](1) NULL,
	[INET_PWD] [nvarchar](200) NULL,
	[SHIP_METHOD] [nvarchar](3) NULL,
	[GENDER] [nvarchar](1) NULL,
	[LANG_CODE] [nvarchar](3) NULL,
	[EFAX_ADDRESS] [nvarchar](150) NULL,
	[ALERT_FREQ] [int] NULL,
	[ALERT_LEAD] [int] NULL,
	[ALERT_EMAIL] [nvarchar](150) NULL,
	[USE_ALERT] [nvarchar](1) NULL,
	[TITLE_2] [nvarchar](100) NULL,
	[ADDR_LBL_01] [nvarchar](255) NULL,
	[ADDR_LBL_02] [nvarchar](255) NULL,
	[ADDR_LBL_03] [nvarchar](255) NULL,
	[ADDR_LBL_04] [nvarchar](255) NULL,
	[ADDR_LBL_05] [nvarchar](255) NULL,
	[ADDR_LBL_06] [nvarchar](255) NULL,
	[ADDR_LBL_07] [nvarchar](255) NULL,
	[ADDR_LBL_08] [nvarchar](255) NULL,
	[ADDR_LBL_09] [nvarchar](255) NULL,
	[ADDR_LBL_10] [nvarchar](255) NULL,
	[HOTEL_FLAG] [nvarchar](1) NULL,
	[HOTEL_RATING] [int] NULL,
	[HOTEL_CAPACITY] [int] NULL,
	[CHK_IN_TIME] [datetime] NULL,
	[CHK_OUT_TIME] [datetime] NULL,
	[METH_OF_NOTIFY] [nvarchar](1) NULL,
	[PAY_LOCATION] [nvarchar](3) NULL,
	[PROP_CNTCT] [nvarchar](8) NULL,
	[PROP_CNTCT_ORG] [nvarchar](2) NULL,
	[MULTI_ORG_ACCT] [nvarchar](20) NULL,
	[SYNC_ORG] [nvarchar](2) NULL,
	[SYNC_ACCT] [nvarchar](8) NULL,
	[SYNC_STS] [nvarchar](1) NULL,
	[PP_NBR] [nvarchar](200) NULL,
	[PP_ISSUE_LOC] [nvarchar](50) NULL,
	[PP_ISSUE_DATE] [datetime] NULL,
	[PP_EXP_DATE] [datetime] NULL,
	[BIRTH_PLACE] [nvarchar](200) NULL,
	[NATIONALITY] [nvarchar](3) NULL,
	[ID_NBR] [nvarchar](200) NULL,
	[SPKR_DESIG] [nvarchar](1) NULL,
	[EXTERNAL_CODE] [nvarchar](40) NULL,
	[EVT_SALES_STS] [nvarchar](1) NULL,
	[TOUR_STS] [nvarchar](1) NULL,
	[PUBREL_STS] [nvarchar](1) NULL,
	[MEMBER_STS] [nvarchar](1) NULL,
	[AR_STS] [nvarchar](1) NULL,
	[AP_STS] [nvarchar](1) NULL,
	[VISITOR_STS] [nvarchar](1) NULL,
	[REGIS_STS] [nvarchar](1) NULL,
	[PERS_STS] [nvarchar](1) NULL,
	[SPKR_STS] [nvarchar](1) NULL,
	[HOTEL_CODE] [nvarchar](6) NULL,
	[REP_CODE_2] [nvarchar](8) NULL,
	[REP_CODE_3] [nvarchar](8) NULL,
	[MAX_REG_HRS] [int] NULL,
	[PRS_POSITION] [nvarchar](6) NULL,
	[PRS_DEPT] [nvarchar](6) NULL,
	[PURGE_IND] [nvarchar](3) NULL,
	[PURGE_VALIDATE] [datetime] NULL,
	[PROP_SORT_ORDER] [nvarchar](4) NULL,
	[UNIQUE_ID] [int] NOT NULL,
	[TAX_SCHEME] [nvarchar](12) NULL,
	[TAX_REG_STS] [nvarchar](1) NULL,
	[PREF_CNTCT_METHOD] [nvarchar](4) NULL,
	[SOCIAL_NETWORK_1] [nvarchar](255) NULL,
	[SOCIAL_NETWORK_2] [nvarchar](255) NULL,
	[SOCIAL_NETWORK_3] [nvarchar](255) NULL,
	[PRIMARY_ACCT] [nvarchar](8) NULL,
	[EXH_RANK_POINTS] [int] NULL,
	[EMAIL_DOMAIN] [nvarchar](100) NULL,
	[ANNUAL_REVENUE] [int] NULL,
	[NUM_EMPLOYEES] [int] NULL,
	[BIO] [nvarchar](4000) NULL,
	[LEAD] [nvarchar](1) NULL,
	PRIMARY KEY CLUSTERED
	(
		[ACCT_CODE] ASC,
		[ORG_CODE] ASC
	)
);