CREATE PROCEDURE CSP_SYNC_ACCT_ORDER

      @TableParam TVP_ACCT_ORDER READONLY

AS
BEGIN

	BEGIN TRY
		
		BEGIN TRANSACTION

			MERGE ACCT_ORDER WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON 
			
				TARGET.ORG_CODE = SOURCE.ORG_CODE AND
				TARGET.ORD_NBR = SOURCE.ORD_NBR
		
			WHEN MATCHED AND (
		
				TARGET.SO_SEARCH != SOURCE.SO_SEARCH OR
				TARGET.EVT_ID != SOURCE.EVT_ID OR
				TARGET.ORD_TYPE != SOURCE.ORD_TYPE OR
				TARGET.FUNC_ID != SOURCE.FUNC_ID OR
				TARGET.EVT_SEARCH != SOURCE.EVT_SEARCH OR
				TARGET.FUNC_SEARCH != SOURCE.FUNC_SEARCH OR
				TARGET.ORD_FORM != SOURCE.ORD_FORM OR
				TARGET.ORD_DATE != SOURCE.ORD_DATE OR
				TARGET.ORD_STS != SOURCE.ORD_STS OR
				TARGET.PRT_STS != SOURCE.PRT_STS OR
				TARGET.MET_NOTIFY != SOURCE.MET_NOTIFY OR
				TARGET.CANCEL_DATE != SOURCE.CANCEL_DATE OR
				TARGET.CANCEL_USER != SOURCE.CANCEL_USER OR
				TARGET.CANCEL_BY != SOURCE.CANCEL_BY OR
				TARGET.CANCEL_REASON != SOURCE.CANCEL_REASON OR
				TARGET.PO_NBR != SOURCE.PO_NBR OR
				TARGET.PRICE_LIST != SOURCE.PRICE_LIST OR
				TARGET.PRICE_COLUMN != SOURCE.PRICE_COLUMN OR
				TARGET.ARR_DATE != SOURCE.ARR_DATE OR
				TARGET.ARR_TIME != SOURCE.ARR_TIME OR
				TARGET.DEP_DATE != SOURCE.DEP_DATE OR
				TARGET.DEP_TIME != SOURCE.DEP_TIME OR
				TARGET.BLOCK_CDE != SOURCE.BLOCK_CDE OR
				TARGET.PROP_CODE != SOURCE.PROP_CODE OR
				TARGET.RM_TYPE != SOURCE.RM_TYPE OR
				TARGET.RM_PRICE_CDE != SOURCE.RM_PRICE_CDE OR
				TARGET.NBR_RMS != SOURCE.NBR_RMS OR
				TARGET.COMP_DATE != SOURCE.COMP_DATE OR
				TARGET.COMP_TIME != SOURCE.COMP_TIME OR
				TARGET.COMP_USER != SOURCE.COMP_USER OR
				TARGET.RES_FUNC_ID != SOURCE.RES_FUNC_ID OR
				TARGET.RES_PHASE != SOURCE.RES_PHASE OR
				TARGET.RES_SEQ != SOURCE.RES_SEQ OR
				TARGET.NBR_PERS != SOURCE.NBR_PERS OR
				TARGET.ACCT_ISSUE != SOURCE.ACCT_ISSUE OR
				TARGET.BATCH != SOURCE.BATCH OR
				TARGET.ORD_ACCT != SOURCE.ORD_ACCT OR
				TARGET.ORD_CONTACT != SOURCE.ORD_CONTACT OR
				TARGET.BILL_TO_CUST != SOURCE.BILL_TO_CUST OR
				TARGET.BILL_TO_CONT != SOURCE.BILL_TO_CONT OR
				TARGET.ORD_TOT != SOURCE.ORD_TOT OR
				TARGET.ORD_TAX != SOURCE.ORD_TAX OR
				TARGET.ORD_DUE != SOURCE.ORD_DUE OR
				TARGET.ACT_TOTAL != SOURCE.ACT_TOTAL OR
				TARGET.ACT_TAX != SOURCE.ACT_TAX OR
				TARGET.ACT_DUE != SOURCE.ACT_DUE OR
				TARGET.ACT_PAYMENTS != SOURCE.ACT_PAYMENTS OR
				TARGET.ACT_CREDITS != SOURCE.ACT_CREDITS OR
				TARGET.ORD_CREDITS != SOURCE.ORD_CREDITS OR
				TARGET.COMMENT != SOURCE.COMMENT OR
				TARGET.ACT_INACT != SOURCE.ACT_INACT OR
				TARGET.PRT_FLAG != SOURCE.PRT_FLAG OR
				TARGET.AMT_DUE_IND != SOURCE.AMT_DUE_IND OR
				TARGET.SETUP_ID != SOURCE.SETUP_ID OR
				TARGET.BOOTH_NBR != SOURCE.BOOTH_NBR OR
				TARGET.ORD_DESC != SOURCE.ORD_DESC OR
				TARGET.ORD_SPACE != SOURCE.ORD_SPACE OR
				TARGET.ORD_STS_1 != SOURCE.ORD_STS_1 OR
				TARGET.ORD_STS_2 != SOURCE.ORD_STS_2 OR
				TARGET.INTERNAL != SOURCE.INTERNAL OR
				TARGET.ENT_DATE_ISO != SOURCE.ENT_DATE_ISO OR
				TARGET.ENT_USER_ID != SOURCE.ENT_USER_ID OR
				TARGET.UPD_DATE_ISO != SOURCE.UPD_DATE_ISO OR
				TARGET.UPD_USER_ID != SOURCE.UPD_USER_ID OR
				TARGET.DEL_MARK != SOURCE.DEL_MARK OR
				TARGET.XTRA_ACCT != SOURCE.XTRA_ACCT OR
				TARGET.USER_8X != SOURCE.USER_8X OR
				TARGET.USER_10X != SOURCE.USER_10X OR
				TARGET.USER_DATE != SOURCE.USER_DATE OR
				TARGET.ORDER_DESIG != SOURCE.ORDER_DESIG OR
				TARGET.ORDER_TERMS != SOURCE.ORDER_TERMS OR
				TARGET.SHIP_METHOD != SOURCE.SHIP_METHOD OR
				TARGET.USER_6X != SOURCE.USER_6X OR
				TARGET.USER_8X2 != SOURCE.USER_8X2 OR
				TARGET.USER_10X2 != SOURCE.USER_10X2 OR
				TARGET.SO_PRT != SOURCE.SO_PRT OR
				TARGET.PARENT_FUNC != SOURCE.PARENT_FUNC OR
				TARGET.REQ_CUST != SOURCE.REQ_CUST OR
				TARGET.SO_USER_SEQ != SOURCE.SO_USER_SEQ OR
				TARGET.SO_FUNC_SEQ != SOURCE.SO_FUNC_SEQ OR
				TARGET.SHIP_DOC_ID != SOURCE.SHIP_DOC_ID OR
				TARGET.SETUP_QTY != SOURCE.SETUP_QTY OR
				TARGET.SO_ACT_INACT != SOURCE.SO_ACT_INACT OR
				TARGET.SHORT_NOTE != SOURCE.SHORT_NOTE OR
				TARGET.SO_STATUS != SOURCE.SO_STATUS OR
				TARGET.USER_8X1 != SOURCE.USER_8X1 OR
				TARGET.USER_8X3 != SOURCE.USER_8X3 OR
				TARGET.CONF_ALL_REGIS != SOURCE.CONF_ALL_REGIS OR
				TARGET.REQ_CONTACT != SOURCE.REQ_CONTACT OR
				TARGET.BILL_CYCLE != SOURCE.BILL_CYCLE OR
				TARGET.DUES_CYCLE != SOURCE.DUES_CYCLE OR
				TARGET.RENEWAL_DATE != SOURCE.RENEWAL_DATE OR
				TARGET.CYCLE_DATE != SOURCE.CYCLE_DATE OR
				TARGET.BKG_ORDER != SOURCE.BKG_ORDER OR
				TARGET.TRANS_SOURCE != SOURCE.TRANS_SOURCE OR
				TARGET.INVOICE != SOURCE.INVOICE OR
				TARGET.ORD_SIGN != SOURCE.ORD_SIGN OR
				TARGET.ORD_DAYS != SOURCE.ORD_DAYS OR
				TARGET.TEMPLATE != SOURCE.TEMPLATE OR
				TARGET.WO_CLOSED != SOURCE.WO_CLOSED OR
				TARGET.WO_DUE_DATE != SOURCE.WO_DUE_DATE OR
				TARGET.WO_RUSH != SOURCE.WO_RUSH OR
				TARGET.CURRENCY != SOURCE.CURRENCY OR
				TARGET.FC_ORD_TOT != SOURCE.FC_ORD_TOT OR
				TARGET.FC_ORD_TAX != SOURCE.FC_ORD_TAX OR
				TARGET.FC_ORD_DUE != SOURCE.FC_ORD_DUE OR
				TARGET.FC_ACT_TOT != SOURCE.FC_ACT_TOT OR
				TARGET.FC_ACT_DUE != SOURCE.FC_ACT_DUE OR
				TARGET.FC_ACT_PAYMENTS != SOURCE.FC_ACT_PAYMENTS OR
				TARGET.FC_ACT_CREDITS != SOURCE.FC_ACT_CREDITS OR
				TARGET.FC_ORD_CREDITS != SOURCE.FC_ORD_CREDITS OR
				TARGET.FC_ACT_TAX != SOURCE.FC_ACT_TAX OR
				TARGET.WO_TIME_OFFSET != SOURCE.WO_TIME_OFFSET OR
				TARGET.WO_SIGN != SOURCE.WO_SIGN OR
				TARGET.WO_DAYS != SOURCE.WO_DAYS OR
				TARGET.WO_END_STAMP != SOURCE.WO_END_STAMP OR
				TARGET.PL_CURRENCY != SOURCE.PL_CURRENCY OR
				TARGET.TR_CURRENCY != SOURCE.TR_CURRENCY OR
				TARGET.TRLC_RATE != SOURCE.TRLC_RATE OR
				TARGET.TRFC_RATE != SOURCE.TRFC_RATE OR
				TARGET.TRPL_RATE != SOURCE.TRPL_RATE OR
				TARGET.TAXABLE != SOURCE.TAXABLE OR
				TARGET.TR_ORD_TOT != SOURCE.TR_ORD_TOT OR
				TARGET.TR_ORD_TAX != SOURCE.TR_ORD_TAX OR
				TARGET.TR_ORD_CREDITS != SOURCE.TR_ORD_CREDITS OR
				TARGET.TR_ORD_DUE != SOURCE.TR_ORD_DUE OR
				TARGET.TR_ACT_TOT != SOURCE.TR_ACT_TOT OR
				TARGET.TR_ACT_TAX != SOURCE.TR_ACT_TAX OR
				TARGET.TR_ACT_CREDITS != SOURCE.TR_ACT_CREDITS OR
				TARGET.TR_ACT_DUE != SOURCE.TR_ACT_DUE OR
				TARGET.TR_ACT_PAYMENTS != SOURCE.TR_ACT_PAYMENTS OR
				TARGET.PL_ORD_TOT != SOURCE.PL_ORD_TOT OR
				TARGET.PL_ORD_TAX != SOURCE.PL_ORD_TAX OR
				TARGET.PL_ORD_CREDITS != SOURCE.PL_ORD_CREDITS OR
				TARGET.PL_ORD_DUE != SOURCE.PL_ORD_DUE OR
				TARGET.PL_ACT_TOT != SOURCE.PL_ACT_TOT OR
				TARGET.PL_ACT_TAX != SOURCE.PL_ACT_TAX OR
				TARGET.PL_ACT_CREDITS != SOURCE.PL_ACT_CREDITS OR
				TARGET.PL_ACT_DUE != SOURCE.PL_ACT_DUE OR
				TARGET.PL_ACT_PAYMENTS != SOURCE.PL_ACT_PAYMENTS OR
				TARGET.ASSIGNMENT_NAME != SOURCE.ASSIGNMENT_NAME OR
				TARGET.PAY_PLAN_ID != SOURCE.PAY_PLAN_ID OR
				TARGET.PP_SCHED_CODE != SOURCE.PP_SCHED_CODE OR
				TARGET.NEW_STS != SOURCE.NEW_STS OR
				TARGET.REPRINT != SOURCE.REPRINT OR
				TARGET.CONFIG_CODE != SOURCE.CONFIG_CODE OR
				TARGET.NG_ORD_CONTACT != SOURCE.NG_ORD_CONTACT OR
				TARGET.NG_BTO_CONTACT != SOURCE.NG_BTO_CONTACT OR
				TARGET.NG_REQ_CONTACT != SOURCE.NG_REQ_CONTACT OR
				TARGET.ORD_ACCT_REP != SOURCE.ORD_ACCT_REP OR
				TARGET.ASGN_TOT_SIZE != SOURCE.ASGN_TOT_SIZE OR
				TARGET.ASGN_OPEN_SIDES != SOURCE.ASGN_OPEN_SIDES OR
				TARGET.ASGN_LENGTH != SOURCE.ASGN_LENGTH OR
				TARGET.ASGN_WIDTH != SOURCE.ASGN_WIDTH OR
				TARGET.PROMO_CODE != SOURCE.PROMO_CODE OR
				TARGET.TAX_DETAIL != SOURCE.TAX_DETAIL OR
				TARGET.ALL_PRT != SOURCE.ALL_PRT OR
				TARGET.MULTI_ORG_ACCT != SOURCE.MULTI_ORG_ACCT OR
				TARGET.ALT_ASSIGN_NAME_1 != SOURCE.ALT_ASSIGN_NAME_1 OR
				TARGET.ALT_ASSIGN_NAME_2 != SOURCE.ALT_ASSIGN_NAME_2 OR
				TARGET.USER_REFERENCE != SOURCE.USER_REFERENCE OR
				TARGET.ORD_COST_TOTAL != SOURCE.ORD_COST_TOTAL OR
				TARGET.ACT_COST_TOTAL != SOURCE.ACT_COST_TOTAL OR
				TARGET.REF_INV_NBR != SOURCE.REF_INV_NBR OR
				TARGET.SHIPTO_ACCT != SOURCE.SHIPTO_ACCT OR
				TARGET.SHIPTO_CONT != SOURCE.SHIPTO_CONT OR
				TARGET.ALT_ASSIGN_NAME_3 != SOURCE.ALT_ASSIGN_NAME_3 OR
				TARGET.ALT_ASSIGN_NAME_4 != SOURCE.ALT_ASSIGN_NAME_4 OR
				TARGET.ALT_ASSIGN_NAME_5 != SOURCE.ALT_ASSIGN_NAME_5 OR
				TARGET.ASGN_TOT_DISP_SIZE != SOURCE.ASGN_TOT_DISP_SIZE OR
				TARGET.CONTRACT_SEQ != SOURCE.CONTRACT_SEQ OR
				TARGET.ORD_GLACCT != SOURCE.ORD_GLACCT OR
				TARGET.NEAR_EXHIB != SOURCE.NEAR_EXHIB OR
				TARGET.AWAY_EXHIB != SOURCE.AWAY_EXHIB OR
				TARGET.COMPETITORS != SOURCE.COMPETITORS OR
				TARGET.PREF_ASSIGN != SOURCE.PREF_ASSIGN OR
				TARGET.EXHIB_POINTS != SOURCE.EXHIB_POINTS OR
				TARGET.EXHIB_MI != SOURCE.EXHIB_MI OR
				TARGET.PAVILION != SOURCE.PAVILION OR
				TARGET.EXHIB_TXT_01 != SOURCE.EXHIB_TXT_01 OR
				TARGET.EXHIB_TXT_02 != SOURCE.EXHIB_TXT_02 OR
				TARGET.EXHIB_TXT_03 != SOURCE.EXHIB_TXT_03 OR
				TARGET.EXHIB_NBR_01 != SOURCE.EXHIB_NBR_01 OR
				TARGET.EXHIB_NBR_02 != SOURCE.EXHIB_NBR_02 OR
				TARGET.EXHIB_NBR_03 != SOURCE.EXHIB_NBR_03 OR
				TARGET.EXHIB_DTM_01 != SOURCE.EXHIB_DTM_01 OR
				TARGET.EXHIB_DTM_02 != SOURCE.EXHIB_DTM_02 OR
				TARGET.EXHIB_DTM_03 != SOURCE.EXHIB_DTM_03 OR
				TARGET.OCCURRENCE != SOURCE.OCCURRENCE OR
				TARGET.ORD_FIXED != SOURCE.ORD_FIXED OR
				TARGET.ORD_REV_TRANS != SOURCE.ORD_REV_TRANS OR
				TARGET.COMM_ORDER != SOURCE.COMM_ORDER OR
				TARGET.ORD_ADDR_SEQ != SOURCE.ORD_ADDR_SEQ OR
				TARGET.BILLTO_ADDR_SEQ != SOURCE.BILLTO_ADDR_SEQ OR
				TARGET.REQ_ADDR_SEQ != SOURCE.REQ_ADDR_SEQ OR
				TARGET.SHIPTO_ADDR_SEQ != SOURCE.SHIPTO_ADDR_SEQ OR
				TARGET.OCCURENCE != SOURCE.OCCURENCE OR
				TARGET.MAIN_EXHIB_ORDER != SOURCE.MAIN_EXHIB_ORDER OR
				TARGET.PRJ_ID != SOURCE.PRJ_ID OR
				TARGET.ACCT_DESIG != SOURCE.ACCT_DESIG OR
				TARGET.GEN != SOURCE.GEN OR
				TARGET.TAX_DATE != SOURCE.TAX_DATE OR
				TARGET.AR_CONTROL != SOURCE.AR_CONTROL OR
				TARGET.EXHIBITOR_ID != SOURCE.EXHIBITOR_ID OR
				TARGET.ENT_APP_TYPE != SOURCE.ENT_APP_TYPE OR
				TARGET.CUST_PAY_INFO != SOURCE.CUST_PAY_INFO OR
				TARGET.CUST_PAY_TYPE != SOURCE.CUST_PAY_TYPE OR
				TARGET.DIVISION != SOURCE.DIVISION OR
				TARGET.EXHIB_ORD_NBR != SOURCE.EXHIB_ORD_NBR OR
				TARGET.BOOTH_ORDER != SOURCE.BOOTH_ORDER OR
				TARGET.ORD_CAT_SEQ != SOURCE.ORD_CAT_SEQ )

			THEN UPDATE SET 

				TARGET.SO_SEARCH = SOURCE.SO_SEARCH,
				TARGET.EVT_ID = SOURCE.EVT_ID,
				TARGET.ORD_TYPE = SOURCE.ORD_TYPE,
				TARGET.FUNC_ID = SOURCE.FUNC_ID,
				TARGET.EVT_SEARCH = SOURCE.EVT_SEARCH,
				TARGET.FUNC_SEARCH = SOURCE.FUNC_SEARCH,
				TARGET.ORD_FORM = SOURCE.ORD_FORM,
				TARGET.ORD_DATE = SOURCE.ORD_DATE,
				TARGET.ORD_STS = SOURCE.ORD_STS,
				TARGET.PRT_STS = SOURCE.PRT_STS,
				TARGET.MET_NOTIFY = SOURCE.MET_NOTIFY,
				TARGET.CANCEL_DATE = SOURCE.CANCEL_DATE,
				TARGET.CANCEL_USER = SOURCE.CANCEL_USER,
				TARGET.CANCEL_BY = SOURCE.CANCEL_BY,
				TARGET.CANCEL_REASON = SOURCE.CANCEL_REASON,
				TARGET.PO_NBR = SOURCE.PO_NBR,
				TARGET.PRICE_LIST = SOURCE.PRICE_LIST,
				TARGET.PRICE_COLUMN = SOURCE.PRICE_COLUMN,
				TARGET.ARR_DATE = SOURCE.ARR_DATE,
				TARGET.ARR_TIME = SOURCE.ARR_TIME,
				TARGET.DEP_DATE = SOURCE.DEP_DATE,
				TARGET.DEP_TIME = SOURCE.DEP_TIME,
				TARGET.BLOCK_CDE = SOURCE.BLOCK_CDE,
				TARGET.PROP_CODE = SOURCE.PROP_CODE,
				TARGET.RM_TYPE = SOURCE.RM_TYPE,
				TARGET.RM_PRICE_CDE = SOURCE.RM_PRICE_CDE,
				TARGET.NBR_RMS = SOURCE.NBR_RMS,
				TARGET.COMP_DATE = SOURCE.COMP_DATE,
				TARGET.COMP_TIME = SOURCE.COMP_TIME,
				TARGET.COMP_USER = SOURCE.COMP_USER,
				TARGET.RES_FUNC_ID = SOURCE.RES_FUNC_ID,
				TARGET.RES_PHASE = SOURCE.RES_PHASE,
				TARGET.RES_SEQ = SOURCE.RES_SEQ,
				TARGET.NBR_PERS = SOURCE.NBR_PERS,
				TARGET.ACCT_ISSUE = SOURCE.ACCT_ISSUE,
				TARGET.BATCH = SOURCE.BATCH,
				TARGET.ORD_ACCT = SOURCE.ORD_ACCT,
				TARGET.ORD_CONTACT = SOURCE.ORD_CONTACT,
				TARGET.BILL_TO_CUST = SOURCE.BILL_TO_CUST,
				TARGET.BILL_TO_CONT = SOURCE.BILL_TO_CONT,
				TARGET.ORD_TOT = SOURCE.ORD_TOT,
				TARGET.ORD_TAX = SOURCE.ORD_TAX,
				TARGET.ORD_DUE = SOURCE.ORD_DUE,
				TARGET.ACT_TOTAL = SOURCE.ACT_TOTAL,
				TARGET.ACT_TAX = SOURCE.ACT_TAX,
				TARGET.ACT_DUE = SOURCE.ACT_DUE,
				TARGET.ACT_PAYMENTS = SOURCE.ACT_PAYMENTS,
				TARGET.ACT_CREDITS = SOURCE.ACT_CREDITS,
				TARGET.ORD_CREDITS = SOURCE.ORD_CREDITS,
				TARGET.COMMENT = SOURCE.COMMENT,
				TARGET.ACT_INACT = SOURCE.ACT_INACT,
				TARGET.PRT_FLAG = SOURCE.PRT_FLAG,
				TARGET.AMT_DUE_IND = SOURCE.AMT_DUE_IND,
				TARGET.SETUP_ID = SOURCE.SETUP_ID,
				TARGET.BOOTH_NBR = SOURCE.BOOTH_NBR,
				TARGET.ORD_DESC = SOURCE.ORD_DESC,
				TARGET.ORD_SPACE = SOURCE.ORD_SPACE,
				TARGET.ORD_STS_1 = SOURCE.ORD_STS_1,
				TARGET.ORD_STS_2 = SOURCE.ORD_STS_2,
				TARGET.INTERNAL = SOURCE.INTERNAL,
				TARGET.ENT_DATE_ISO = SOURCE.ENT_DATE_ISO,
				TARGET.ENT_USER_ID = SOURCE.ENT_USER_ID,
				TARGET.UPD_DATE_ISO = SOURCE.UPD_DATE_ISO,
				TARGET.UPD_USER_ID = SOURCE.UPD_USER_ID,
				TARGET.DEL_MARK = SOURCE.DEL_MARK,
				TARGET.XTRA_ACCT = SOURCE.XTRA_ACCT,
				TARGET.USER_8X = SOURCE.USER_8X,
				TARGET.USER_10X = SOURCE.USER_10X,
				TARGET.USER_DATE = SOURCE.USER_DATE,
				TARGET.ORDER_DESIG = SOURCE.ORDER_DESIG,
				TARGET.ORDER_TERMS = SOURCE.ORDER_TERMS,
				TARGET.SHIP_METHOD = SOURCE.SHIP_METHOD,
				TARGET.USER_6X = SOURCE.USER_6X,
				TARGET.USER_8X2 = SOURCE.USER_8X2,
				TARGET.USER_10X2 = SOURCE.USER_10X2,
				TARGET.SO_PRT = SOURCE.SO_PRT,
				TARGET.PARENT_FUNC = SOURCE.PARENT_FUNC,
				TARGET.REQ_CUST = SOURCE.REQ_CUST,
				TARGET.SO_USER_SEQ = SOURCE.SO_USER_SEQ,
				TARGET.SO_FUNC_SEQ = SOURCE.SO_FUNC_SEQ,
				TARGET.SHIP_DOC_ID = SOURCE.SHIP_DOC_ID,
				TARGET.SETUP_QTY = SOURCE.SETUP_QTY,
				TARGET.SO_ACT_INACT = SOURCE.SO_ACT_INACT,
				TARGET.SHORT_NOTE = SOURCE.SHORT_NOTE,
				TARGET.SO_STATUS = SOURCE.SO_STATUS,
				TARGET.USER_8X1 = SOURCE.USER_8X1,
				TARGET.USER_8X3 = SOURCE.USER_8X3,
				TARGET.CONF_ALL_REGIS = SOURCE.CONF_ALL_REGIS,
				TARGET.REQ_CONTACT = SOURCE.REQ_CONTACT,
				TARGET.BILL_CYCLE = SOURCE.BILL_CYCLE,
				TARGET.DUES_CYCLE = SOURCE.DUES_CYCLE,
				TARGET.RENEWAL_DATE = SOURCE.RENEWAL_DATE,
				TARGET.CYCLE_DATE = SOURCE.CYCLE_DATE,
				TARGET.BKG_ORDER = SOURCE.BKG_ORDER,
				TARGET.TRANS_SOURCE = SOURCE.TRANS_SOURCE,
				TARGET.INVOICE = SOURCE.INVOICE,
				TARGET.ORD_SIGN = SOURCE.ORD_SIGN,
				TARGET.ORD_DAYS = SOURCE.ORD_DAYS,
				TARGET.TEMPLATE = SOURCE.TEMPLATE,
				TARGET.WO_CLOSED = SOURCE.WO_CLOSED,
				TARGET.WO_DUE_DATE = SOURCE.WO_DUE_DATE,
				TARGET.WO_RUSH = SOURCE.WO_RUSH,
				TARGET.CURRENCY = SOURCE.CURRENCY,
				TARGET.FC_ORD_TOT = SOURCE.FC_ORD_TOT,
				TARGET.FC_ORD_TAX = SOURCE.FC_ORD_TAX,
				TARGET.FC_ORD_DUE = SOURCE.FC_ORD_DUE,
				TARGET.FC_ACT_TOT = SOURCE.FC_ACT_TOT,
				TARGET.FC_ACT_DUE = SOURCE.FC_ACT_DUE,
				TARGET.FC_ACT_PAYMENTS = SOURCE.FC_ACT_PAYMENTS,
				TARGET.FC_ACT_CREDITS = SOURCE.FC_ACT_CREDITS,
				TARGET.FC_ORD_CREDITS = SOURCE.FC_ORD_CREDITS,
				TARGET.FC_ACT_TAX = SOURCE.FC_ACT_TAX,
				TARGET.WO_TIME_OFFSET = SOURCE.WO_TIME_OFFSET,
				TARGET.WO_SIGN = SOURCE.WO_SIGN,
				TARGET.WO_DAYS = SOURCE.WO_DAYS,
				TARGET.WO_END_STAMP = SOURCE.WO_END_STAMP,
				TARGET.PL_CURRENCY = SOURCE.PL_CURRENCY,
				TARGET.TR_CURRENCY = SOURCE.TR_CURRENCY,
				TARGET.TRLC_RATE = SOURCE.TRLC_RATE,
				TARGET.TRFC_RATE = SOURCE.TRFC_RATE,
				TARGET.TRPL_RATE = SOURCE.TRPL_RATE,
				TARGET.TAXABLE = SOURCE.TAXABLE,
				TARGET.TR_ORD_TOT = SOURCE.TR_ORD_TOT,
				TARGET.TR_ORD_TAX = SOURCE.TR_ORD_TAX,
				TARGET.TR_ORD_CREDITS = SOURCE.TR_ORD_CREDITS,
				TARGET.TR_ORD_DUE = SOURCE.TR_ORD_DUE,
				TARGET.TR_ACT_TOT = SOURCE.TR_ACT_TOT,
				TARGET.TR_ACT_TAX = SOURCE.TR_ACT_TAX,
				TARGET.TR_ACT_CREDITS = SOURCE.TR_ACT_CREDITS,
				TARGET.TR_ACT_DUE = SOURCE.TR_ACT_DUE,
				TARGET.TR_ACT_PAYMENTS = SOURCE.TR_ACT_PAYMENTS,
				TARGET.PL_ORD_TOT = SOURCE.PL_ORD_TOT,
				TARGET.PL_ORD_TAX = SOURCE.PL_ORD_TAX,
				TARGET.PL_ORD_CREDITS = SOURCE.PL_ORD_CREDITS,
				TARGET.PL_ORD_DUE = SOURCE.PL_ORD_DUE,
				TARGET.PL_ACT_TOT = SOURCE.PL_ACT_TOT,
				TARGET.PL_ACT_TAX = SOURCE.PL_ACT_TAX,
				TARGET.PL_ACT_CREDITS = SOURCE.PL_ACT_CREDITS,
				TARGET.PL_ACT_DUE = SOURCE.PL_ACT_DUE,
				TARGET.PL_ACT_PAYMENTS = SOURCE.PL_ACT_PAYMENTS,
				TARGET.ASSIGNMENT_NAME = SOURCE.ASSIGNMENT_NAME,
				TARGET.PAY_PLAN_ID = SOURCE.PAY_PLAN_ID,
				TARGET.PP_SCHED_CODE = SOURCE.PP_SCHED_CODE,
				TARGET.NEW_STS = SOURCE.NEW_STS,
				TARGET.REPRINT = SOURCE.REPRINT,
				TARGET.CONFIG_CODE = SOURCE.CONFIG_CODE,
				TARGET.NG_ORD_CONTACT = SOURCE.NG_ORD_CONTACT,
				TARGET.NG_BTO_CONTACT = SOURCE.NG_BTO_CONTACT,
				TARGET.NG_REQ_CONTACT = SOURCE.NG_REQ_CONTACT,
				TARGET.ORD_ACCT_REP = SOURCE.ORD_ACCT_REP,
				TARGET.ASGN_TOT_SIZE = SOURCE.ASGN_TOT_SIZE,
				TARGET.ASGN_OPEN_SIDES = SOURCE.ASGN_OPEN_SIDES,
				TARGET.ASGN_LENGTH = SOURCE.ASGN_LENGTH,
				TARGET.ASGN_WIDTH = SOURCE.ASGN_WIDTH,
				TARGET.PROMO_CODE = SOURCE.PROMO_CODE,
				TARGET.TAX_DETAIL = SOURCE.TAX_DETAIL,
				TARGET.ALL_PRT = SOURCE.ALL_PRT,
				TARGET.MULTI_ORG_ACCT = SOURCE.MULTI_ORG_ACCT,
				TARGET.ALT_ASSIGN_NAME_1 = SOURCE.ALT_ASSIGN_NAME_1,
				TARGET.ALT_ASSIGN_NAME_2 = SOURCE.ALT_ASSIGN_NAME_2,
				TARGET.USER_REFERENCE = SOURCE.USER_REFERENCE,
				TARGET.ORD_COST_TOTAL = SOURCE.ORD_COST_TOTAL,
				TARGET.ACT_COST_TOTAL = SOURCE.ACT_COST_TOTAL,
				TARGET.REF_INV_NBR = SOURCE.REF_INV_NBR,
				TARGET.SHIPTO_ACCT = SOURCE.SHIPTO_ACCT,
				TARGET.SHIPTO_CONT = SOURCE.SHIPTO_CONT,
				TARGET.ALT_ASSIGN_NAME_3 = SOURCE.ALT_ASSIGN_NAME_3,
				TARGET.ALT_ASSIGN_NAME_4 = SOURCE.ALT_ASSIGN_NAME_4,
				TARGET.ALT_ASSIGN_NAME_5 = SOURCE.ALT_ASSIGN_NAME_5,
				TARGET.ASGN_TOT_DISP_SIZE = SOURCE.ASGN_TOT_DISP_SIZE,
				TARGET.CONTRACT_SEQ = SOURCE.CONTRACT_SEQ,
				TARGET.ORD_GLACCT = SOURCE.ORD_GLACCT,
				TARGET.NEAR_EXHIB = SOURCE.NEAR_EXHIB,
				TARGET.AWAY_EXHIB = SOURCE.AWAY_EXHIB,
				TARGET.COMPETITORS = SOURCE.COMPETITORS,
				TARGET.PREF_ASSIGN = SOURCE.PREF_ASSIGN,
				TARGET.EXHIB_POINTS = SOURCE.EXHIB_POINTS,
				TARGET.EXHIB_MI = SOURCE.EXHIB_MI,
				TARGET.PAVILION = SOURCE.PAVILION,
				TARGET.EXHIB_TXT_01 = SOURCE.EXHIB_TXT_01,
				TARGET.EXHIB_TXT_02 = SOURCE.EXHIB_TXT_02,
				TARGET.EXHIB_TXT_03 = SOURCE.EXHIB_TXT_03,
				TARGET.EXHIB_NBR_01 = SOURCE.EXHIB_NBR_01,
				TARGET.EXHIB_NBR_02 = SOURCE.EXHIB_NBR_02,
				TARGET.EXHIB_NBR_03 = SOURCE.EXHIB_NBR_03,
				TARGET.EXHIB_DTM_01 = SOURCE.EXHIB_DTM_01,
				TARGET.EXHIB_DTM_02 = SOURCE.EXHIB_DTM_02,
				TARGET.EXHIB_DTM_03 = SOURCE.EXHIB_DTM_03,
				TARGET.OCCURRENCE = SOURCE.OCCURRENCE,
				TARGET.ORD_FIXED = SOURCE.ORD_FIXED,
				TARGET.ORD_REV_TRANS = SOURCE.ORD_REV_TRANS,
				TARGET.COMM_ORDER = SOURCE.COMM_ORDER,
				TARGET.ORD_ADDR_SEQ = SOURCE.ORD_ADDR_SEQ,
				TARGET.BILLTO_ADDR_SEQ = SOURCE.BILLTO_ADDR_SEQ,
				TARGET.REQ_ADDR_SEQ = SOURCE.REQ_ADDR_SEQ,
				TARGET.SHIPTO_ADDR_SEQ = SOURCE.SHIPTO_ADDR_SEQ,
				TARGET.OCCURENCE = SOURCE.OCCURENCE,
				TARGET.MAIN_EXHIB_ORDER = SOURCE.MAIN_EXHIB_ORDER,
				TARGET.PRJ_ID = SOURCE.PRJ_ID,
				TARGET.ACCT_DESIG = SOURCE.ACCT_DESIG,
				TARGET.GEN = SOURCE.GEN,
				TARGET.TAX_DATE = SOURCE.TAX_DATE,
				TARGET.AR_CONTROL = SOURCE.AR_CONTROL,
				TARGET.EXHIBITOR_ID = SOURCE.EXHIBITOR_ID,
				TARGET.ENT_APP_TYPE = SOURCE.ENT_APP_TYPE,
				TARGET.CUST_PAY_INFO = SOURCE.CUST_PAY_INFO,
				TARGET.CUST_PAY_TYPE = SOURCE.CUST_PAY_TYPE,
				TARGET.DIVISION = SOURCE.DIVISION,
				TARGET.EXHIB_ORD_NBR = SOURCE.EXHIB_ORD_NBR,
				TARGET.BOOTH_ORDER = SOURCE.BOOTH_ORDER,
				TARGET.ORD_CAT_SEQ = SOURCE.ORD_CAT_SEQ

			WHEN NOT MATCHED BY TARGET THEN INSERT (

				ORG_CODE,
				ORD_NBR,
				SO_SEARCH,
				EVT_ID,
				ORD_TYPE,
				FUNC_ID,
				EVT_SEARCH,
				FUNC_SEARCH,
				ORD_FORM,
				ORD_DATE,
				ORD_STS,
				PRT_STS,
				MET_NOTIFY,
				CANCEL_DATE,
				CANCEL_USER,
				CANCEL_BY,
				CANCEL_REASON,
				PO_NBR,
				PRICE_LIST,
				PRICE_COLUMN,
				ARR_DATE,
				ARR_TIME,
				DEP_DATE,
				DEP_TIME,
				BLOCK_CDE,
				PROP_CODE,
				RM_TYPE,
				RM_PRICE_CDE,
				NBR_RMS,
				COMP_DATE,
				COMP_TIME,
				COMP_USER,
				RES_FUNC_ID,
				RES_PHASE,
				RES_SEQ,
				NBR_PERS,
				ACCT_ISSUE,
				BATCH,
				ORD_ACCT,
				ORD_CONTACT,
				BILL_TO_CUST,
				BILL_TO_CONT,
				ORD_TOT,
				ORD_TAX,
				ORD_DUE,
				ACT_TOTAL,
				ACT_TAX,
				ACT_DUE,
				ACT_PAYMENTS,
				ACT_CREDITS,
				ORD_CREDITS,
				COMMENT,
				ACT_INACT,
				PRT_FLAG,
				AMT_DUE_IND,
				SETUP_ID,
				BOOTH_NBR,
				ORD_DESC,
				ORD_SPACE,
				ORD_STS_1,
				ORD_STS_2,
				INTERNAL,
				ENT_DATE_ISO,
				ENT_USER_ID,
				UPD_DATE_ISO,
				UPD_USER_ID,
				DEL_MARK,
				XTRA_ACCT,
				USER_8X,
				USER_10X,
				USER_DATE,
				ORDER_DESIG,
				ORDER_TERMS,
				SHIP_METHOD,
				USER_6X,
				USER_8X2,
				USER_10X2,
				SO_PRT,
				PARENT_FUNC,
				REQ_CUST,
				SO_USER_SEQ,
				SO_FUNC_SEQ,
				SHIP_DOC_ID,
				SETUP_QTY,
				SO_ACT_INACT,
				SHORT_NOTE,
				SO_STATUS,
				USER_8X1,
				USER_8X3,
				CONF_ALL_REGIS,
				REQ_CONTACT,
				BILL_CYCLE,
				DUES_CYCLE,
				RENEWAL_DATE,
				CYCLE_DATE,
				BKG_ORDER,
				TRANS_SOURCE,
				INVOICE,
				ORD_SIGN,
				ORD_DAYS,
				TEMPLATE,
				WO_CLOSED,
				WO_DUE_DATE,
				WO_RUSH,
				CURRENCY,
				FC_ORD_TOT,
				FC_ORD_TAX,
				FC_ORD_DUE,
				FC_ACT_TOT,
				FC_ACT_DUE,
				FC_ACT_PAYMENTS,
				FC_ACT_CREDITS,
				FC_ORD_CREDITS,
				FC_ACT_TAX,
				WO_TIME_OFFSET,
				WO_SIGN,
				WO_DAYS,
				WO_END_STAMP,
				PL_CURRENCY,
				TR_CURRENCY,
				TRLC_RATE,
				TRFC_RATE,
				TRPL_RATE,
				TAXABLE,
				TR_ORD_TOT,
				TR_ORD_TAX,
				TR_ORD_CREDITS,
				TR_ORD_DUE,
				TR_ACT_TOT,
				TR_ACT_TAX,
				TR_ACT_CREDITS,
				TR_ACT_DUE,
				TR_ACT_PAYMENTS,
				PL_ORD_TOT,
				PL_ORD_TAX,
				PL_ORD_CREDITS,
				PL_ORD_DUE,
				PL_ACT_TOT,
				PL_ACT_TAX,
				PL_ACT_CREDITS,
				PL_ACT_DUE,
				PL_ACT_PAYMENTS,
				ASSIGNMENT_NAME,
				PAY_PLAN_ID,
				PP_SCHED_CODE,
				NEW_STS,
				REPRINT,
				CONFIG_CODE,
				NG_ORD_CONTACT,
				NG_BTO_CONTACT,
				NG_REQ_CONTACT,
				ORD_ACCT_REP,
				ASGN_TOT_SIZE,
				ASGN_OPEN_SIDES,
				ASGN_LENGTH,
				ASGN_WIDTH,
				PROMO_CODE,
				TAX_DETAIL,
				ALL_PRT,
				MULTI_ORG_ACCT,
				ALT_ASSIGN_NAME_1,
				ALT_ASSIGN_NAME_2,
				USER_REFERENCE,
				ORD_COST_TOTAL,
				ACT_COST_TOTAL,
				REF_INV_NBR,
				SHIPTO_ACCT,
				SHIPTO_CONT,
				ALT_ASSIGN_NAME_3,
				ALT_ASSIGN_NAME_4,
				ALT_ASSIGN_NAME_5,
				ASGN_TOT_DISP_SIZE,
				CONTRACT_SEQ,
				ORD_GLACCT,
				NEAR_EXHIB,
				AWAY_EXHIB,
				COMPETITORS,
				PREF_ASSIGN,
				EXHIB_POINTS,
				EXHIB_MI,
				PAVILION,
				EXHIB_TXT_01,
				EXHIB_TXT_02,
				EXHIB_TXT_03,
				EXHIB_NBR_01,
				EXHIB_NBR_02,
				EXHIB_NBR_03,
				EXHIB_DTM_01,
				EXHIB_DTM_02,
				EXHIB_DTM_03,
				OCCURRENCE,
				ORD_FIXED,
				ORD_REV_TRANS,
				COMM_ORDER,
				ORD_ADDR_SEQ,
				BILLTO_ADDR_SEQ,
				REQ_ADDR_SEQ,
				SHIPTO_ADDR_SEQ,
				OCCURENCE,
				MAIN_EXHIB_ORDER,
				PRJ_ID,
				ACCT_DESIG,
				GEN,
				TAX_DATE,
				AR_CONTROL,
				EXHIBITOR_ID,
				ENT_APP_TYPE,
				CUST_PAY_INFO,
				CUST_PAY_TYPE,
				DIVISION,
				EXHIB_ORD_NBR,
				BOOTH_ORDER,
				ORD_CAT_SEQ )

			VALUES (

				SOURCE.ORG_CODE,
				SOURCE.ORD_NBR,
				SOURCE.SO_SEARCH,
				SOURCE.EVT_ID,
				SOURCE.ORD_TYPE,
				SOURCE.FUNC_ID,
				SOURCE.EVT_SEARCH,
				SOURCE.FUNC_SEARCH,
				SOURCE.ORD_FORM,
				SOURCE.ORD_DATE,
				SOURCE.ORD_STS,
				SOURCE.PRT_STS,
				SOURCE.MET_NOTIFY,
				SOURCE.CANCEL_DATE,
				SOURCE.CANCEL_USER,
				SOURCE.CANCEL_BY,
				SOURCE.CANCEL_REASON,
				SOURCE.PO_NBR,
				SOURCE.PRICE_LIST,
				SOURCE.PRICE_COLUMN,
				SOURCE.ARR_DATE,
				SOURCE.ARR_TIME,
				SOURCE.DEP_DATE,
				SOURCE.DEP_TIME,
				SOURCE.BLOCK_CDE,
				SOURCE.PROP_CODE,
				SOURCE.RM_TYPE,
				SOURCE.RM_PRICE_CDE,
				SOURCE.NBR_RMS,
				SOURCE.COMP_DATE,
				SOURCE.COMP_TIME,
				SOURCE.COMP_USER,
				SOURCE.RES_FUNC_ID,
				SOURCE.RES_PHASE,
				SOURCE.RES_SEQ,
				SOURCE.NBR_PERS,
				SOURCE.ACCT_ISSUE,
				SOURCE.BATCH,
				SOURCE.ORD_ACCT,
				SOURCE.ORD_CONTACT,
				SOURCE.BILL_TO_CUST,
				SOURCE.BILL_TO_CONT,
				SOURCE.ORD_TOT,
				SOURCE.ORD_TAX,
				SOURCE.ORD_DUE,
				SOURCE.ACT_TOTAL,
				SOURCE.ACT_TAX,
				SOURCE.ACT_DUE,
				SOURCE.ACT_PAYMENTS,
				SOURCE.ACT_CREDITS,
				SOURCE.ORD_CREDITS,
				SOURCE.COMMENT,
				SOURCE.ACT_INACT,
				SOURCE.PRT_FLAG,
				SOURCE.AMT_DUE_IND,
				SOURCE.SETUP_ID,
				SOURCE.BOOTH_NBR,
				SOURCE.ORD_DESC,
				SOURCE.ORD_SPACE,
				SOURCE.ORD_STS_1,
				SOURCE.ORD_STS_2,
				SOURCE.INTERNAL,
				SOURCE.ENT_DATE_ISO,
				SOURCE.ENT_USER_ID,
				SOURCE.UPD_DATE_ISO,
				SOURCE.UPD_USER_ID,
				SOURCE.DEL_MARK,
				SOURCE.XTRA_ACCT,
				SOURCE.USER_8X,
				SOURCE.USER_10X,
				SOURCE.USER_DATE,
				SOURCE.ORDER_DESIG,
				SOURCE.ORDER_TERMS,
				SOURCE.SHIP_METHOD,
				SOURCE.USER_6X,
				SOURCE.USER_8X2,
				SOURCE.USER_10X2,
				SOURCE.SO_PRT,
				SOURCE.PARENT_FUNC,
				SOURCE.REQ_CUST,
				SOURCE.SO_USER_SEQ,
				SOURCE.SO_FUNC_SEQ,
				SOURCE.SHIP_DOC_ID,
				SOURCE.SETUP_QTY,
				SOURCE.SO_ACT_INACT,
				SOURCE.SHORT_NOTE,
				SOURCE.SO_STATUS,
				SOURCE.USER_8X1,
				SOURCE.USER_8X3,
				SOURCE.CONF_ALL_REGIS,
				SOURCE.REQ_CONTACT,
				SOURCE.BILL_CYCLE,
				SOURCE.DUES_CYCLE,
				SOURCE.RENEWAL_DATE,
				SOURCE.CYCLE_DATE,
				SOURCE.BKG_ORDER,
				SOURCE.TRANS_SOURCE,
				SOURCE.INVOICE,
				SOURCE.ORD_SIGN,
				SOURCE.ORD_DAYS,
				SOURCE.TEMPLATE,
				SOURCE.WO_CLOSED,
				SOURCE.WO_DUE_DATE,
				SOURCE.WO_RUSH,
				SOURCE.CURRENCY,
				SOURCE.FC_ORD_TOT,
				SOURCE.FC_ORD_TAX,
				SOURCE.FC_ORD_DUE,
				SOURCE.FC_ACT_TOT,
				SOURCE.FC_ACT_DUE,
				SOURCE.FC_ACT_PAYMENTS,
				SOURCE.FC_ACT_CREDITS,
				SOURCE.FC_ORD_CREDITS,
				SOURCE.FC_ACT_TAX,
				SOURCE.WO_TIME_OFFSET,
				SOURCE.WO_SIGN,
				SOURCE.WO_DAYS,
				SOURCE.WO_END_STAMP,
				SOURCE.PL_CURRENCY,
				SOURCE.TR_CURRENCY,
				SOURCE.TRLC_RATE,
				SOURCE.TRFC_RATE,
				SOURCE.TRPL_RATE,
				SOURCE.TAXABLE,
				SOURCE.TR_ORD_TOT,
				SOURCE.TR_ORD_TAX,
				SOURCE.TR_ORD_CREDITS,
				SOURCE.TR_ORD_DUE,
				SOURCE.TR_ACT_TOT,
				SOURCE.TR_ACT_TAX,
				SOURCE.TR_ACT_CREDITS,
				SOURCE.TR_ACT_DUE,
				SOURCE.TR_ACT_PAYMENTS,
				SOURCE.PL_ORD_TOT,
				SOURCE.PL_ORD_TAX,
				SOURCE.PL_ORD_CREDITS,
				SOURCE.PL_ORD_DUE,
				SOURCE.PL_ACT_TOT,
				SOURCE.PL_ACT_TAX,
				SOURCE.PL_ACT_CREDITS,
				SOURCE.PL_ACT_DUE,
				SOURCE.PL_ACT_PAYMENTS,
				SOURCE.ASSIGNMENT_NAME,
				SOURCE.PAY_PLAN_ID,
				SOURCE.PP_SCHED_CODE,
				SOURCE.NEW_STS,
				SOURCE.REPRINT,
				SOURCE.CONFIG_CODE,
				SOURCE.NG_ORD_CONTACT,
				SOURCE.NG_BTO_CONTACT,
				SOURCE.NG_REQ_CONTACT,
				SOURCE.ORD_ACCT_REP,
				SOURCE.ASGN_TOT_SIZE,
				SOURCE.ASGN_OPEN_SIDES,
				SOURCE.ASGN_LENGTH,
				SOURCE.ASGN_WIDTH,
				SOURCE.PROMO_CODE,
				SOURCE.TAX_DETAIL,
				SOURCE.ALL_PRT,
				SOURCE.MULTI_ORG_ACCT,
				SOURCE.ALT_ASSIGN_NAME_1,
				SOURCE.ALT_ASSIGN_NAME_2,
				SOURCE.USER_REFERENCE,
				SOURCE.ORD_COST_TOTAL,
				SOURCE.ACT_COST_TOTAL,
				SOURCE.REF_INV_NBR,
				SOURCE.SHIPTO_ACCT,
				SOURCE.SHIPTO_CONT,
				SOURCE.ALT_ASSIGN_NAME_3,
				SOURCE.ALT_ASSIGN_NAME_4,
				SOURCE.ALT_ASSIGN_NAME_5,
				SOURCE.ASGN_TOT_DISP_SIZE,
				SOURCE.CONTRACT_SEQ,
				SOURCE.ORD_GLACCT,
				SOURCE.NEAR_EXHIB,
				SOURCE.AWAY_EXHIB,
				SOURCE.COMPETITORS,
				SOURCE.PREF_ASSIGN,
				SOURCE.EXHIB_POINTS,
				SOURCE.EXHIB_MI,
				SOURCE.PAVILION,
				SOURCE.EXHIB_TXT_01,
				SOURCE.EXHIB_TXT_02,
				SOURCE.EXHIB_TXT_03,
				SOURCE.EXHIB_NBR_01,
				SOURCE.EXHIB_NBR_02,
				SOURCE.EXHIB_NBR_03,
				SOURCE.EXHIB_DTM_01,
				SOURCE.EXHIB_DTM_02,
				SOURCE.EXHIB_DTM_03,
				SOURCE.OCCURRENCE,
				SOURCE.ORD_FIXED,
				SOURCE.ORD_REV_TRANS,
				SOURCE.COMM_ORDER,
				SOURCE.ORD_ADDR_SEQ,
				SOURCE.BILLTO_ADDR_SEQ,
				SOURCE.REQ_ADDR_SEQ,
				SOURCE.SHIPTO_ADDR_SEQ,
				SOURCE.OCCURENCE,
				SOURCE.MAIN_EXHIB_ORDER,
				SOURCE.PRJ_ID,
				SOURCE.ACCT_DESIG,
				SOURCE.GEN,
				SOURCE.TAX_DATE,
				SOURCE.AR_CONTROL,
				SOURCE.EXHIBITOR_ID,
				SOURCE.ENT_APP_TYPE,
				SOURCE.CUST_PAY_INFO,
				SOURCE.CUST_PAY_TYPE,
				SOURCE.DIVISION,
				SOURCE.EXHIB_ORD_NBR,
				SOURCE.BOOTH_ORDER,
				SOURCE.ORD_CAT_SEQ )
			
			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);
		
		COMMIT TRANSACTION;

	END TRY
	
	BEGIN CATCH

		ROLLBACK TRANSACTION;
		
		THROW;

	END CATCH;

END;