CREATE PROCEDURE CSP_SYNC_TRANS_TYPES

      @TableParam TVP_TRANS_TYPES READONLY

AS
BEGIN

	BEGIN TRY
		
		BEGIN TRANSACTION

			MERGE TRANS_TYPES WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON 
			
				TARGET.TSM      = SOURCE.TSM AND 
				TARGET.ORG_CODE = SOURCE.ORG_CODE
		
			WHEN MATCHED AND (
		
				TARGET.TRANS_TYPE            != SOURCE.TRANS_TYPE OR
				TARGET.TRANS_SOURCE          != SOURCE.TRANS_SOURCE OR
				TARGET.TRANS_METHOD          != SOURCE.TRANS_METHOD OR
				TARGET.TRANS_DESC            != SOURCE.TRANS_DESC OR
				TARGET.STATUS                != SOURCE.STATUS OR
				TARGET.MEMO_TYPE             != SOURCE.MEMO_TYPE OR
				TARGET.REF_REQ               != SOURCE.REF_REQ OR
				TARGET.EXPIR_REQ             != SOURCE.EXPIR_REQ OR
				TARGET.CONTROL_REQ           != SOURCE.CONTROL_REQ OR
				TARGET.CC_NBR_REQ            != SOURCE.CC_NBR_REQ OR
				TARGET.CC_ID_REQ             != SOURCE.CC_ID_REQ OR
				TARGET.TRANS_CLASS           != SOURCE.TRANS_CLASS OR
				TARGET.TRANS_IND             != SOURCE.TRANS_IND OR
				TARGET.REV_DEPOSIT           != SOURCE.REV_DEPOSIT OR
				TARGET.REV_TYPE              != SOURCE.REV_TYPE OR
				TARGET.CURRENCY              != SOURCE.CURRENCY OR
				TARGET.TRANSFER              != SOURCE.TRANSFER OR
				TARGET.GROUP                 != SOURCE.GROUP OR
				TARGET.ACCRUE                != SOURCE.ACCRUE OR
				TARGET.LATE_CHARGE           != SOURCE.LATE_CHARGE OR
				TARGET.CC_FIRST_NUM          != SOURCE.CC_FIRST_NUM OR
				TARGET.CC_MERCH_ID           != SOURCE.CC_MERCH_ID OR
				TARGET.CC_AUTH_USER          != SOURCE.CC_AUTH_USER OR
				TARGET.CC_AUTH_PWD           != SOURCE.CC_AUTH_PWD OR
				TARGET.ENT_STAMP             != SOURCE.ENT_STAMP OR
				TARGET.ENT_USER_ID           != SOURCE.ENT_USER_ID OR
				TARGET.UPD_STAMP             != SOURCE.UPD_STAMP OR
				TARGET.UPD_USER_ID           != SOURCE.UPD_USER_ID OR
				TARGET.ALLOW_FINAL_INV       != SOURCE.ALLOW_FINAL_INV OR
				TARGET.REFUND                != SOURCE.REFUND OR
				TARGET.ALT_TRANS_DESC_1      != SOURCE.ALT_TRANS_DESC_1 OR
				TARGET.ALT_TRANS_DESC_2      != SOURCE.ALT_TRANS_DESC_2 OR
				TARGET.ALT_TRANS_DESC_3      != SOURCE.ALT_TRANS_DESC_3 OR
				TARGET.ALT_TRANS_DESC_4      != SOURCE.ALT_TRANS_DESC_4 OR
				TARGET.ALT_TRANS_DESC_5      != SOURCE.ALT_TRANS_DESC_5 OR
				TARGET.SOURCE_DEFAULT        != SOURCE.SOURCE_DEFAULT OR
				TARGET.AUTO_AUTHORIZE        != SOURCE.AUTO_AUTHORIZE OR
				TARGET.CB_TRANS              != SOURCE.CB_TRANS OR
				TARGET.USER_REF_REQ          != SOURCE.USER_REF_REQ OR
				TARGET.CC_ID_HIDE            != SOURCE.CC_ID_HIDE OR
				TARGET.CC_NBR_HIDE           != SOURCE.CC_NBR_HIDE OR
				TARGET.CONTROL_HIDE          != SOURCE.CONTROL_HIDE OR
				TARGET.EXPIR_HIDE            != SOURCE.EXPIR_HIDE OR
				TARGET.REF_HIDE              != SOURCE.REF_HIDE OR
				TARGET.USER_REF_HIDE         != SOURCE.USER_REF_HIDE OR
				TARGET.GL_HIDE               != SOURCE.GL_HIDE OR
				TARGET.PAYOR_INFO_HIDE       != SOURCE.PAYOR_INFO_HIDE OR
				TARGET.FEE_TSM               != SOURCE.FEE_TSM OR
				TARGET.FEE_PCT               != SOURCE.FEE_PCT OR
				TARGET.FEE_RES_TYPE          != SOURCE.FEE_RES_TYPE OR
				TARGET.FEE_RES_CODE          != SOURCE.FEE_RES_CODE OR
				TARGET.FEE_PCT_AMT           != SOURCE.FEE_PCT_AMT OR
				TARGET.FEE_BASIS             != SOURCE.FEE_BASIS OR
				TARGET.CC_AUTH_SPECS_SEQ_NBR != SOURCE.CC_AUTH_SPECS_SEQ_NBR )

			THEN UPDATE SET 

				TRANS_TYPE            = SOURCE.TRANS_TYPE,
				TRANS_SOURCE          = SOURCE.TRANS_SOURCE,
				TRANS_METHOD          = SOURCE.TRANS_METHOD,
				TRANS_DESC            = SOURCE.TRANS_DESC,
				STATUS                = SOURCE.STATUS,
				MEMO_TYPE             = SOURCE.MEMO_TYPE,
				REF_REQ               = SOURCE.REF_REQ,
				EXPIR_REQ             = SOURCE.EXPIR_REQ,
				CONTROL_REQ           = SOURCE.CONTROL_REQ,
				CC_NBR_REQ            = SOURCE.CC_NBR_REQ,
				CC_ID_REQ             = SOURCE.CC_ID_REQ,
				TRANS_CLASS           = SOURCE.TRANS_CLASS,
				TRANS_IND             = SOURCE.TRANS_IND,
				REV_DEPOSIT           = SOURCE.REV_DEPOSIT,
				REV_TYPE              = SOURCE.REV_TYPE,
				CURRENCY              = SOURCE.CURRENCY,
				TRANSFER              = SOURCE.TRANSFER,
				GROUP                 = SOURCE.GROUP,
				ACCRUE                = SOURCE.ACCRUE,
				LATE_CHARGE           = SOURCE.LATE_CHARGE,
				CC_FIRST_NUM          = SOURCE.CC_FIRST_NUM,
				CC_MERCH_ID           = SOURCE.CC_MERCH_ID,
				CC_AUTH_USER          = SOURCE.CC_AUTH_USER,
				CC_AUTH_PWD           = SOURCE.CC_AUTH_PWD,
				ENT_STAMP             = SOURCE.ENT_STAMP,
				ENT_USER_ID           = SOURCE.ENT_USER_ID,
				UPD_STAMP             = SOURCE.UPD_STAMP,
				UPD_USER_ID           = SOURCE.UPD_USER_ID,
				ALLOW_FINAL_INV       = SOURCE.ALLOW_FINAL_INV,
				REFUND                = SOURCE.REFUND,
				ALT_TRANS_DESC_1      = SOURCE.ALT_TRANS_DESC_1,
				ALT_TRANS_DESC_2      = SOURCE.ALT_TRANS_DESC_2,
				ALT_TRANS_DESC_3      = SOURCE.ALT_TRANS_DESC_3,
				ALT_TRANS_DESC_4      = SOURCE.ALT_TRANS_DESC_4,
				ALT_TRANS_DESC_5      = SOURCE.ALT_TRANS_DESC_5,
				SOURCE_DEFAULT        = SOURCE.SOURCE_DEFAULT,
				AUTO_AUTHORIZE        = SOURCE.AUTO_AUTHORIZE,
				CB_TRANS              = SOURCE.CB_TRANS,
				USER_REF_REQ          = SOURCE.USER_REF_REQ,
				CC_ID_HIDE            = SOURCE.CC_ID_HIDE,
				CC_NBR_HIDE           = SOURCE.CC_NBR_HIDE,
				CONTROL_HIDE          = SOURCE.CONTROL_HIDE,
				EXPIR_HIDE            = SOURCE.EXPIR_HIDE,
				REF_HIDE              = SOURCE.REF_HIDE,
				USER_REF_HIDE         = SOURCE.USER_REF_HIDE,
				GL_HIDE               = SOURCE.GL_HIDE,
				PAYOR_INFO_HIDE       = SOURCE.PAYOR_INFO_HIDE,
				FEE_TSM               = SOURCE.FEE_TSM,
				FEE_PCT               = SOURCE.FEE_PCT,
				FEE_RES_TYPE          = SOURCE.FEE_RES_TYPE,
				FEE_RES_CODE          = SOURCE.FEE_RES_CODE,
				FEE_PCT_AMT           = SOURCE.FEE_PCT_AMT,
				FEE_BASIS             = SOURCE.FEE_BASIS,
				CC_AUTH_SPECS_SEQ_NBR = SOURCE.CC_AUTH_SPECS_SEQ_NBR

			WHEN NOT MATCHED BY TARGET THEN INSERT (

				TSM,
				ORG_CODE,
				TRANS_TYPE,
				TRANS_SOURCE,
				TRANS_METHOD,
				TRANS_DESC,
				STATUS,
				MEMO_TYPE,
				REF_REQ,
				EXPIR_REQ,
				CONTROL_REQ,
				CC_NBR_REQ,
				CC_ID_REQ,
				TRANS_CLASS,
				TRANS_IND,
				REV_DEPOSIT,
				REV_TYPE,
				CURRENCY,
				TRANSFER,
				GROUP,
				ACCRUE,
				LATE_CHARGE,
				CC_FIRST_NUM,
				CC_MERCH_ID,
				CC_AUTH_USER,
				CC_AUTH_PWD,
				ENT_STAMP,
				ENT_USER_ID,
				UPD_STAMP,
				UPD_USER_ID,
				ALLOW_FINAL_INV,
				REFUND,
				ALT_TRANS_DESC_1,
				ALT_TRANS_DESC_2,
				ALT_TRANS_DESC_3,
				ALT_TRANS_DESC_4,
				ALT_TRANS_DESC_5,
				SOURCE_DEFAULT,
				AUTO_AUTHORIZE,
				CB_TRANS,
				USER_REF_REQ,
				CC_ID_HIDE,
				CC_NBR_HIDE,
				CONTROL_HIDE,
				EXPIR_HIDE,
				REF_HIDE,
				USER_REF_HIDE,
				GL_HIDE,
				PAYOR_INFO_HIDE,
				FEE_TSM,
				FEE_PCT,
				FEE_RES_TYPE,
				FEE_RES_CODE,
				FEE_PCT_AMT,
				FEE_BASIS,
				CC_AUTH_SPECS_SEQ_NBR )

			VALUES (

				SOURCE.TSM,
				SOURCE.ORG_CODE,
				SOURCE.TRANS_TYPE,
				SOURCE.TRANS_SOURCE,
				SOURCE.TRANS_METHOD,
				SOURCE.TRANS_DESC,
				SOURCE.STATUS,
				SOURCE.MEMO_TYPE,
				SOURCE.REF_REQ,
				SOURCE.EXPIR_REQ,
				SOURCE.CONTROL_REQ,
				SOURCE.CC_NBR_REQ,
				SOURCE.CC_ID_REQ,
				SOURCE.TRANS_CLASS,
				SOURCE.TRANS_IND,
				SOURCE.REV_DEPOSIT,
				SOURCE.REV_TYPE,
				SOURCE.CURRENCY,
				SOURCE.TRANSFER,
				SOURCE.GROUP,
				SOURCE.ACCRUE,
				SOURCE.LATE_CHARGE,
				SOURCE.CC_FIRST_NUM,
				SOURCE.CC_MERCH_ID,
				SOURCE.CC_AUTH_USER,
				SOURCE.CC_AUTH_PWD,
				SOURCE.ENT_STAMP,
				SOURCE.ENT_USER_ID,
				SOURCE.UPD_STAMP,
				SOURCE.UPD_USER_ID,
				SOURCE.ALLOW_FINAL_INV,
				SOURCE.REFUND,
				SOURCE.ALT_TRANS_DESC_1,
				SOURCE.ALT_TRANS_DESC_2,
				SOURCE.ALT_TRANS_DESC_3,
				SOURCE.ALT_TRANS_DESC_4,
				SOURCE.ALT_TRANS_DESC_5,
				SOURCE.SOURCE_DEFAULT,
				SOURCE.AUTO_AUTHORIZE,
				SOURCE.CB_TRANS,
				SOURCE.USER_REF_REQ,
				SOURCE.CC_ID_HIDE,
				SOURCE.CC_NBR_HIDE,
				SOURCE.CONTROL_HIDE,
				SOURCE.EXPIR_HIDE,
				SOURCE.REF_HIDE,
				SOURCE.USER_REF_HIDE,
				SOURCE.GL_HIDE,
				SOURCE.PAYOR_INFO_HIDE,
				SOURCE.FEE_TSM,
				SOURCE.FEE_PCT,
				SOURCE.FEE_RES_TYPE,
				SOURCE.FEE_RES_CODE,
				SOURCE.FEE_PCT_AMT,
				SOURCE.FEE_BASIS,
				SOURCE.CC_AUTH_SPECS_SEQ_NBR )
			
			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);
		
		COMMIT TRANSACTION;

	END TRY
	
	BEGIN CATCH

		ROLLBACK TRANSACTION;
		
		THROW;

	END CATCH;

END;