CREATE PROCEDURE CSP_SYNC_EVENT_MASTER

      @TableParam TVP_EVENT_MASTER READONLY

AS
BEGIN

	BEGIN TRY

		BEGIN TRANSACTION

			MERGE EVENT_MASTER WITH (TABLOCK) AS TARGET USING @TableParam AS SOURCE ON

				TARGET.ORG_CODE = SOURCE.ORG_CODE AND
				TARGET.EVT_ID = SOURCE.EVT_ID

			WHEN MATCHED AND (

				TARGET.EVT_SEARCH != SOURCE.EVT_SEARCH OR
				TARGET.EVT_DESC != SOURCE.EVT_DESC OR
				TARGET.EVT_DESIGNATION != SOURCE.EVT_DESIGNATION OR
				TARGET.CONFIDENTIAL != SOURCE.CONFIDENTIAL OR
				TARGET.START_DATE != SOURCE.START_DATE OR
				TARGET.END_DATE != SOURCE.END_DATE OR
				TARGET.MI_DATE != SOURCE.MI_DATE OR
				TARGET.MO_DATE != SOURCE.MO_DATE OR
				TARGET.DECISION_DATE != SOURCE.DECISION_DATE OR
				TARGET.BOX_OFFICE != SOURCE.BOX_OFFICE OR
				TARGET.INSUR_REQ != SOURCE.INSUR_REQ OR
				TARGET.INSUR_REC != SOURCE.INSUR_REC OR
				TARGET.CONTRACT_STS != SOURCE.CONTRACT_STS OR
				TARGET.CONTRACT_ID != SOURCE.CONTRACT_ID OR
				TARGET.CM_FILE_NBR != SOURCE.CM_FILE_NBR OR
				TARGET.MTG_NBR != SOURCE.MTG_NBR OR
				TARGET.MTG_START_DATE != SOURCE.MTG_START_DATE OR
				TARGET.GROUP_NAME != SOURCE.GROUP_NAME OR
				TARGET.EST_REVENUE != SOURCE.EST_REVENUE OR
				TARGET.PLN_REVENUE != SOURCE.PLN_REVENUE OR
				TARGET.ACT_REVENUE != SOURCE.ACT_REVENUE OR
				TARGET.EST_ATTEND != SOURCE.EST_ATTEND OR
				TARGET.PLN_ATTEND != SOURCE.PLN_ATTEND OR
				TARGET.ACT_ATTEND != SOURCE.ACT_ATTEND OR
				TARGET.EST_COST != SOURCE.EST_COST OR
				TARGET.PLN_COST != SOURCE.PLN_COST OR
				TARGET.ACT_COST != SOURCE.ACT_COST OR
				TARGET.BOOKED_BY != SOURCE.BOOKED_BY OR
				TARGET.BOOKING_TYPE != SOURCE.BOOKING_TYPE OR
				TARGET.PUBLIC_YN != SOURCE.PUBLIC_YN OR
				TARGET.ON_SITE_OFFICE != SOURCE.ON_SITE_OFFICE OR
				TARGET.ON_SITE_PHONE != SOURCE.ON_SITE_PHONE OR
				TARGET.DURATION_CODE != SOURCE.DURATION_CODE OR
				TARGET.PRICE_LIST != SOURCE.PRICE_LIST OR
				TARGET.BKG_BOOK_DATE != SOURCE.BKG_BOOK_DATE OR
				TARGET.BKG_CHG_DATE != SOURCE.BKG_CHG_DATE OR
				TARGET.BKG_CNCL_DATE != SOURCE.BKG_CNCL_DATE OR
				TARGET.EVT_CATEGORY != SOURCE.EVT_CATEGORY OR
				TARGET.EVT_CLASS != SOURCE.EVT_CLASS OR
				TARGET.EVT_TYPE != SOURCE.EVT_TYPE OR
				TARGET.EVT_RANK != SOURCE.EVT_RANK OR
				TARGET.EVT_STATUS != SOURCE.EVT_STATUS OR
				TARGET.SLSPER != SOURCE.SLSPER OR
				TARGET.COORD_1 != SOURCE.COORD_1 OR
				TARGET.COORD_2 != SOURCE.COORD_2 OR
				TARGET.CUST_NBR != SOURCE.CUST_NBR OR
				TARGET.CUST_SUB_NBR != SOURCE.CUST_SUB_NBR OR
				TARGET.CUST_PO != SOURCE.CUST_PO OR
				TARGET.CUST_CNTCT_NAME != SOURCE.CUST_CNTCT_NAME OR
				TARGET.CUST_PHONE != SOURCE.CUST_PHONE OR
				TARGET.UPD_DATE != SOURCE.UPD_DATE OR
				TARGET.UPD_TIME != SOURCE.UPD_TIME OR
				TARGET.UPD_USER_ID != SOURCE.UPD_USER_ID OR
				TARGET.LAST_BILLED_DATE != SOURCE.LAST_BILLED_DATE OR
				TARGET.SLSPER_ORG != SOURCE.SLSPER_ORG OR
				TARGET.CUST_ORG != SOURCE.CUST_ORG OR
				TARGET.COORD1_ORG != SOURCE.COORD1_ORG OR
				TARGET.ECON_IMPACT_AMT != SOURCE.ECON_IMPACT_AMT OR
				TARGET.RETAIN_PCT != SOURCE.RETAIN_PCT OR
				TARGET.CONFLICT_STS != SOURCE.CONFLICT_STS OR
				TARGET.EVT_CODE_1 != SOURCE.EVT_CODE_1 OR
				TARGET.EVT_CODE_2 != SOURCE.EVT_CODE_2 OR
				TARGET.DESC_1 != SOURCE.DESC_1 OR
				TARGET.EVT_USR_CODE_1 != SOURCE.EVT_USR_CODE_1 OR
				TARGET.EVT_USR_ID != SOURCE.EVT_USR_ID OR
				TARGET.SEQ_NBR != SOURCE.SEQ_NBR OR
				TARGET.EVT_GL != SOURCE.EVT_GL OR
				TARGET.ADV_OFFSET != SOURCE.ADV_OFFSET OR
				TARGET.ADV_DAYS != SOURCE.ADV_DAYS OR
				TARGET.BADGE_FMT != SOURCE.BADGE_FMT OR
				TARGET.MAJ_GROUP != SOURCE.MAJ_GROUP OR
				TARGET.MIN_GROUP != SOURCE.MIN_GROUP OR
				TARGET.ANCHOR_VENUE != SOURCE.ANCHOR_VENUE OR
				TARGET.EVT_GLACCT != SOURCE.EVT_GLACCT OR
				TARGET.BDG_VOIDS != SOURCE.BDG_VOIDS OR
				TARGET.CANCEL_STAMP != SOURCE.CANCEL_STAMP OR
				TARGET.CANCEL_USER_ID != SOURCE.CANCEL_USER_ID OR
				TARGET.CANCEL_REASON != SOURCE.CANCEL_REASON OR
				TARGET.ORD_ATT_INDIC != SOURCE.ORD_ATT_INDIC OR
				TARGET.ACT_ATT_INDIC != SOURCE.ACT_ATT_INDIC OR
				TARGET.RVS_REVENUE != SOURCE.RVS_REVENUE OR
				TARGET.RVS_COST != SOURCE.RVS_COST OR
				TARGET.RVS_ATTEND != SOURCE.RVS_ATTEND OR
				TARGET.RVS_OTHER != SOURCE.RVS_OTHER OR
				TARGET.FOR_ATT_INDIC != SOURCE.FOR_ATT_INDIC OR
				TARGET.RVS_ATT_INDIC != SOURCE.RVS_ATT_INDIC OR
				TARGET.CAD_NAME != SOURCE.CAD_NAME OR
				TARGET.SENSITIVITY != SOURCE.SENSITIVITY OR
				TARGET.CANCEL_APPL != SOURCE.CANCEL_APPL OR
				TARGET.ALT_EVT_DESC != SOURCE.ALT_EVT_DESC OR
				TARGET.ALT_LEGAL_NAME != SOURCE.ALT_LEGAL_NAME OR
				TARGET.BKG_ENT_STAMP != SOURCE.BKG_ENT_STAMP OR
				TARGET.BKG_ENT_USER != SOURCE.BKG_ENT_USER OR
				TARGET.BKG_CHG_STAMP != SOURCE.BKG_CHG_STAMP OR
				TARGET.BKG_CHG_USER != SOURCE.BKG_CHG_USER OR
				TARGET.EVT_COORD3 != SOURCE.EVT_COORD3 OR
				TARGET.EVT_COORD4 != SOURCE.EVT_COORD4 OR
				TARGET.WEB_ADDRESS != SOURCE.WEB_ADDRESS OR
				TARGET.MASTER_EVT != SOURCE.MASTER_EVT OR
				TARGET.PREV_EVT != SOURCE.PREV_EVT OR
				TARGET.ALT_EVT_DESC2 != SOURCE.ALT_EVT_DESC2 OR
				TARGET.ALT_LEGAL_NAME2 != SOURCE.ALT_LEGAL_NAME2 OR
				TARGET.NG_EVT_CONTACT != SOURCE.NG_EVT_CONTACT OR
				TARGET.NG_BILLTO_CONTACT != SOURCE.NG_BILLTO_CONTACT OR
				TARGET.GLAA_CODE_01 != SOURCE.GLAA_CODE_01 OR
				TARGET.GLAA_CODE_02 != SOURCE.GLAA_CODE_02 OR
				TARGET.GLAA_CODE_03 != SOURCE.GLAA_CODE_03 OR
				TARGET.GLAA_CODE_04 != SOURCE.GLAA_CODE_04 OR
				TARGET.GLAA_CODE_05 != SOURCE.GLAA_CODE_05 OR
				TARGET.GLAA_CODE_06 != SOURCE.GLAA_CODE_06 OR
				TARGET.GLAA_CODE_07 != SOURCE.GLAA_CODE_07 OR
				TARGET.GLAA_CODE_08 != SOURCE.GLAA_CODE_08 OR
				TARGET.GLAA_CODE_09 != SOURCE.GLAA_CODE_09 OR
				TARGET.USE_GL_SUBS != SOURCE.USE_GL_SUBS OR
				TARGET.GLAA_OPER != SOURCE.GLAA_OPER OR
				TARGET.UPD_STAMP != SOURCE.UPD_STAMP OR
				TARGET.ENT_STAMP != SOURCE.ENT_STAMP OR
				TARGET.RVS_ATT_SYNC != SOURCE.RVS_ATT_SYNC OR
				TARGET.ORD_ATT_SYNC != SOURCE.ORD_ATT_SYNC OR
				TARGET.ACT_ATT_SYNC != SOURCE.ACT_ATT_SYNC OR
				TARGET.HSG_STDATE != SOURCE.HSG_STDATE OR
				TARGET.HSG_ENDATE != SOURCE.HSG_ENDATE OR
				TARGET.HSG_CUTOFF != SOURCE.HSG_CUTOFF OR
				TARGET.HSG_OFFICE != SOURCE.HSG_OFFICE OR
				TARGET.HSG_HQ_HOTEL != SOURCE.HSG_HQ_HOTEL OR
				TARGET.HSG_FLAG != SOURCE.HSG_FLAG OR
				TARGET.MI_OFFSET_HRS != SOURCE.MI_OFFSET_HRS OR
				TARGET.ST_OFFSET_HRS != SOURCE.ST_OFFSET_HRS OR
				TARGET.EN_OFFSET_HRS != SOURCE.EN_OFFSET_HRS OR
				TARGET.MO_OFFSET_HRS != SOURCE.MO_OFFSET_HRS OR
				TARGET.BADGE_XML != SOURCE.BADGE_XML OR
				TARGET.REG_PAY_SCHED != SOURCE.REG_PAY_SCHED OR
				TARGET.REG_PRLIST != SOURCE.REG_PRLIST OR
				TARGET.MULTI_ORG_ACCT != SOURCE.MULTI_ORG_ACCT OR
				TARGET.ALT_EVT != SOURCE.ALT_EVT OR
				TARGET.REG_ADV_CUTOFF != SOURCE.REG_ADV_CUTOFF OR
				TARGET.REG_STD_CUTOFF != SOURCE.REG_STD_CUTOFF OR
				TARGET.REGST_ISS_CLS != SOURCE.REGST_ISS_CLS OR
				TARGET.REGST_ISS_TYP != SOURCE.REGST_ISS_TYP OR
				TARGET.REG_ADV_OFFSET != SOURCE.REG_ADV_OFFSET OR
				TARGET.REG_ADV_DAYS != SOURCE.REG_ADV_DAYS OR
				TARGET.REG_STD_OFFSET != SOURCE.REG_STD_OFFSET OR
				TARGET.REG_STD_DAYS != SOURCE.REG_STD_DAYS OR
				TARGET.EVT_IN_DATE != SOURCE.EVT_IN_DATE OR
				TARGET.EVT_IN_TIME != SOURCE.EVT_IN_TIME OR
				TARGET.EVT_START_DATE != SOURCE.EVT_START_DATE OR
				TARGET.EVT_START_TIME != SOURCE.EVT_START_TIME OR
				TARGET.EVT_END_DATE != SOURCE.EVT_END_DATE OR
				TARGET.EVT_END_TIME != SOURCE.EVT_END_TIME OR
				TARGET.EVT_OUT_DATE != SOURCE.EVT_OUT_DATE OR
				TARGET.EVT_OUT_TIME != SOURCE.EVT_OUT_TIME OR
				TARGET.RELEASE_DATE != SOURCE.RELEASE_DATE OR
				TARGET.ADV_CUTOFF_DATE != SOURCE.ADV_CUTOFF_DATE OR
				TARGET.EVT_ABBREV_NAME != SOURCE.EVT_ABBREV_NAME OR
				TARGET.EVT_LEGAL_NAME != SOURCE.EVT_LEGAL_NAME OR
				TARGET.EVT_INDICATOR != SOURCE.EVT_INDICATOR OR
				TARGET.SO_ISSUE_CLASS != SOURCE.SO_ISSUE_CLASS OR
				TARGET.SO_ISSUE_TYPE != SOURCE.SO_ISSUE_TYPE OR
				TARGET.RG_ISSUE_CLASS != SOURCE.RG_ISSUE_CLASS OR
				TARGET.RG_ISSUE_TYPE != SOURCE.RG_ISSUE_TYPE OR
				TARGET.EVT_NOTE_1 != SOURCE.EVT_NOTE_1 OR
				TARGET.EVT_NOTE_2 != SOURCE.EVT_NOTE_2 OR
				TARGET.PROF_MI_SIGN != SOURCE.PROF_MI_SIGN OR
				TARGET.PROF_ST_SIGN != SOURCE.PROF_ST_SIGN OR
				TARGET.PROF_EN_SIGN != SOURCE.PROF_EN_SIGN OR
				TARGET.PROF_MO_SIGN != SOURCE.PROF_MO_SIGN OR
				TARGET.PROF_TIME_OFFSET != SOURCE.PROF_TIME_OFFSET OR
				TARGET.EVT_RELEASE_INDIC != SOURCE.EVT_RELEASE_INDIC OR
				TARGET.PROF_MI_DAYS != SOURCE.PROF_MI_DAYS OR
				TARGET.PROF_ST_DAYS != SOURCE.PROF_ST_DAYS OR
				TARGET.PROF_EN_DAYS != SOURCE.PROF_EN_DAYS OR
				TARGET.PROF_MO_DAYS != SOURCE.PROF_MO_DAYS OR
				TARGET.BILLTO_ACCT != SOURCE.BILLTO_ACCT OR
				TARGET.EVENT_DAYS != SOURCE.EVENT_DAYS OR
				TARGET.EVT_LOGO != SOURCE.EVT_LOGO OR
				TARGET.MAX_TOPIC_LVL != SOURCE.MAX_TOPIC_LVL OR
				TARGET.EST_OTHER != SOURCE.EST_OTHER OR
				TARGET.PLN_OTHER != SOURCE.PLN_OTHER OR
				TARGET.ACT_OTHER != SOURCE.ACT_OTHER OR
				TARGET.ALT_EVT_DESC3 != SOURCE.ALT_EVT_DESC3 OR
				TARGET.ALT_EVT_DESC4 != SOURCE.ALT_EVT_DESC4 OR
				TARGET.ALT_EVT_DESC5 != SOURCE.ALT_EVT_DESC5 OR
				TARGET.ALT_LEGAL_NAME3 != SOURCE.ALT_LEGAL_NAME3 OR
				TARGET.ALT_LEGAL_NAME4 != SOURCE.ALT_LEGAL_NAME4 OR
				TARGET.ALT_LEGAL_NAME5 != SOURCE.ALT_LEGAL_NAME5 OR
				TARGET.STD_CUTOFF_DATE != SOURCE.STD_CUTOFF_DATE OR
				TARGET.STD_OFFSET != SOURCE.STD_OFFSET OR
				TARGET.STD_DAYS != SOURCE.STD_DAYS OR
				TARGET.DATE_FMT != SOURCE.DATE_FMT OR
				TARGET.TIME_FMT != SOURCE.TIME_FMT OR
				TARGET.RES_FMT != SOURCE.RES_FMT OR
				TARGET.DECISION_DATE_ISO != SOURCE.DECISION_DATE_ISO OR
				TARGET.CONFL_ORD_STS != SOURCE.CONFL_ORD_STS OR
				TARGET.EXH_PROD_SYNC != SOURCE.EXH_PROD_SYNC OR
				TARGET.LOST_TO_VAL != SOURCE.LOST_TO_VAL OR
				TARGET.UNSCHED_FLAG != SOURCE.UNSCHED_FLAG OR
				TARGET.DEF_PAY_SCHED != SOURCE.DEF_PAY_SCHED OR
				TARGET.FIRM_DATE != SOURCE.FIRM_DATE OR
				TARGET.ASSET_CODE != SOURCE.ASSET_CODE OR
				TARGET.REQ_ACCT_CODE != SOURCE.REQ_ACCT_CODE OR
				TARGET.REQ_CNTCT_CODE != SOURCE.REQ_CNTCT_CODE OR
				TARGET.FN_ISSUE_CLASS != SOURCE.FN_ISSUE_CLASS OR
				TARGET.FN_ISSUE_TYPE != SOURCE.FN_ISSUE_TYPE OR
				TARGET.REG_PICKUP_TYPE != SOURCE.REG_PICKUP_TYPE OR
				TARGET.REG_PU_STDATE != SOURCE.REG_PU_STDATE OR
				TARGET.REG_PU_ENDATE != SOURCE.REG_PU_ENDATE OR
				TARGET.ALLOW_ROOMMATE != SOURCE.ALLOW_ROOMMATE OR
				TARGET.ENABLE_TRAVEL != SOURCE.ENABLE_TRAVEL OR
				TARGET.ORD_ISS_CLASS != SOURCE.ORD_ISS_CLASS OR
				TARGET.ORD_ISS_TYPE != SOURCE.ORD_ISS_TYPE OR
				TARGET.PURGE_IND != SOURCE.PURGE_IND OR
				TARGET.PURGE_VALIDATE != SOURCE.PURGE_VALIDATE OR
				TARGET.PURGE_STAMP != SOURCE.PURGE_STAMP OR
				TARGET.PURGE_USER_ID != SOURCE.PURGE_USER_ID OR
				TARGET.AVG_DAILY_RATE != SOURCE.AVG_DAILY_RATE OR
				TARGET.SPACE_GUEST_RATIO != SOURCE.SPACE_GUEST_RATIO OR
				TARGET.PEAK_NBR_RMS != SOURCE.PEAK_NBR_RMS OR
				TARGET.BOOKED_AREA != SOURCE.BOOKED_AREA OR
				TARGET.TRAVEL_TYPE != SOURCE.TRAVEL_TYPE OR
				TARGET.VAL_ASSIGN_AREA != SOURCE.VAL_ASSIGN_AREA OR
				TARGET.VAL_ASSIGN_DIM != SOURCE.VAL_ASSIGN_DIM OR
				TARGET.VAL_ASSIGN_DIM_INT != SOURCE.VAL_ASSIGN_DIM_INT OR
				TARGET.VAL_ASSIGN_OS != SOURCE.VAL_ASSIGN_OS OR
				TARGET.VAL_ASSIGN_FR != SOURCE.VAL_ASSIGN_FR OR
				TARGET.PURGE_VAL_USER_ID != SOURCE.PURGE_VAL_USER_ID OR
				TARGET.PRJ_ID != SOURCE.PRJ_ID OR
				TARGET.ACCT_DESIG != SOURCE.ACCT_DESIG OR
				TARGET.PROMPT_PROMO_CODE != SOURCE.PROMPT_PROMO_CODE OR
				TARGET.ECON_IMPACT != SOURCE.ECON_IMPACT OR
				TARGET.PORTAL_ID != SOURCE.PORTAL_ID OR
				TARGET.TAX_SCHEME != SOURCE.TAX_SCHEME OR
				TARGET.UNIQUE_ID != SOURCE.UNIQUE_ID OR
				TARGET.SOCIAL_NETWORK_1 != SOURCE.SOCIAL_NETWORK_1 OR
				TARGET.SOCIAL_NETWORK_2 != SOURCE.SOCIAL_NETWORK_2 OR
				TARGET.SOCIAL_NETWORK_3 != SOURCE.SOCIAL_NETWORK_3 OR
				TARGET.OUTLOOK_MEETING != SOURCE.OUTLOOK_MEETING OR
				TARGET.CC_AUTH_CFG != SOURCE.CC_AUTH_CFG OR
				TARGET.EVAL_ISS_TYPE != SOURCE.EVAL_ISS_TYPE OR
				TARGET.EXH_ISSUE_CLASS != SOURCE.EXH_ISSUE_CLASS OR
				TARGET.EXH_ISSUE_TYPE != SOURCE.EXH_ISSUE_TYPE OR
				TARGET.EXHIB_REG_RULE_TYPE != SOURCE.EXHIB_REG_RULE_TYPE OR
				TARGET.LINKED_FUNCS != SOURCE.LINKED_FUNCS OR
				TARGET.ENABLE_REG_APPR != SOURCE.ENABLE_REG_APPR )

			THEN UPDATE SET

				TARGET.EVT_SEARCH = SOURCE.EVT_SEARCH,
				TARGET.EVT_DESC = SOURCE.EVT_DESC,
				TARGET.EVT_DESIGNATION = SOURCE.EVT_DESIGNATION,
				TARGET.CONFIDENTIAL = SOURCE.CONFIDENTIAL,
				TARGET.START_DATE = SOURCE.START_DATE,
				TARGET.END_DATE = SOURCE.END_DATE,
				TARGET.MI_DATE = SOURCE.MI_DATE,
				TARGET.MO_DATE = SOURCE.MO_DATE,
				TARGET.DECISION_DATE = SOURCE.DECISION_DATE,
				TARGET.BOX_OFFICE = SOURCE.BOX_OFFICE,
				TARGET.INSUR_REQ = SOURCE.INSUR_REQ,
				TARGET.INSUR_REC = SOURCE.INSUR_REC,
				TARGET.CONTRACT_STS = SOURCE.CONTRACT_STS,
				TARGET.CONTRACT_ID = SOURCE.CONTRACT_ID,
				TARGET.CM_FILE_NBR = SOURCE.CM_FILE_NBR,
				TARGET.MTG_NBR = SOURCE.MTG_NBR,
				TARGET.MTG_START_DATE = SOURCE.MTG_START_DATE,
				TARGET.GROUP_NAME = SOURCE.GROUP_NAME,
				TARGET.EST_REVENUE = SOURCE.EST_REVENUE,
				TARGET.PLN_REVENUE = SOURCE.PLN_REVENUE,
				TARGET.ACT_REVENUE = SOURCE.ACT_REVENUE,
				TARGET.EST_ATTEND = SOURCE.EST_ATTEND,
				TARGET.PLN_ATTEND = SOURCE.PLN_ATTEND,
				TARGET.ACT_ATTEND = SOURCE.ACT_ATTEND,
				TARGET.EST_COST = SOURCE.EST_COST,
				TARGET.PLN_COST = SOURCE.PLN_COST,
				TARGET.ACT_COST = SOURCE.ACT_COST,
				TARGET.BOOKED_BY = SOURCE.BOOKED_BY,
				TARGET.BOOKING_TYPE = SOURCE.BOOKING_TYPE,
				TARGET.PUBLIC_YN = SOURCE.PUBLIC_YN,
				TARGET.ON_SITE_OFFICE = SOURCE.ON_SITE_OFFICE,
				TARGET.ON_SITE_PHONE = SOURCE.ON_SITE_PHONE,
				TARGET.DURATION_CODE = SOURCE.DURATION_CODE,
				TARGET.PRICE_LIST = SOURCE.PRICE_LIST,
				TARGET.BKG_BOOK_DATE = SOURCE.BKG_BOOK_DATE,
				TARGET.BKG_CHG_DATE = SOURCE.BKG_CHG_DATE,
				TARGET.BKG_CNCL_DATE = SOURCE.BKG_CNCL_DATE,
				TARGET.EVT_CATEGORY = SOURCE.EVT_CATEGORY,
				TARGET.EVT_CLASS = SOURCE.EVT_CLASS,
				TARGET.EVT_TYPE = SOURCE.EVT_TYPE,
				TARGET.EVT_RANK = SOURCE.EVT_RANK,
				TARGET.EVT_STATUS = SOURCE.EVT_STATUS,
				TARGET.SLSPER = SOURCE.SLSPER,
				TARGET.COORD_1 = SOURCE.COORD_1,
				TARGET.COORD_2 = SOURCE.COORD_2,
				TARGET.CUST_NBR = SOURCE.CUST_NBR,
				TARGET.CUST_SUB_NBR = SOURCE.CUST_SUB_NBR,
				TARGET.CUST_PO = SOURCE.CUST_PO,
				TARGET.CUST_CNTCT_NAME = SOURCE.CUST_CNTCT_NAME,
				TARGET.CUST_PHONE = SOURCE.CUST_PHONE,
				TARGET.UPD_DATE = SOURCE.UPD_DATE,
				TARGET.UPD_TIME = SOURCE.UPD_TIME,
				TARGET.UPD_USER_ID = SOURCE.UPD_USER_ID,
				TARGET.LAST_BILLED_DATE = SOURCE.LAST_BILLED_DATE,
				TARGET.SLSPER_ORG = SOURCE.SLSPER_ORG,
				TARGET.CUST_ORG = SOURCE.CUST_ORG,
				TARGET.COORD1_ORG = SOURCE.COORD1_ORG,
				TARGET.ECON_IMPACT_AMT = SOURCE.ECON_IMPACT_AMT,
				TARGET.RETAIN_PCT = SOURCE.RETAIN_PCT,
				TARGET.CONFLICT_STS = SOURCE.CONFLICT_STS,
				TARGET.EVT_CODE_1 = SOURCE.EVT_CODE_1,
				TARGET.EVT_CODE_2 = SOURCE.EVT_CODE_2,
				TARGET.DESC_1 = SOURCE.DESC_1,
				TARGET.EVT_USR_CODE_1 = SOURCE.EVT_USR_CODE_1,
				TARGET.EVT_USR_ID = SOURCE.EVT_USR_ID,
				TARGET.SEQ_NBR = SOURCE.SEQ_NBR,
				TARGET.EVT_GL = SOURCE.EVT_GL,
				TARGET.ADV_OFFSET = SOURCE.ADV_OFFSET,
				TARGET.ADV_DAYS = SOURCE.ADV_DAYS,
				TARGET.BADGE_FMT = SOURCE.BADGE_FMT,
				TARGET.MAJ_GROUP = SOURCE.MAJ_GROUP,
				TARGET.MIN_GROUP = SOURCE.MIN_GROUP,
				TARGET.ANCHOR_VENUE = SOURCE.ANCHOR_VENUE,
				TARGET.EVT_GLACCT = SOURCE.EVT_GLACCT,
				TARGET.BDG_VOIDS = SOURCE.BDG_VOIDS,
				TARGET.CANCEL_STAMP = SOURCE.CANCEL_STAMP,
				TARGET.CANCEL_USER_ID = SOURCE.CANCEL_USER_ID,
				TARGET.CANCEL_REASON = SOURCE.CANCEL_REASON,
				TARGET.ORD_ATT_INDIC = SOURCE.ORD_ATT_INDIC,
				TARGET.ACT_ATT_INDIC = SOURCE.ACT_ATT_INDIC,
				TARGET.RVS_REVENUE = SOURCE.RVS_REVENUE,
				TARGET.RVS_COST = SOURCE.RVS_COST,
				TARGET.RVS_ATTEND = SOURCE.RVS_ATTEND,
				TARGET.RVS_OTHER = SOURCE.RVS_OTHER,
				TARGET.FOR_ATT_INDIC = SOURCE.FOR_ATT_INDIC,
				TARGET.RVS_ATT_INDIC = SOURCE.RVS_ATT_INDIC,
				TARGET.CAD_NAME = SOURCE.CAD_NAME,
				TARGET.SENSITIVITY = SOURCE.SENSITIVITY,
				TARGET.CANCEL_APPL = SOURCE.CANCEL_APPL,
				TARGET.ALT_EVT_DESC = SOURCE.ALT_EVT_DESC,
				TARGET.ALT_LEGAL_NAME = SOURCE.ALT_LEGAL_NAME,
				TARGET.BKG_ENT_STAMP = SOURCE.BKG_ENT_STAMP,
				TARGET.BKG_ENT_USER = SOURCE.BKG_ENT_USER,
				TARGET.BKG_CHG_STAMP = SOURCE.BKG_CHG_STAMP,
				TARGET.BKG_CHG_USER = SOURCE.BKG_CHG_USER,
				TARGET.EVT_COORD3 = SOURCE.EVT_COORD3,
				TARGET.EVT_COORD4 = SOURCE.EVT_COORD4,
				TARGET.WEB_ADDRESS = SOURCE.WEB_ADDRESS,
				TARGET.MASTER_EVT = SOURCE.MASTER_EVT,
				TARGET.PREV_EVT = SOURCE.PREV_EVT,
				TARGET.ALT_EVT_DESC2 = SOURCE.ALT_EVT_DESC2,
				TARGET.ALT_LEGAL_NAME2 = SOURCE.ALT_LEGAL_NAME2,
				TARGET.NG_EVT_CONTACT = SOURCE.NG_EVT_CONTACT,
				TARGET.NG_BILLTO_CONTACT = SOURCE.NG_BILLTO_CONTACT,
				TARGET.GLAA_CODE_01 = SOURCE.GLAA_CODE_01,
				TARGET.GLAA_CODE_02 = SOURCE.GLAA_CODE_02,
				TARGET.GLAA_CODE_03 = SOURCE.GLAA_CODE_03,
				TARGET.GLAA_CODE_04 = SOURCE.GLAA_CODE_04,
				TARGET.GLAA_CODE_05 = SOURCE.GLAA_CODE_05,
				TARGET.GLAA_CODE_06 = SOURCE.GLAA_CODE_06,
				TARGET.GLAA_CODE_07 = SOURCE.GLAA_CODE_07,
				TARGET.GLAA_CODE_08 = SOURCE.GLAA_CODE_08,
				TARGET.GLAA_CODE_09 = SOURCE.GLAA_CODE_09,
				TARGET.USE_GL_SUBS = SOURCE.USE_GL_SUBS,
				TARGET.GLAA_OPER = SOURCE.GLAA_OPER,
				TARGET.UPD_STAMP = SOURCE.UPD_STAMP,
				TARGET.ENT_STAMP = SOURCE.ENT_STAMP,
				TARGET.RVS_ATT_SYNC = SOURCE.RVS_ATT_SYNC,
				TARGET.ORD_ATT_SYNC = SOURCE.ORD_ATT_SYNC,
				TARGET.ACT_ATT_SYNC = SOURCE.ACT_ATT_SYNC,
				TARGET.HSG_STDATE = SOURCE.HSG_STDATE,
				TARGET.HSG_ENDATE = SOURCE.HSG_ENDATE,
				TARGET.HSG_CUTOFF = SOURCE.HSG_CUTOFF,
				TARGET.HSG_OFFICE = SOURCE.HSG_OFFICE,
				TARGET.HSG_HQ_HOTEL = SOURCE.HSG_HQ_HOTEL,
				TARGET.HSG_FLAG = SOURCE.HSG_FLAG,
				TARGET.MI_OFFSET_HRS = SOURCE.MI_OFFSET_HRS,
				TARGET.ST_OFFSET_HRS = SOURCE.ST_OFFSET_HRS,
				TARGET.EN_OFFSET_HRS = SOURCE.EN_OFFSET_HRS,
				TARGET.MO_OFFSET_HRS = SOURCE.MO_OFFSET_HRS,
				TARGET.BADGE_XML = SOURCE.BADGE_XML,
				TARGET.REG_PAY_SCHED = SOURCE.REG_PAY_SCHED,
				TARGET.REG_PRLIST = SOURCE.REG_PRLIST,
				TARGET.MULTI_ORG_ACCT = SOURCE.MULTI_ORG_ACCT,
				TARGET.ALT_EVT = SOURCE.ALT_EVT,
				TARGET.REG_ADV_CUTOFF = SOURCE.REG_ADV_CUTOFF,
				TARGET.REG_STD_CUTOFF = SOURCE.REG_STD_CUTOFF,
				TARGET.REGST_ISS_CLS = SOURCE.REGST_ISS_CLS,
				TARGET.REGST_ISS_TYP = SOURCE.REGST_ISS_TYP,
				TARGET.REG_ADV_OFFSET = SOURCE.REG_ADV_OFFSET,
				TARGET.REG_ADV_DAYS = SOURCE.REG_ADV_DAYS,
				TARGET.REG_STD_OFFSET = SOURCE.REG_STD_OFFSET,
				TARGET.REG_STD_DAYS = SOURCE.REG_STD_DAYS,
				TARGET.EVT_IN_DATE = SOURCE.EVT_IN_DATE,
				TARGET.EVT_IN_TIME = SOURCE.EVT_IN_TIME,
				TARGET.EVT_START_DATE = SOURCE.EVT_START_DATE,
				TARGET.EVT_START_TIME = SOURCE.EVT_START_TIME,
				TARGET.EVT_END_DATE = SOURCE.EVT_END_DATE,
				TARGET.EVT_END_TIME = SOURCE.EVT_END_TIME,
				TARGET.EVT_OUT_DATE = SOURCE.EVT_OUT_DATE,
				TARGET.EVT_OUT_TIME = SOURCE.EVT_OUT_TIME,
				TARGET.RELEASE_DATE = SOURCE.RELEASE_DATE,
				TARGET.ADV_CUTOFF_DATE = SOURCE.ADV_CUTOFF_DATE,
				TARGET.EVT_ABBREV_NAME = SOURCE.EVT_ABBREV_NAME,
				TARGET.EVT_LEGAL_NAME = SOURCE.EVT_LEGAL_NAME,
				TARGET.EVT_INDICATOR = SOURCE.EVT_INDICATOR,
				TARGET.SO_ISSUE_CLASS = SOURCE.SO_ISSUE_CLASS,
				TARGET.SO_ISSUE_TYPE = SOURCE.SO_ISSUE_TYPE,
				TARGET.RG_ISSUE_CLASS = SOURCE.RG_ISSUE_CLASS,
				TARGET.RG_ISSUE_TYPE = SOURCE.RG_ISSUE_TYPE,
				TARGET.EVT_NOTE_1 = SOURCE.EVT_NOTE_1,
				TARGET.EVT_NOTE_2 = SOURCE.EVT_NOTE_2,
				TARGET.PROF_MI_SIGN = SOURCE.PROF_MI_SIGN,
				TARGET.PROF_ST_SIGN = SOURCE.PROF_ST_SIGN,
				TARGET.PROF_EN_SIGN = SOURCE.PROF_EN_SIGN,
				TARGET.PROF_MO_SIGN = SOURCE.PROF_MO_SIGN,
				TARGET.PROF_TIME_OFFSET = SOURCE.PROF_TIME_OFFSET,
				TARGET.EVT_RELEASE_INDIC = SOURCE.EVT_RELEASE_INDIC,
				TARGET.PROF_MI_DAYS = SOURCE.PROF_MI_DAYS,
				TARGET.PROF_ST_DAYS = SOURCE.PROF_ST_DAYS,
				TARGET.PROF_EN_DAYS = SOURCE.PROF_EN_DAYS,
				TARGET.PROF_MO_DAYS = SOURCE.PROF_MO_DAYS,
				TARGET.BILLTO_ACCT = SOURCE.BILLTO_ACCT,
				TARGET.EVENT_DAYS = SOURCE.EVENT_DAYS,
				TARGET.EVT_LOGO = SOURCE.EVT_LOGO,
				TARGET.MAX_TOPIC_LVL = SOURCE.MAX_TOPIC_LVL,
				TARGET.EST_OTHER = SOURCE.EST_OTHER,
				TARGET.PLN_OTHER = SOURCE.PLN_OTHER,
				TARGET.ACT_OTHER = SOURCE.ACT_OTHER,
				TARGET.ALT_EVT_DESC3 = SOURCE.ALT_EVT_DESC3,
				TARGET.ALT_EVT_DESC4 = SOURCE.ALT_EVT_DESC4,
				TARGET.ALT_EVT_DESC5 = SOURCE.ALT_EVT_DESC5,
				TARGET.ALT_LEGAL_NAME3 = SOURCE.ALT_LEGAL_NAME3,
				TARGET.ALT_LEGAL_NAME4 = SOURCE.ALT_LEGAL_NAME4,
				TARGET.ALT_LEGAL_NAME5 = SOURCE.ALT_LEGAL_NAME5,
				TARGET.STD_CUTOFF_DATE = SOURCE.STD_CUTOFF_DATE,
				TARGET.STD_OFFSET = SOURCE.STD_OFFSET,
				TARGET.STD_DAYS = SOURCE.STD_DAYS,
				TARGET.DATE_FMT = SOURCE.DATE_FMT,
				TARGET.TIME_FMT = SOURCE.TIME_FMT,
				TARGET.RES_FMT = SOURCE.RES_FMT,
				TARGET.DECISION_DATE_ISO = SOURCE.DECISION_DATE_ISO,
				TARGET.CONFL_ORD_STS = SOURCE.CONFL_ORD_STS,
				TARGET.EXH_PROD_SYNC = SOURCE.EXH_PROD_SYNC,
				TARGET.LOST_TO_VAL = SOURCE.LOST_TO_VAL,
				TARGET.UNSCHED_FLAG = SOURCE.UNSCHED_FLAG,
				TARGET.DEF_PAY_SCHED = SOURCE.DEF_PAY_SCHED,
				TARGET.FIRM_DATE = SOURCE.FIRM_DATE,
				TARGET.ASSET_CODE = SOURCE.ASSET_CODE,
				TARGET.REQ_ACCT_CODE = SOURCE.REQ_ACCT_CODE,
				TARGET.REQ_CNTCT_CODE = SOURCE.REQ_CNTCT_CODE,
				TARGET.FN_ISSUE_CLASS = SOURCE.FN_ISSUE_CLASS,
				TARGET.FN_ISSUE_TYPE = SOURCE.FN_ISSUE_TYPE,
				TARGET.REG_PICKUP_TYPE = SOURCE.REG_PICKUP_TYPE,
				TARGET.REG_PU_STDATE = SOURCE.REG_PU_STDATE,
				TARGET.REG_PU_ENDATE = SOURCE.REG_PU_ENDATE,
				TARGET.ALLOW_ROOMMATE = SOURCE.ALLOW_ROOMMATE,
				TARGET.ENABLE_TRAVEL = SOURCE.ENABLE_TRAVEL,
				TARGET.ORD_ISS_CLASS = SOURCE.ORD_ISS_CLASS,
				TARGET.ORD_ISS_TYPE = SOURCE.ORD_ISS_TYPE,
				TARGET.PURGE_IND = SOURCE.PURGE_IND,
				TARGET.PURGE_VALIDATE = SOURCE.PURGE_VALIDATE,
				TARGET.PURGE_STAMP = SOURCE.PURGE_STAMP,
				TARGET.PURGE_USER_ID = SOURCE.PURGE_USER_ID,
				TARGET.AVG_DAILY_RATE = SOURCE.AVG_DAILY_RATE,
				TARGET.SPACE_GUEST_RATIO = SOURCE.SPACE_GUEST_RATIO,
				TARGET.PEAK_NBR_RMS = SOURCE.PEAK_NBR_RMS,
				TARGET.BOOKED_AREA = SOURCE.BOOKED_AREA,
				TARGET.TRAVEL_TYPE = SOURCE.TRAVEL_TYPE,
				TARGET.VAL_ASSIGN_AREA = SOURCE.VAL_ASSIGN_AREA,
				TARGET.VAL_ASSIGN_DIM = SOURCE.VAL_ASSIGN_DIM,
				TARGET.VAL_ASSIGN_DIM_INT = SOURCE.VAL_ASSIGN_DIM_INT,
				TARGET.VAL_ASSIGN_OS = SOURCE.VAL_ASSIGN_OS,
				TARGET.VAL_ASSIGN_FR = SOURCE.VAL_ASSIGN_FR,
				TARGET.PURGE_VAL_USER_ID = SOURCE.PURGE_VAL_USER_ID,
				TARGET.PRJ_ID = SOURCE.PRJ_ID,
				TARGET.ACCT_DESIG = SOURCE.ACCT_DESIG,
				TARGET.PROMPT_PROMO_CODE = SOURCE.PROMPT_PROMO_CODE,
				TARGET.ECON_IMPACT = SOURCE.ECON_IMPACT,
				TARGET.PORTAL_ID = SOURCE.PORTAL_ID,
				TARGET.TAX_SCHEME = SOURCE.TAX_SCHEME,
				TARGET.UNIQUE_ID = SOURCE.UNIQUE_ID,
				TARGET.SOCIAL_NETWORK_1 = SOURCE.SOCIAL_NETWORK_1,
				TARGET.SOCIAL_NETWORK_2 = SOURCE.SOCIAL_NETWORK_2,
				TARGET.SOCIAL_NETWORK_3 = SOURCE.SOCIAL_NETWORK_3,
				TARGET.OUTLOOK_MEETING = SOURCE.OUTLOOK_MEETING,
				TARGET.CC_AUTH_CFG = SOURCE.CC_AUTH_CFG,
				TARGET.EVAL_ISS_TYPE = SOURCE.EVAL_ISS_TYPE,
				TARGET.EXH_ISSUE_CLASS = SOURCE.EXH_ISSUE_CLASS,
				TARGET.EXH_ISSUE_TYPE = SOURCE.EXH_ISSUE_TYPE,
				TARGET.EXHIB_REG_RULE_TYPE = SOURCE.EXHIB_REG_RULE_TYPE,
				TARGET.LINKED_FUNCS = SOURCE.LINKED_FUNCS,
				TARGET.ENABLE_REG_APPR = SOURCE.ENABLE_REG_APPR

			WHEN NOT MATCHED BY TARGET THEN INSERT (

				ORG_CODE,
				EVT_ID,
				EVT_SEARCH,
				EVT_DESC,
				EVT_DESIGNATION,
				CONFIDENTIAL,
				START_DATE,
				END_DATE,
				MI_DATE,
				MO_DATE,
				DECISION_DATE,
				BOX_OFFICE,
				INSUR_REQ,
				INSUR_REC,
				CONTRACT_STS,
				CONTRACT_ID,
				CM_FILE_NBR,
				MTG_NBR,
				MTG_START_DATE,
				GROUP_NAME,
				EST_REVENUE,
				PLN_REVENUE,
				ACT_REVENUE,
				EST_ATTEND,
				PLN_ATTEND,
				ACT_ATTEND,
				EST_COST,
				PLN_COST,
				ACT_COST,
				BOOKED_BY,
				BOOKING_TYPE,
				PUBLIC_YN,
				ON_SITE_OFFICE,
				ON_SITE_PHONE,
				DURATION_CODE,
				PRICE_LIST,
				BKG_BOOK_DATE,
				BKG_CHG_DATE,
				BKG_CNCL_DATE,
				EVT_CATEGORY,
				EVT_CLASS,
				EVT_TYPE,
				EVT_RANK,
				EVT_STATUS,
				SLSPER,
				COORD_1,
				COORD_2,
				CUST_NBR,
				CUST_SUB_NBR,
				CUST_PO,
				CUST_CNTCT_NAME,
				CUST_PHONE,
				UPD_DATE,
				UPD_TIME,
				UPD_USER_ID,
				LAST_BILLED_DATE,
				SLSPER_ORG,
				CUST_ORG,
				COORD1_ORG,
				ECON_IMPACT_AMT,
				RETAIN_PCT,
				CONFLICT_STS,
				EVT_CODE_1,
				EVT_CODE_2,
				DESC_1,
				EVT_USR_CODE_1,
				EVT_USR_ID,
				SEQ_NBR,
				EVT_GL,
				ADV_OFFSET,
				ADV_DAYS,
				BADGE_FMT,
				MAJ_GROUP,
				MIN_GROUP,
				ANCHOR_VENUE,
				EVT_GLACCT,
				BDG_VOIDS,
				CANCEL_STAMP,
				CANCEL_USER_ID,
				CANCEL_REASON,
				ORD_ATT_INDIC,
				ACT_ATT_INDIC,
				RVS_REVENUE,
				RVS_COST,
				RVS_ATTEND,
				RVS_OTHER,
				FOR_ATT_INDIC,
				RVS_ATT_INDIC,
				CAD_NAME,
				SENSITIVITY,
				CANCEL_APPL,
				ALT_EVT_DESC,
				ALT_LEGAL_NAME,
				BKG_ENT_STAMP,
				BKG_ENT_USER,
				BKG_CHG_STAMP,
				BKG_CHG_USER,
				EVT_COORD3,
				EVT_COORD4,
				WEB_ADDRESS,
				MASTER_EVT,
				PREV_EVT,
				ALT_EVT_DESC2,
				ALT_LEGAL_NAME2,
				NG_EVT_CONTACT,
				NG_BILLTO_CONTACT,
				GLAA_CODE_01,
				GLAA_CODE_02,
				GLAA_CODE_03,
				GLAA_CODE_04,
				GLAA_CODE_05,
				GLAA_CODE_06,
				GLAA_CODE_07,
				GLAA_CODE_08,
				GLAA_CODE_09,
				USE_GL_SUBS,
				GLAA_OPER,
				UPD_STAMP,
				ENT_STAMP,
				RVS_ATT_SYNC,
				ORD_ATT_SYNC,
				ACT_ATT_SYNC,
				HSG_STDATE,
				HSG_ENDATE,
				HSG_CUTOFF,
				HSG_OFFICE,
				HSG_HQ_HOTEL,
				HSG_FLAG,
				MI_OFFSET_HRS,
				ST_OFFSET_HRS,
				EN_OFFSET_HRS,
				MO_OFFSET_HRS,
				BADGE_XML,
				REG_PAY_SCHED,
				REG_PRLIST,
				MULTI_ORG_ACCT,
				ALT_EVT,
				REG_ADV_CUTOFF,
				REG_STD_CUTOFF,
				REGST_ISS_CLS,
				REGST_ISS_TYP,
				REG_ADV_OFFSET,
				REG_ADV_DAYS,
				REG_STD_OFFSET,
				REG_STD_DAYS,
				EVT_IN_DATE,
				EVT_IN_TIME,
				EVT_START_DATE,
				EVT_START_TIME,
				EVT_END_DATE,
				EVT_END_TIME,
				EVT_OUT_DATE,
				EVT_OUT_TIME,
				RELEASE_DATE,
				ADV_CUTOFF_DATE,
				EVT_ABBREV_NAME,
				EVT_LEGAL_NAME,
				EVT_INDICATOR,
				SO_ISSUE_CLASS,
				SO_ISSUE_TYPE,
				RG_ISSUE_CLASS,
				RG_ISSUE_TYPE,
				EVT_NOTE_1,
				EVT_NOTE_2,
				PROF_MI_SIGN,
				PROF_ST_SIGN,
				PROF_EN_SIGN,
				PROF_MO_SIGN,
				PROF_TIME_OFFSET,
				EVT_RELEASE_INDIC,
				PROF_MI_DAYS,
				PROF_ST_DAYS,
				PROF_EN_DAYS,
				PROF_MO_DAYS,
				BILLTO_ACCT,
				EVENT_DAYS,
				EVT_LOGO,
				MAX_TOPIC_LVL,
				EST_OTHER,
				PLN_OTHER,
				ACT_OTHER,
				ALT_EVT_DESC3,
				ALT_EVT_DESC4,
				ALT_EVT_DESC5,
				ALT_LEGAL_NAME3,
				ALT_LEGAL_NAME4,
				ALT_LEGAL_NAME5,
				STD_CUTOFF_DATE,
				STD_OFFSET,
				STD_DAYS,
				DATE_FMT,
				TIME_FMT,
				RES_FMT,
				DECISION_DATE_ISO,
				CONFL_ORD_STS,
				EXH_PROD_SYNC,
				LOST_TO_VAL,
				UNSCHED_FLAG,
				DEF_PAY_SCHED,
				FIRM_DATE,
				ASSET_CODE,
				REQ_ACCT_CODE,
				REQ_CNTCT_CODE,
				FN_ISSUE_CLASS,
				FN_ISSUE_TYPE,
				REG_PICKUP_TYPE,
				REG_PU_STDATE,
				REG_PU_ENDATE,
				ALLOW_ROOMMATE,
				ENABLE_TRAVEL,
				ORD_ISS_CLASS,
				ORD_ISS_TYPE,
				PURGE_IND,
				PURGE_VALIDATE,
				PURGE_STAMP,
				PURGE_USER_ID,
				AVG_DAILY_RATE,
				SPACE_GUEST_RATIO,
				PEAK_NBR_RMS,
				BOOKED_AREA,
				TRAVEL_TYPE,
				VAL_ASSIGN_AREA,
				VAL_ASSIGN_DIM,
				VAL_ASSIGN_DIM_INT,
				VAL_ASSIGN_OS,
				VAL_ASSIGN_FR,
				PURGE_VAL_USER_ID,
				PRJ_ID,
				ACCT_DESIG,
				PROMPT_PROMO_CODE,
				ECON_IMPACT,
				PORTAL_ID,
				TAX_SCHEME,
				UNIQUE_ID,
				SOCIAL_NETWORK_1,
				SOCIAL_NETWORK_2,
				SOCIAL_NETWORK_3,
				OUTLOOK_MEETING,
				CC_AUTH_CFG,
				EVAL_ISS_TYPE,
				EXH_ISSUE_CLASS,
				EXH_ISSUE_TYPE,
				EXHIB_REG_RULE_TYPE,
				LINKED_FUNCS,
				ENABLE_REG_APPR )

			VALUES (

				SOURCE.ORG_CODE,
				SOURCE.EVT_ID,
				SOURCE.EVT_SEARCH,
				SOURCE.EVT_DESC,
				SOURCE.EVT_DESIGNATION,
				SOURCE.CONFIDENTIAL,
				SOURCE.START_DATE,
				SOURCE.END_DATE,
				SOURCE.MI_DATE,
				SOURCE.MO_DATE,
				SOURCE.DECISION_DATE,
				SOURCE.BOX_OFFICE,
				SOURCE.INSUR_REQ,
				SOURCE.INSUR_REC,
				SOURCE.CONTRACT_STS,
				SOURCE.CONTRACT_ID,
				SOURCE.CM_FILE_NBR,
				SOURCE.MTG_NBR,
				SOURCE.MTG_START_DATE,
				SOURCE.GROUP_NAME,
				SOURCE.EST_REVENUE,
				SOURCE.PLN_REVENUE,
				SOURCE.ACT_REVENUE,
				SOURCE.EST_ATTEND,
				SOURCE.PLN_ATTEND,
				SOURCE.ACT_ATTEND,
				SOURCE.EST_COST,
				SOURCE.PLN_COST,
				SOURCE.ACT_COST,
				SOURCE.BOOKED_BY,
				SOURCE.BOOKING_TYPE,
				SOURCE.PUBLIC_YN,
				SOURCE.ON_SITE_OFFICE,
				SOURCE.ON_SITE_PHONE,
				SOURCE.DURATION_CODE,
				SOURCE.PRICE_LIST,
				SOURCE.BKG_BOOK_DATE,
				SOURCE.BKG_CHG_DATE,
				SOURCE.BKG_CNCL_DATE,
				SOURCE.EVT_CATEGORY,
				SOURCE.EVT_CLASS,
				SOURCE.EVT_TYPE,
				SOURCE.EVT_RANK,
				SOURCE.EVT_STATUS,
				SOURCE.SLSPER,
				SOURCE.COORD_1,
				SOURCE.COORD_2,
				SOURCE.CUST_NBR,
				SOURCE.CUST_SUB_NBR,
				SOURCE.CUST_PO,
				SOURCE.CUST_CNTCT_NAME,
				SOURCE.CUST_PHONE,
				SOURCE.UPD_DATE,
				SOURCE.UPD_TIME,
				SOURCE.UPD_USER_ID,
				SOURCE.LAST_BILLED_DATE,
				SOURCE.SLSPER_ORG,
				SOURCE.CUST_ORG,
				SOURCE.COORD1_ORG,
				SOURCE.ECON_IMPACT_AMT,
				SOURCE.RETAIN_PCT,
				SOURCE.CONFLICT_STS,
				SOURCE.EVT_CODE_1,
				SOURCE.EVT_CODE_2,
				SOURCE.DESC_1,
				SOURCE.EVT_USR_CODE_1,
				SOURCE.EVT_USR_ID,
				SOURCE.SEQ_NBR,
				SOURCE.EVT_GL,
				SOURCE.ADV_OFFSET,
				SOURCE.ADV_DAYS,
				SOURCE.BADGE_FMT,
				SOURCE.MAJ_GROUP,
				SOURCE.MIN_GROUP,
				SOURCE.ANCHOR_VENUE,
				SOURCE.EVT_GLACCT,
				SOURCE.BDG_VOIDS,
				SOURCE.CANCEL_STAMP,
				SOURCE.CANCEL_USER_ID,
				SOURCE.CANCEL_REASON,
				SOURCE.ORD_ATT_INDIC,
				SOURCE.ACT_ATT_INDIC,
				SOURCE.RVS_REVENUE,
				SOURCE.RVS_COST,
				SOURCE.RVS_ATTEND,
				SOURCE.RVS_OTHER,
				SOURCE.FOR_ATT_INDIC,
				SOURCE.RVS_ATT_INDIC,
				SOURCE.CAD_NAME,
				SOURCE.SENSITIVITY,
				SOURCE.CANCEL_APPL,
				SOURCE.ALT_EVT_DESC,
				SOURCE.ALT_LEGAL_NAME,
				SOURCE.BKG_ENT_STAMP,
				SOURCE.BKG_ENT_USER,
				SOURCE.BKG_CHG_STAMP,
				SOURCE.BKG_CHG_USER,
				SOURCE.EVT_COORD3,
				SOURCE.EVT_COORD4,
				SOURCE.WEB_ADDRESS,
				SOURCE.MASTER_EVT,
				SOURCE.PREV_EVT,
				SOURCE.ALT_EVT_DESC2,
				SOURCE.ALT_LEGAL_NAME2,
				SOURCE.NG_EVT_CONTACT,
				SOURCE.NG_BILLTO_CONTACT,
				SOURCE.GLAA_CODE_01,
				SOURCE.GLAA_CODE_02,
				SOURCE.GLAA_CODE_03,
				SOURCE.GLAA_CODE_04,
				SOURCE.GLAA_CODE_05,
				SOURCE.GLAA_CODE_06,
				SOURCE.GLAA_CODE_07,
				SOURCE.GLAA_CODE_08,
				SOURCE.GLAA_CODE_09,
				SOURCE.USE_GL_SUBS,
				SOURCE.GLAA_OPER,
				SOURCE.UPD_STAMP,
				SOURCE.ENT_STAMP,
				SOURCE.RVS_ATT_SYNC,
				SOURCE.ORD_ATT_SYNC,
				SOURCE.ACT_ATT_SYNC,
				SOURCE.HSG_STDATE,
				SOURCE.HSG_ENDATE,
				SOURCE.HSG_CUTOFF,
				SOURCE.HSG_OFFICE,
				SOURCE.HSG_HQ_HOTEL,
				SOURCE.HSG_FLAG,
				SOURCE.MI_OFFSET_HRS,
				SOURCE.ST_OFFSET_HRS,
				SOURCE.EN_OFFSET_HRS,
				SOURCE.MO_OFFSET_HRS,
				SOURCE.BADGE_XML,
				SOURCE.REG_PAY_SCHED,
				SOURCE.REG_PRLIST,
				SOURCE.MULTI_ORG_ACCT,
				SOURCE.ALT_EVT,
				SOURCE.REG_ADV_CUTOFF,
				SOURCE.REG_STD_CUTOFF,
				SOURCE.REGST_ISS_CLS,
				SOURCE.REGST_ISS_TYP,
				SOURCE.REG_ADV_OFFSET,
				SOURCE.REG_ADV_DAYS,
				SOURCE.REG_STD_OFFSET,
				SOURCE.REG_STD_DAYS,
				SOURCE.EVT_IN_DATE,
				SOURCE.EVT_IN_TIME,
				SOURCE.EVT_START_DATE,
				SOURCE.EVT_START_TIME,
				SOURCE.EVT_END_DATE,
				SOURCE.EVT_END_TIME,
				SOURCE.EVT_OUT_DATE,
				SOURCE.EVT_OUT_TIME,
				SOURCE.RELEASE_DATE,
				SOURCE.ADV_CUTOFF_DATE,
				SOURCE.EVT_ABBREV_NAME,
				SOURCE.EVT_LEGAL_NAME,
				SOURCE.EVT_INDICATOR,
				SOURCE.SO_ISSUE_CLASS,
				SOURCE.SO_ISSUE_TYPE,
				SOURCE.RG_ISSUE_CLASS,
				SOURCE.RG_ISSUE_TYPE,
				SOURCE.EVT_NOTE_1,
				SOURCE.EVT_NOTE_2,
				SOURCE.PROF_MI_SIGN,
				SOURCE.PROF_ST_SIGN,
				SOURCE.PROF_EN_SIGN,
				SOURCE.PROF_MO_SIGN,
				SOURCE.PROF_TIME_OFFSET,
				SOURCE.EVT_RELEASE_INDIC,
				SOURCE.PROF_MI_DAYS,
				SOURCE.PROF_ST_DAYS,
				SOURCE.PROF_EN_DAYS,
				SOURCE.PROF_MO_DAYS,
				SOURCE.BILLTO_ACCT,
				SOURCE.EVENT_DAYS,
				SOURCE.EVT_LOGO,
				SOURCE.MAX_TOPIC_LVL,
				SOURCE.EST_OTHER,
				SOURCE.PLN_OTHER,
				SOURCE.ACT_OTHER,
				SOURCE.ALT_EVT_DESC3,
				SOURCE.ALT_EVT_DESC4,
				SOURCE.ALT_EVT_DESC5,
				SOURCE.ALT_LEGAL_NAME3,
				SOURCE.ALT_LEGAL_NAME4,
				SOURCE.ALT_LEGAL_NAME5,
				SOURCE.STD_CUTOFF_DATE,
				SOURCE.STD_OFFSET,
				SOURCE.STD_DAYS,
				SOURCE.DATE_FMT,
				SOURCE.TIME_FMT,
				SOURCE.RES_FMT,
				SOURCE.DECISION_DATE_ISO,
				SOURCE.CONFL_ORD_STS,
				SOURCE.EXH_PROD_SYNC,
				SOURCE.LOST_TO_VAL,
				SOURCE.UNSCHED_FLAG,
				SOURCE.DEF_PAY_SCHED,
				SOURCE.FIRM_DATE,
				SOURCE.ASSET_CODE,
				SOURCE.REQ_ACCT_CODE,
				SOURCE.REQ_CNTCT_CODE,
				SOURCE.FN_ISSUE_CLASS,
				SOURCE.FN_ISSUE_TYPE,
				SOURCE.REG_PICKUP_TYPE,
				SOURCE.REG_PU_STDATE,
				SOURCE.REG_PU_ENDATE,
				SOURCE.ALLOW_ROOMMATE,
				SOURCE.ENABLE_TRAVEL,
				SOURCE.ORD_ISS_CLASS,
				SOURCE.ORD_ISS_TYPE,
				SOURCE.PURGE_IND,
				SOURCE.PURGE_VALIDATE,
				SOURCE.PURGE_STAMP,
				SOURCE.PURGE_USER_ID,
				SOURCE.AVG_DAILY_RATE,
				SOURCE.SPACE_GUEST_RATIO,
				SOURCE.PEAK_NBR_RMS,
				SOURCE.BOOKED_AREA,
				SOURCE.TRAVEL_TYPE,
				SOURCE.VAL_ASSIGN_AREA,
				SOURCE.VAL_ASSIGN_DIM,
				SOURCE.VAL_ASSIGN_DIM_INT,
				SOURCE.VAL_ASSIGN_OS,
				SOURCE.VAL_ASSIGN_FR,
				SOURCE.PURGE_VAL_USER_ID,
				SOURCE.PRJ_ID,
				SOURCE.ACCT_DESIG,
				SOURCE.PROMPT_PROMO_CODE,
				SOURCE.ECON_IMPACT,
				SOURCE.PORTAL_ID,
				SOURCE.TAX_SCHEME,
				SOURCE.UNIQUE_ID,
				SOURCE.SOCIAL_NETWORK_1,
				SOURCE.SOCIAL_NETWORK_2,
				SOURCE.SOCIAL_NETWORK_3,
				SOURCE.OUTLOOK_MEETING,
				SOURCE.CC_AUTH_CFG,
				SOURCE.EVAL_ISS_TYPE,
				SOURCE.EXH_ISSUE_CLASS,
				SOURCE.EXH_ISSUE_TYPE,
				SOURCE.EXHIB_REG_RULE_TYPE,
				SOURCE.LINKED_FUNCS,
				SOURCE.ENABLE_REG_APPR )

			WHEN NOT MATCHED BY SOURCE

				THEN DELETE

			OPTION (LOOP JOIN);

		COMMIT TRANSACTION;

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION;

		THROW;

	END CATCH;

END;