CREATE TABLE TRANSACTIONS
(
	[ORG_CODE] [nvarchar](2) NOT NULL,
	[EXT_ACCT_CODE] [nvarchar](8) NOT NULL,
	[SEQ] [int] NOT NULL,
	[TRANS_TYPE] [nvarchar](3) NULL,
	[TRANS_SOURCE] [nvarchar](2) NULL,
	[TRANS_METHOD] [nvarchar](3) NULL,
	[MEMO_TRANS] [nchar](1) NULL,
	[AMT] [numeric](11, 2) NULL 
		CONSTRAINT [DF_TVP_TRANSACTIONS_AMT] DEFAULT (0),
	[OPEN_AMT] [numeric](11, 2) NULL 
		CONSTRAINT [DF_TVP_TRANSACTIONS_OPEN_AMT] DEFAULT (0),
	[DISC_ALLOWED] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_DISC_ALLOWED] DEFAULT (0),
	[DISC_TAKEN] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_DISC_TAKEN] DEFAULT (0),
	[TRANS_DATE] [datetime] NULL,
	[DUE_DATE] [datetime] NULL,
	[FISCAL_YR] [int] NULL,
	[FISCAL_PERIOD] [int] NULL,
	[CLOSED_DATE] [datetime] NULL,
	[EVT_ID] [int] NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_EVT_ID] DEFAULT (0),
	[FUNC_ID] [int] NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FUNC_ID] DEFAULT (0),
	[ORD_NBR] [int] NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_ORD_NBR] DEFAULT (0),
	[STATEMENT_ID] [nvarchar](10) NULL,
	[STATEMENT_DATE] [datetime] NULL,
	[REFERENCE] [nvarchar](50) NULL,
	[CC_CHECK] [nvarchar](50) NULL,
	[CC_CONTROL] [nvarchar](1000) NULL,
	[CC_EXP_DATE] [datetime] NULL,
	[CC_NAME] [nvarchar](40) NULL,
	[CC_AUTHORIZED] [nvarchar](40) NULL,
	[REASON_CODE] [nvarchar](2) NULL,
	[LOCKBOX_ID] [nvarchar](6) NULL,
	[REMARK] [nvarchar](40) NULL,
	[LOCKBOX_DATE] [datetime] NULL,
	[LOCKBOX_BATCH_DATE] [datetime] NULL,
	[BANK_CODE] [nvarchar](2) NULL,
	[GL_DEBIT] [nvarchar](30) NULL,
	[GL_CREDIT] [nvarchar](30) NULL,
	[EXT_BATCH_ID] [nvarchar](10) NULL,
	[INT_BATCH_ID] [nvarchar](10) NULL,
	[GL_POSTING_DATE] [datetime] NULL,
	[GL_POSTED] [nchar](1) NULL,
	[STATUS] [nchar](1) NULL,
	[SETTLE_DATE] [datetime] NULL,
	[STS_1] [nchar](1) NULL,
	[STS_2] [nchar](1) NULL,
	[ORD_LINE] [int] NULL,
	[CONTACT] [nvarchar](8) NULL,
	[RES_TYPE] [nvarchar](6) NULL,
	[RES_CODE] [nvarchar](12) NULL,
	[DEL] [nchar](1) NULL,
	[CHG] [nchar](1) NULL,
	[ENT_DATE_ISO] [datetime] NULL,
	[ENT_TIME_ISO] [datetime] NULL,
	[ENT_USER_ID] [nvarchar](10) NULL,
	[UPD_DATE_ISO] [datetime] NULL,
	[UPD_TIME_ISO] [datetime] NULL,
	[UPD_USER_ID] [nvarchar](10) NULL,
	[TRANS_CLASS] [nchar](1) NULL,
	[INVOICE] [int] NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_INVOICE] DEFAULT (0),
	[FC_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FC_AMT] DEFAULT (0),
	[FC_CODE] [nvarchar](3) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FC_CODE] DEFAULT ('***'),
	[FC_OPEN_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FC_OPEN_AMT] DEFAULT (0),
	[FCA_SEQ] [int] NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FCA_SEQ] DEFAULT (0),
	[INTERNAL] [nchar](1) NULL,
	[APPLIED_SEQ] [int] NULL,
	[APPLIED_TO_SEQ] [int] NULL,
	[APPLIED_AMT] [numeric](11, 2) NULL,
	[APPLIED_TO_AMT] [numeric](11, 2) NULL,
	[APPLIED_DATE] [datetime] NULL,
	[APPLIED_USER_ID] [nvarchar](10) NULL,
	[APPLIED_TO_OPEN] [numeric](11, 2) NULL,
	[RECONCILED] [nchar](1) NULL,
	[FC_ADJ] [nchar](1) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FC_ADD] DEFAULT ('N'),
	[FC_ADJ_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FC_ADJ_AMT] DEFAULT (0),
	[PAID_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_PAID_AMT] DEFAULT (0),
	[PAID_CURRENCY] [nvarchar](3) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_PAID_CURRENCY] DEFAULT ('***'),
	[FCO_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_FCO_AMT] DEFAULT (0),
	[LC_ADJ_AMT] [numeric](11, 2) NULL
		CONSTRAINT [DF_TVP_TRANSACTIONS_LC_ADJ_AMT] DEFAULT (0),
	[NAME] [nvarchar](150) NULL,
	[ADDR1] [nvarchar](100) NULL,
	[ADDR2] [nvarchar](100) NULL,
	[ADDR3] [nvarchar](100) NULL,
	[CITY] [nvarchar](50) NULL,
	[STATE] [nvarchar](5) NULL,
	[POSTAL_CODE] [nvarchar](25) NULL,
	[COUNTRY_CODE] [nvarchar](3) NULL,
	[AUTHORIZED] [nvarchar](1) NULL,
	[TR_AMT] [numeric](11, 2) NULL,
	[PAY_PLAN_ID] [int] NULL,
	[GL_SOURCE] [nvarchar](2) NULL,
	[ENTRY_NBR] [nvarchar](7) NULL,
	[CONTROL_SEQ] [nvarchar](10) NULL,
	[INT_CHG_STS] [nvarchar](2) NULL,
	[INT_ACC_STS] [nvarchar](2) NULL,
	[ORIG_CC_CONTROL] [nvarchar](1000) NULL,
	[FIRST_NAME] [nvarchar](70) NULL,
	[LAST_NAME] [nvarchar](70) NULL,
	[ORD_DEPT] [nvarchar](6) NULL,
	[DELINQUENT_DATE] [datetime] NULL,
	[FINANCE_CHARGE] [numeric](11, 2) NULL,
	[LAST_FINANCE_DATE] [datetime] NULL,
	[FINANCE_CHARGE_EST] [numeric](11, 2) NULL,
	[LATE_NOTICE_DATE] [datetime] NULL,
	[PP_SCHED_CODE] [nvarchar](3) NULL,
	[TRANS_IND] [nvarchar](1) NULL,
	[CC_ID_FIELD] [nvarchar](50) NULL,
	[GRP_SEQ] [int] NULL,
	[GRP_TSM] [nvarchar](8) NULL,
	[GRP_STS] [nvarchar](3) NULL,
	[TSM] [nvarchar](8) NULL,
	[FYP] [nvarchar](6) NULL,
	[GL_FYP] [nvarchar](6) NULL,
	[GRP_DATE] [datetime] NULL,
	[FROM_ACCOUNT] [nvarchar](8) NULL,
	[TO_ACCOUNT] [nvarchar](8) NULL,
	[USER_REFERENCE] [nvarchar](50) NULL,
	[CC_EXP_DATE_ENC] [nvarchar](50) NULL,
	[CC_NBR_ENC] [nvarchar](100) NULL,
	[TOTAL_AMT] [decimal](13, 2) NULL,
	[TOTAL_FC_AMT] [decimal](13, 2) NULL,
	[TOTAL_INDIC] [nvarchar](1) NULL,
	[REF_INVOICE] [int] NULL,
	[REVERSE_SEQ] [int] NULL,
	[VOUCHER] [int] NULL,
	[CB_DEPOSIT_SEQ] [int] NULL,
	[TRANS_PRINT] [nvarchar](1) NULL,
	[BANK_AUTH_CODE] [nvarchar](100) NULL,
	[USER_REF_NBR1] [int] NULL,
	[USER_REF_NBR2] [int] NULL,
	[CARD_TYPE] [nvarchar](4) NULL,
	[CARD_ISSUE_NBR_ENC] [nvarchar](30) NULL,
	[CARD_START_MONTH_ENC] [nvarchar](30) NULL,
	[CARD_START_YEAR_ENC] [nvarchar](30) NULL,
	[LOCKBOX_BATCH] [int] NULL,
	[LOCKBOX_SEQ] [int] NULL,
	[CC_TOKEN] [nvarchar](256) NULL,
	[CC_SWIPE] [nvarchar](1) NULL,
	[AR_CONTROL] [nvarchar](10) NULL,
	[TRANSIT_NBR] [nvarchar](50) NULL,
	[ADJ_RCD_TYPE] [nvarchar](3) NULL,
	[MAIN_SEQ] [int] NULL,
	[TRANS_INFO_SEQ] [int] NULL,
	[BILL_PROFILE_TOKEN_ENC] [nvarchar](50) NULL,
	CONSTRAINT [PK_TRANSACTIONS] PRIMARY KEY CLUSTERED
	(
		[EXT_ACCT_CODE] ASC,
		[SEQ] ASC,
		[ORG_CODE] ASC
	)
);