CREATE TABLE [dbo].[EVT_REGIS](
	[ORG_CODE] [nvarchar](2) NOT NULL,
	[REG_SEQ] [int] NOT NULL,
	[EVT_ID] [int] NULL,
	[FUNC_ID] [int] NULL,
	[REG_CONTACT] [nvarchar](8) NULL,
	[STATUS] [nchar](1) NULL,
	[PRT_STATUS] [nchar](1) NULL,
	[CANCEL_DATE_ISO] [datetime] NULL,
	[CANCEL_TIME] [datetime] NULL,
	[CANCEL_USER_ID] [nvarchar](10) NULL,
	[CANCEL_BY] [nvarchar](30) NULL,
	[CANCEL_REASON] [nvarchar](2) NULL,
	[ORD_LINE] [int] NULL,
	[STATUS_2] [nchar](1) NULL,
	[REG_ACCT] [nvarchar](8) NULL,
	[STATUS_AT_PRINT] [nchar](1) NULL,
	[RM_NBR] [nvarchar](10) NULL,
	[ARR_DATE] [datetime] NULL,
	[ARR_TIME] [datetime] NULL,
	[ARR_VIA] [nvarchar](30) NULL,
	[ARR_LOC] [nvarchar](30) NULL,
	[ARR_PICKUP_TIME] [datetime] NULL,
	[ARR_PICKUP_DATE] [datetime] NULL,
	[ARR_PICKUP_LOC] [nvarchar](30) NULL,
	[ARR_TRANSPORTATION] [nvarchar](30) NULL,
	[DEP_DATE] [datetime] NULL,
	[DEP_TIME] [datetime] NULL,
	[DEP_VIA] [nvarchar](30) NULL,
	[DEP_LOCATION] [nvarchar](30) NULL,
	[DEP_PICKUP_DATE] [datetime] NULL,
	[DEP_PICKUP_TIME] [datetime] NULL,
	[DEP_PICKUP_LOC] [nvarchar](30) NULL,
	[DEP_TRANSPORTATION] [nvarchar](30) NULL,
	[LOCAL_TRANSPORTATION] [nvarchar](30) NULL,
	[FILL_092] [numeric](9, 2) NULL,
	[FILL_1X] [nchar](1) NULL,
	[FILL_1X2] [nchar](1) NULL,
	[FILL_1X3] [nchar](1) NULL,
	[FILL_20X] [nvarchar](20) NULL,
	[FILL_20X2] [nvarchar](20) NULL,
	[FILL_20X3] [nvarchar](20) NULL,
	[FILL_6X] [nvarchar](6) NULL,
	[FILL_6X2] [nvarchar](6) NULL,
	[FILL_6X4] [nvarchar](6) NULL,
	[FILL_6X5] [nvarchar](6) NULL,
	[FILL_10X] [nvarchar](10) NULL,
	[FILL_072] [numeric](9, 2) NULL,
	[FILL_30X] [nvarchar](30) NULL,
	[USER_PROFILE] [nvarchar](10) NULL,
	[ENT_DATE_ISO] [datetime] NULL,
	[ENT_TIME_ISO] [datetime] NULL,
	[ENT_USER_ID] [nvarchar](10) NULL,
	[UPD_DATE_ISO] [datetime] NULL,
	[UPD_TIME_ISO] [datetime] NULL,
	[UPD_USER_ID] [nvarchar](10) NULL,
	[ACCUM_EVT_ID] [int] NULL,
	[ACCUM_FUNC_ID] [int] NULL,
	[ACCUM_PHASE] [nchar](1) NULL,
	[ACCUM_RES_SEQ] [int] NULL,
	[DEL_MARK] [nchar](1) NULL,
	[USER_8X1] [nvarchar](8) NULL,
	[USER_8X2] [nvarchar](8) NULL,
	[USER_8X3] [nvarchar](10) NULL,
	[USER_10X] [nvarchar](10) NULL,
	[ORD_NBR] [int] NULL,
	[ORD_TYPE] [nvarchar](2) NULL,
	[ORD_ACCT] [nvarchar](8) NULL,
	[PRI_ACCT] [nvarchar](8) NULL,
	[SEC_ACCT] [nvarchar](8) NULL,
	[PRT_CONF] [nchar](1) NULL,
	[CO_NAME] [nvarchar](40) NULL,
	[CHKIN_STAMP] [datetime] NULL,
	[CHKIN_USER] [nvarchar](10) NULL,
	[REG_TYPE] [nvarchar](12) NULL,
	[AMT_01] [numeric](15, 4) NULL,
	[AMT_02] [numeric](15, 4) NULL,
	[AMT_03] [numeric](15, 4) NULL,
	[AMT_04] [numeric](15, 4) NULL,
	[AMT_05] [numeric](15, 4) NULL,
	[AMT_06] [numeric](15, 4) NULL,
	[AMT_07] [numeric](15, 4) NULL,
	[AMT_08] [numeric](15, 4) NULL,
	[AMT_09] [numeric](15, 4) NULL,
	[AMT_10] [numeric](15, 4) NULL,
	[AMT_11] [numeric](15, 4) NULL,
	[AMT_12] [numeric](15, 4) NULL,
	[AMT_13] [numeric](15, 4) NULL,
	[AMT_14] [numeric](15, 4) NULL,
	[AMT_15] [numeric](15, 4) NULL,
	[AMT_16] [numeric](15, 4) NULL,
	[AMT_17] [numeric](15, 4) NULL,
	[AMT_18] [numeric](15, 4) NULL,
	[AMT_19] [numeric](15, 4) NULL,
	[AMT_20] [numeric](15, 4) NULL,
	[AMT_21] [numeric](15, 4) NULL,
	[AMT_22] [numeric](15, 4) NULL,
	[AMT_23] [numeric](15, 4) NULL,
	[AMT_24] [numeric](15, 4) NULL,
	[AMT_25] [numeric](15, 4) NULL,
	[AMT_26] [numeric](15, 4) NULL,
	[AMT_27] [numeric](15, 4) NULL,
	[AMT_28] [numeric](15, 4) NULL,
	[AMT_29] [numeric](15, 4) NULL,
	[AMT_30] [numeric](15, 4) NULL,
	[DTS_01] [datetime] NULL,
	[DTS_02] [datetime] NULL,
	[DTS_03] [datetime] NULL,
	[DTS_04] [datetime] NULL,
	[DTS_05] [datetime] NULL,
	[DTS_06] [datetime] NULL,
	[DTS_07] [datetime] NULL,
	[DTS_08] [datetime] NULL,
	[DTS_09] [datetime] NULL,
	[DTS_10] [datetime] NULL,
	[DTS_11] [datetime] NULL,
	[DTS_12] [datetime] NULL,
	[DTS_13] [datetime] NULL,
	[DTS_14] [datetime] NULL,
	[DTS_15] [datetime] NULL,
	[DTS_16] [datetime] NULL,
	[DTS_17] [datetime] NULL,
	[DTS_18] [datetime] NULL,
	[DTS_19] [datetime] NULL,
	[DTS_20] [datetime] NULL,
	[TXT_01] [nvarchar](255) NULL,
	[TXT_02] [nvarchar](255) NULL,
	[TXT_03] [nvarchar](255) NULL,
	[TXT_04] [nvarchar](255) NULL,
	[TXT_05] [nvarchar](255) NULL,
	[TXT_06] [nvarchar](255) NULL,
	[TXT_07] [nvarchar](255) NULL,
	[TXT_08] [nvarchar](255) NULL,
	[TXT_09] [nvarchar](255) NULL,
	[TXT_10] [nvarchar](255) NULL,
	[TXT_11] [nvarchar](255) NULL,
	[TXT_12] [nvarchar](255) NULL,
	[TXT_13] [nvarchar](255) NULL,
	[TXT_14] [nvarchar](255) NULL,
	[TXT_15] [nvarchar](255) NULL,
	[TXT_16] [nvarchar](255) NULL,
	[TXT_17] [nvarchar](255) NULL,
	[TXT_18] [nvarchar](255) NULL,
	[TXT_19] [nvarchar](255) NULL,
	[TXT_20] [nvarchar](255) NULL,
	[TXT_21] [nvarchar](255) NULL,
	[TXT_22] [nvarchar](255) NULL,
	[TXT_23] [nvarchar](255) NULL,
	[TXT_24] [nvarchar](255) NULL,
	[TXT_25] [nvarchar](255) NULL,
	[TXT_26] [nvarchar](255) NULL,
	[TXT_27] [nvarchar](255) NULL,
	[TXT_28] [nvarchar](255) NULL,
	[TXT_29] [nvarchar](255) NULL,
	[TXT_30] [nvarchar](255) NULL,
	[TXT_31] [nvarchar](255) NULL,
	[TXT_32] [nvarchar](255) NULL,
	[TXT_33] [nvarchar](255) NULL,
	[TXT_34] [nvarchar](255) NULL,
	[TXT_35] [nvarchar](255) NULL,
	[TXT_36] [nvarchar](255) NULL,
	[TXT_37] [nvarchar](255) NULL,
	[TXT_38] [nvarchar](255) NULL,
	[TXT_39] [nvarchar](255) NULL,
	[TXT_40] [nvarchar](255) NULL,
	[TXT_41] [nvarchar](255) NULL,
	[TXT_42] [nvarchar](255) NULL,
	[TXT_43] [nvarchar](255) NULL,
	[TXT_44] [nvarchar](255) NULL,
	[TXT_45] [nvarchar](255) NULL,
	[TXT_46] [nvarchar](255) NULL,
	[TXT_47] [nvarchar](255) NULL,
	[TXT_48] [nvarchar](255) NULL,
	[TXT_49] [nvarchar](255) NULL,
	[TXT_50] [nvarchar](255) NULL,
	[ISSUE_CLASS] [nvarchar](1) NULL,
	[ISSUE_TYPE] [nvarchar](2) NULL,
	[MSTR_REG_ACCT_CODE] [nvarchar](8) NULL,
	[PU_NEEDED] [nvarchar](1) NULL,
	[PU_DATE] [datetime] NULL,
	[PU_TIME] [datetime] NULL,
	[PU_LOC_FROM] [nvarchar](100) NULL,
	[PU_LOC_TO] [nvarchar](100) NULL,
	[PU_REFERENCE] [nvarchar](255) NULL,
	[DO_NEEDED] [nvarchar](1) NULL,
	[DO_DATE] [datetime] NULL,
	[DO_TIME] [datetime] NULL,
	[DO_LOC_FROM] [nvarchar](100) NULL,
	[DO_LOC_TO] [nvarchar](100) NULL,
	[DO_REFERENCE] [nvarchar](255) NULL,
	[ROOM_SHARING] [nvarchar](2) NULL,
	[PREF_ROOMMATE] [nvarchar](100) NULL,
	[ROOMMATE_ACCT] [nvarchar](8) NULL,
	[AR_MODE] [nvarchar](100) NULL,
	[AR_DATE] [datetime] NULL,
	[AR_TIME] [datetime] NULL,
	[AR_LOC_FROM] [nvarchar](100) NULL,
	[AR_LOC_TO] [nvarchar](100) NULL,
	[AR_REFERENCE] [nvarchar](255) NULL,
	[AR_TRANS_NEED] [nvarchar](1) NULL,
	[AR_TRANS_MODE] [nvarchar](100) NULL,
	[AR_STATUS] [nvarchar](2) NULL,
	[DP_MODE] [nvarchar](100) NULL,
	[DP_DATE] [datetime] NULL,
	[DP_TIME] [datetime] NULL,
	[DP_LOC_FROM] [nvarchar](100) NULL,
	[DP_LOC_TO] [nvarchar](100) NULL,
	[DP_REFERENCE] [nvarchar](255) NULL,
	[DP_TRANS_NEED] [nvarchar](1) NULL,
	[DP_TRANS_MODE] [nvarchar](100) NULL,
	[DP_STATUS] [nvarchar](2) NULL,
	[BLOCK_CODE] [nvarchar](6) NULL,
	[EVT_REG_SEQ] [int] NULL,
	[APPR_LEVEL] [int] NULL,
	[APPR_ACTION] [nvarchar](1) NULL,
	[APPR_USER_ID] [nvarchar](10) NULL,
	[APPR_STAMP] [datetime] NULL,
	CONSTRAINT [PK_EVT_REGIS] PRIMARY KEY CLUSTERED
	(
		[REG_SEQ] ASC,
		[ORG_CODE] ASC
	)
);