#
# Module manifest for module 'CoolGuyModule'
#
# Generated by: Rusty Hann
#
# Generated on: 12/4/2015
#

@{
    # Version number of this module.
    ModuleVersion = '1.0.0.0'

    # ID used to uniquely identify this module
    GUID = '11111111-1111-1111-1111-111111111111'

    # Author of this module
    Author = 'Rusty Hann'

    # Company or vendor of this module
    CompanyName = ''

    # Copyright statement for this module
    Copyright = '(c) 2018 Evention LLC. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Provides PowerShell Commands.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Script module or binary module file associated with this manifest.
    RootModule = 'CoolGuyModule.psm1'

    # Functions to export from this module
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport = '*'
}
