---
# tasks file for AllServerSetup

- name: set sudoers file
  template:
    src: templates/hostname
    dest: "/etc/hostname"

- name: set hosts file
  template:
    src: templates/hosts
    dest: "/etc/hosts"

- name: set sudoers file
  template:
    src: templates/sudoers
    dest: "/etc/sudoers"

- name: 'apt-get update'
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: 'apt-get dist-upgrade'
  apt:
    upgrade: dist